// Code generated by ent, DO NOT EDIT.

package supportgrant

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the supportgrant type in the database.
	Label = "support_grant"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInstitutionID holds the string denoting the institution_id field in the database.
	FieldInstitutionID = "institution_id"
	// FieldGrantedByID holds the string denoting the granted_by_id field in the database.
	FieldGrantedByID = "granted_by_id"
	// FieldUsedByID holds the string denoting the used_by_id field in the database.
	FieldUsedByID = "used_by_id"
	// FieldTokenHash holds the string denoting the token_hash field in the database.
	FieldTokenHash = "token_hash"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldIsUsed holds the string denoting the is_used field in the database.
	FieldIsUsed = "is_used"
	// FieldUsedAt holds the string denoting the used_at field in the database.
	FieldUsedAt = "used_at"
	// FieldScope holds the string denoting the scope field in the database.
	FieldScope = "scope"
	// FieldWhitelistedIps holds the string denoting the whitelisted_ips field in the database.
	FieldWhitelistedIps = "whitelisted_ips"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the supportgrant in the database.
	Table = "gs_support_grants"
)

// Columns holds all SQL columns for supportgrant fields.
var Columns = []string{
	FieldID,
	FieldInstitutionID,
	FieldGrantedByID,
	FieldUsedByID,
	FieldTokenHash,
	FieldExpiresAt,
	FieldIsUsed,
	FieldUsedAt,
	FieldScope,
	FieldWhitelistedIps,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsUsed holds the default value on creation for the "is_used" field.
	DefaultIsUsed bool
	// DefaultScope holds the default value on creation for the "scope" field.
	DefaultScope string
	// DefaultWhitelistedIps holds the default value on creation for the "whitelisted_ips" field.
	DefaultWhitelistedIps []string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the SupportGrant queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInstitutionID orders the results by the institution_id field.
func ByInstitutionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstitutionID, opts...).ToFunc()
}

// ByGrantedByID orders the results by the granted_by_id field.
func ByGrantedByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrantedByID, opts...).ToFunc()
}

// ByUsedByID orders the results by the used_by_id field.
func ByUsedByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsedByID, opts...).ToFunc()
}

// ByTokenHash orders the results by the token_hash field.
func ByTokenHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenHash, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByIsUsed orders the results by the is_used field.
func ByIsUsed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsUsed, opts...).ToFunc()
}

// ByUsedAt orders the results by the used_at field.
func ByUsedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsedAt, opts...).ToFunc()
}

// ByScope orders the results by the scope field.
func ByScope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScope, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
