// Code generated by ent, DO NOT EDIT.

package supportgrant

import (
	"grantsupport/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldLTE(FieldID, id))
}

// InstitutionID applies equality check predicate on the "institution_id" field. It's identical to InstitutionIDEQ.
func InstitutionID(v uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldEQ(FieldInstitutionID, v))
}

// GrantedByID applies equality check predicate on the "granted_by_id" field. It's identical to GrantedByIDEQ.
func GrantedByID(v uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldEQ(FieldGrantedByID, v))
}

// UsedByID applies equality check predicate on the "used_by_id" field. It's identical to UsedByIDEQ.
func UsedByID(v uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldEQ(FieldUsedByID, v))
}

// TokenHash applies equality check predicate on the "token_hash" field. It's identical to TokenHashEQ.
func TokenHash(v string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldEQ(FieldTokenHash, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldEQ(FieldExpiresAt, v))
}

// IsUsed applies equality check predicate on the "is_used" field. It's identical to IsUsedEQ.
func IsUsed(v bool) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldEQ(FieldIsUsed, v))
}

// UsedAt applies equality check predicate on the "used_at" field. It's identical to UsedAtEQ.
func UsedAt(v time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldEQ(FieldUsedAt, v))
}

// Scope applies equality check predicate on the "scope" field. It's identical to ScopeEQ.
func Scope(v string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldEQ(FieldScope, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// InstitutionIDEQ applies the EQ predicate on the "institution_id" field.
func InstitutionIDEQ(v uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldEQ(FieldInstitutionID, v))
}

// InstitutionIDNEQ applies the NEQ predicate on the "institution_id" field.
func InstitutionIDNEQ(v uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldNEQ(FieldInstitutionID, v))
}

// InstitutionIDIn applies the In predicate on the "institution_id" field.
func InstitutionIDIn(vs ...uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldIn(FieldInstitutionID, vs...))
}

// InstitutionIDNotIn applies the NotIn predicate on the "institution_id" field.
func InstitutionIDNotIn(vs ...uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldNotIn(FieldInstitutionID, vs...))
}

// InstitutionIDGT applies the GT predicate on the "institution_id" field.
func InstitutionIDGT(v uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldGT(FieldInstitutionID, v))
}

// InstitutionIDGTE applies the GTE predicate on the "institution_id" field.
func InstitutionIDGTE(v uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldGTE(FieldInstitutionID, v))
}

// InstitutionIDLT applies the LT predicate on the "institution_id" field.
func InstitutionIDLT(v uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldLT(FieldInstitutionID, v))
}

// InstitutionIDLTE applies the LTE predicate on the "institution_id" field.
func InstitutionIDLTE(v uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldLTE(FieldInstitutionID, v))
}

// GrantedByIDEQ applies the EQ predicate on the "granted_by_id" field.
func GrantedByIDEQ(v uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldEQ(FieldGrantedByID, v))
}

// GrantedByIDNEQ applies the NEQ predicate on the "granted_by_id" field.
func GrantedByIDNEQ(v uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldNEQ(FieldGrantedByID, v))
}

// GrantedByIDIn applies the In predicate on the "granted_by_id" field.
func GrantedByIDIn(vs ...uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldIn(FieldGrantedByID, vs...))
}

// GrantedByIDNotIn applies the NotIn predicate on the "granted_by_id" field.
func GrantedByIDNotIn(vs ...uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldNotIn(FieldGrantedByID, vs...))
}

// GrantedByIDGT applies the GT predicate on the "granted_by_id" field.
func GrantedByIDGT(v uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldGT(FieldGrantedByID, v))
}

// GrantedByIDGTE applies the GTE predicate on the "granted_by_id" field.
func GrantedByIDGTE(v uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldGTE(FieldGrantedByID, v))
}

// GrantedByIDLT applies the LT predicate on the "granted_by_id" field.
func GrantedByIDLT(v uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldLT(FieldGrantedByID, v))
}

// GrantedByIDLTE applies the LTE predicate on the "granted_by_id" field.
func GrantedByIDLTE(v uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldLTE(FieldGrantedByID, v))
}

// UsedByIDEQ applies the EQ predicate on the "used_by_id" field.
func UsedByIDEQ(v uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldEQ(FieldUsedByID, v))
}

// UsedByIDNEQ applies the NEQ predicate on the "used_by_id" field.
func UsedByIDNEQ(v uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldNEQ(FieldUsedByID, v))
}

// UsedByIDIn applies the In predicate on the "used_by_id" field.
func UsedByIDIn(vs ...uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldIn(FieldUsedByID, vs...))
}

// UsedByIDNotIn applies the NotIn predicate on the "used_by_id" field.
func UsedByIDNotIn(vs ...uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldNotIn(FieldUsedByID, vs...))
}

// UsedByIDGT applies the GT predicate on the "used_by_id" field.
func UsedByIDGT(v uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldGT(FieldUsedByID, v))
}

// UsedByIDGTE applies the GTE predicate on the "used_by_id" field.
func UsedByIDGTE(v uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldGTE(FieldUsedByID, v))
}

// UsedByIDLT applies the LT predicate on the "used_by_id" field.
func UsedByIDLT(v uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldLT(FieldUsedByID, v))
}

// UsedByIDLTE applies the LTE predicate on the "used_by_id" field.
func UsedByIDLTE(v uuid.UUID) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldLTE(FieldUsedByID, v))
}

// UsedByIDIsNil applies the IsNil predicate on the "used_by_id" field.
func UsedByIDIsNil() predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldIsNull(FieldUsedByID))
}

// UsedByIDNotNil applies the NotNil predicate on the "used_by_id" field.
func UsedByIDNotNil() predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldNotNull(FieldUsedByID))
}

// TokenHashEQ applies the EQ predicate on the "token_hash" field.
func TokenHashEQ(v string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldEQ(FieldTokenHash, v))
}

// TokenHashNEQ applies the NEQ predicate on the "token_hash" field.
func TokenHashNEQ(v string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldNEQ(FieldTokenHash, v))
}

// TokenHashIn applies the In predicate on the "token_hash" field.
func TokenHashIn(vs ...string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldIn(FieldTokenHash, vs...))
}

// TokenHashNotIn applies the NotIn predicate on the "token_hash" field.
func TokenHashNotIn(vs ...string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldNotIn(FieldTokenHash, vs...))
}

// TokenHashGT applies the GT predicate on the "token_hash" field.
func TokenHashGT(v string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldGT(FieldTokenHash, v))
}

// TokenHashGTE applies the GTE predicate on the "token_hash" field.
func TokenHashGTE(v string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldGTE(FieldTokenHash, v))
}

// TokenHashLT applies the LT predicate on the "token_hash" field.
func TokenHashLT(v string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldLT(FieldTokenHash, v))
}

// TokenHashLTE applies the LTE predicate on the "token_hash" field.
func TokenHashLTE(v string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldLTE(FieldTokenHash, v))
}

// TokenHashContains applies the Contains predicate on the "token_hash" field.
func TokenHashContains(v string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldContains(FieldTokenHash, v))
}

// TokenHashHasPrefix applies the HasPrefix predicate on the "token_hash" field.
func TokenHashHasPrefix(v string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldHasPrefix(FieldTokenHash, v))
}

// TokenHashHasSuffix applies the HasSuffix predicate on the "token_hash" field.
func TokenHashHasSuffix(v string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldHasSuffix(FieldTokenHash, v))
}

// TokenHashEqualFold applies the EqualFold predicate on the "token_hash" field.
func TokenHashEqualFold(v string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldEqualFold(FieldTokenHash, v))
}

// TokenHashContainsFold applies the ContainsFold predicate on the "token_hash" field.
func TokenHashContainsFold(v string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldContainsFold(FieldTokenHash, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldLTE(FieldExpiresAt, v))
}

// IsUsedEQ applies the EQ predicate on the "is_used" field.
func IsUsedEQ(v bool) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldEQ(FieldIsUsed, v))
}

// IsUsedNEQ applies the NEQ predicate on the "is_used" field.
func IsUsedNEQ(v bool) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldNEQ(FieldIsUsed, v))
}

// UsedAtEQ applies the EQ predicate on the "used_at" field.
func UsedAtEQ(v time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldEQ(FieldUsedAt, v))
}

// UsedAtNEQ applies the NEQ predicate on the "used_at" field.
func UsedAtNEQ(v time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldNEQ(FieldUsedAt, v))
}

// UsedAtIn applies the In predicate on the "used_at" field.
func UsedAtIn(vs ...time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldIn(FieldUsedAt, vs...))
}

// UsedAtNotIn applies the NotIn predicate on the "used_at" field.
func UsedAtNotIn(vs ...time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldNotIn(FieldUsedAt, vs...))
}

// UsedAtGT applies the GT predicate on the "used_at" field.
func UsedAtGT(v time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldGT(FieldUsedAt, v))
}

// UsedAtGTE applies the GTE predicate on the "used_at" field.
func UsedAtGTE(v time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldGTE(FieldUsedAt, v))
}

// UsedAtLT applies the LT predicate on the "used_at" field.
func UsedAtLT(v time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldLT(FieldUsedAt, v))
}

// UsedAtLTE applies the LTE predicate on the "used_at" field.
func UsedAtLTE(v time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldLTE(FieldUsedAt, v))
}

// UsedAtIsNil applies the IsNil predicate on the "used_at" field.
func UsedAtIsNil() predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldIsNull(FieldUsedAt))
}

// UsedAtNotNil applies the NotNil predicate on the "used_at" field.
func UsedAtNotNil() predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldNotNull(FieldUsedAt))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldNotIn(FieldScope, vs...))
}

// ScopeGT applies the GT predicate on the "scope" field.
func ScopeGT(v string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldGT(FieldScope, v))
}

// ScopeGTE applies the GTE predicate on the "scope" field.
func ScopeGTE(v string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldGTE(FieldScope, v))
}

// ScopeLT applies the LT predicate on the "scope" field.
func ScopeLT(v string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldLT(FieldScope, v))
}

// ScopeLTE applies the LTE predicate on the "scope" field.
func ScopeLTE(v string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldLTE(FieldScope, v))
}

// ScopeContains applies the Contains predicate on the "scope" field.
func ScopeContains(v string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldContains(FieldScope, v))
}

// ScopeHasPrefix applies the HasPrefix predicate on the "scope" field.
func ScopeHasPrefix(v string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldHasPrefix(FieldScope, v))
}

// ScopeHasSuffix applies the HasSuffix predicate on the "scope" field.
func ScopeHasSuffix(v string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldHasSuffix(FieldScope, v))
}

// ScopeEqualFold applies the EqualFold predicate on the "scope" field.
func ScopeEqualFold(v string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldEqualFold(FieldScope, v))
}

// ScopeContainsFold applies the ContainsFold predicate on the "scope" field.
func ScopeContainsFold(v string) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldContainsFold(FieldScope, v))
}

// WhitelistedIpsIsNil applies the IsNil predicate on the "whitelisted_ips" field.
func WhitelistedIpsIsNil() predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldIsNull(FieldWhitelistedIps))
}

// WhitelistedIpsNotNil applies the NotNil predicate on the "whitelisted_ips" field.
func WhitelistedIpsNotNil() predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldNotNull(FieldWhitelistedIps))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SupportGrant {
	return predicate.SupportGrant(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SupportGrant) predicate.SupportGrant {
	return predicate.SupportGrant(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SupportGrant) predicate.SupportGrant {
	return predicate.SupportGrant(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SupportGrant) predicate.SupportGrant {
	return predicate.SupportGrant(sql.NotPredicates(p))
}
