// Code generated by ent, DO NOT EDIT.

package accessrequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the accessrequest type in the database.
	Label = "access_request"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInstitutionID holds the string denoting the institution_id field in the database.
	FieldInstitutionID = "institution_id"
	// FieldRequesterID holds the string denoting the requester_id field in the database.
	FieldRequesterID = "requester_id"
	// FieldTargetService holds the string denoting the target_service field in the database.
	FieldTargetService = "target_service"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldRequestedDurationMinutes holds the string denoting the requested_duration_minutes field in the database.
	FieldRequestedDurationMinutes = "requested_duration_minutes"
	// FieldApprovedDurationMinutes holds the string denoting the approved_duration_minutes field in the database.
	FieldApprovedDurationMinutes = "approved_duration_minutes"
	// FieldRequestedScope holds the string denoting the requested_scope field in the database.
	FieldRequestedScope = "requested_scope"
	// FieldApprovedScope holds the string denoting the approved_scope field in the database.
	FieldApprovedScope = "approved_scope"
	// FieldRequestedIps holds the string denoting the requested_ips field in the database.
	FieldRequestedIps = "requested_ips"
	// FieldApprovedIps holds the string denoting the approved_ips field in the database.
	FieldApprovedIps = "approved_ips"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldApprovedByID holds the string denoting the approved_by_id field in the database.
	FieldApprovedByID = "approved_by_id"
	// FieldApprovedAt holds the string denoting the approved_at field in the database.
	FieldApprovedAt = "approved_at"
	// FieldRejectedByID holds the string denoting the rejected_by_id field in the database.
	FieldRejectedByID = "rejected_by_id"
	// FieldRejectionReason holds the string denoting the rejection_reason field in the database.
	FieldRejectionReason = "rejection_reason"
	// FieldRejectedAt holds the string denoting the rejected_at field in the database.
	FieldRejectedAt = "rejected_at"
	// FieldCancelledAt holds the string denoting the cancelled_at field in the database.
	FieldCancelledAt = "cancelled_at"
	// FieldSupportGrantID holds the string denoting the support_grant_id field in the database.
	FieldSupportGrantID = "support_grant_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the accessrequest in the database.
	Table = "gs_access_requests"
)

// Columns holds all SQL columns for accessrequest fields.
var Columns = []string{
	FieldID,
	FieldInstitutionID,
	FieldRequesterID,
	FieldTargetService,
	FieldReason,
	FieldRequestedDurationMinutes,
	FieldApprovedDurationMinutes,
	FieldRequestedScope,
	FieldApprovedScope,
	FieldRequestedIps,
	FieldApprovedIps,
	FieldStatus,
	FieldExpiresAt,
	FieldApprovedByID,
	FieldApprovedAt,
	FieldRejectedByID,
	FieldRejectionReason,
	FieldRejectedAt,
	FieldCancelledAt,
	FieldSupportGrantID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TargetServiceValidator is a validator for the "target_service" field. It is called by the builders before save.
	TargetServiceValidator func(string) error
	// ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	ReasonValidator func(string) error
	// RequestedDurationMinutesValidator is a validator for the "requested_duration_minutes" field. It is called by the builders before save.
	RequestedDurationMinutesValidator func(int) error
	// DefaultRequestedScope holds the default value on creation for the "requested_scope" field.
	DefaultRequestedScope string
	// DefaultRequestedIps holds the default value on creation for the "requested_ips" field.
	DefaultRequestedIps []string
	// DefaultApprovedIps holds the default value on creation for the "approved_ips" field.
	DefaultApprovedIps []string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the AccessRequest queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInstitutionID orders the results by the institution_id field.
func ByInstitutionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstitutionID, opts...).ToFunc()
}

// ByRequesterID orders the results by the requester_id field.
func ByRequesterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequesterID, opts...).ToFunc()
}

// ByTargetService orders the results by the target_service field.
func ByTargetService(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetService, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByRequestedDurationMinutes orders the results by the requested_duration_minutes field.
func ByRequestedDurationMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedDurationMinutes, opts...).ToFunc()
}

// ByApprovedDurationMinutes orders the results by the approved_duration_minutes field.
func ByApprovedDurationMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApprovedDurationMinutes, opts...).ToFunc()
}

// ByRequestedScope orders the results by the requested_scope field.
func ByRequestedScope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedScope, opts...).ToFunc()
}

// ByApprovedScope orders the results by the approved_scope field.
func ByApprovedScope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApprovedScope, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByApprovedByID orders the results by the approved_by_id field.
func ByApprovedByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApprovedByID, opts...).ToFunc()
}

// ByApprovedAt orders the results by the approved_at field.
func ByApprovedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApprovedAt, opts...).ToFunc()
}

// ByRejectedByID orders the results by the rejected_by_id field.
func ByRejectedByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRejectedByID, opts...).ToFunc()
}

// ByRejectionReason orders the results by the rejection_reason field.
func ByRejectionReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRejectionReason, opts...).ToFunc()
}

// ByRejectedAt orders the results by the rejected_at field.
func ByRejectedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRejectedAt, opts...).ToFunc()
}

// ByCancelledAt orders the results by the cancelled_at field.
func ByCancelledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancelledAt, opts...).ToFunc()
}

// BySupportGrantID orders the results by the support_grant_id field.
func BySupportGrantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupportGrantID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
