// Code generated by ent, DO NOT EDIT.

package accessrequest

import (
	"grantsupport/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldID, id))
}

// InstitutionID applies equality check predicate on the "institution_id" field. It's identical to InstitutionIDEQ.
func InstitutionID(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldInstitutionID, v))
}

// RequesterID applies equality check predicate on the "requester_id" field. It's identical to RequesterIDEQ.
func RequesterID(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldRequesterID, v))
}

// TargetService applies equality check predicate on the "target_service" field. It's identical to TargetServiceEQ.
func TargetService(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldTargetService, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldReason, v))
}

// RequestedDurationMinutes applies equality check predicate on the "requested_duration_minutes" field. It's identical to RequestedDurationMinutesEQ.
func RequestedDurationMinutes(v int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldRequestedDurationMinutes, v))
}

// ApprovedDurationMinutes applies equality check predicate on the "approved_duration_minutes" field. It's identical to ApprovedDurationMinutesEQ.
func ApprovedDurationMinutes(v int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldApprovedDurationMinutes, v))
}

// RequestedScope applies equality check predicate on the "requested_scope" field. It's identical to RequestedScopeEQ.
func RequestedScope(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldRequestedScope, v))
}

// ApprovedScope applies equality check predicate on the "approved_scope" field. It's identical to ApprovedScopeEQ.
func ApprovedScope(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldApprovedScope, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldStatus, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldExpiresAt, v))
}

// ApprovedByID applies equality check predicate on the "approved_by_id" field. It's identical to ApprovedByIDEQ.
func ApprovedByID(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldApprovedByID, v))
}

// ApprovedAt applies equality check predicate on the "approved_at" field. It's identical to ApprovedAtEQ.
func ApprovedAt(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldApprovedAt, v))
}

// RejectedByID applies equality check predicate on the "rejected_by_id" field. It's identical to RejectedByIDEQ.
func RejectedByID(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldRejectedByID, v))
}

// RejectionReason applies equality check predicate on the "rejection_reason" field. It's identical to RejectionReasonEQ.
func RejectionReason(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldRejectionReason, v))
}

// RejectedAt applies equality check predicate on the "rejected_at" field. It's identical to RejectedAtEQ.
func RejectedAt(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldRejectedAt, v))
}

// CancelledAt applies equality check predicate on the "cancelled_at" field. It's identical to CancelledAtEQ.
func CancelledAt(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldCancelledAt, v))
}

// SupportGrantID applies equality check predicate on the "support_grant_id" field. It's identical to SupportGrantIDEQ.
func SupportGrantID(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldSupportGrantID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// InstitutionIDEQ applies the EQ predicate on the "institution_id" field.
func InstitutionIDEQ(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldInstitutionID, v))
}

// InstitutionIDNEQ applies the NEQ predicate on the "institution_id" field.
func InstitutionIDNEQ(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldInstitutionID, v))
}

// InstitutionIDIn applies the In predicate on the "institution_id" field.
func InstitutionIDIn(vs ...uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldInstitutionID, vs...))
}

// InstitutionIDNotIn applies the NotIn predicate on the "institution_id" field.
func InstitutionIDNotIn(vs ...uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldInstitutionID, vs...))
}

// InstitutionIDGT applies the GT predicate on the "institution_id" field.
func InstitutionIDGT(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldInstitutionID, v))
}

// InstitutionIDGTE applies the GTE predicate on the "institution_id" field.
func InstitutionIDGTE(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldInstitutionID, v))
}

// InstitutionIDLT applies the LT predicate on the "institution_id" field.
func InstitutionIDLT(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldInstitutionID, v))
}

// InstitutionIDLTE applies the LTE predicate on the "institution_id" field.
func InstitutionIDLTE(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldInstitutionID, v))
}

// RequesterIDEQ applies the EQ predicate on the "requester_id" field.
func RequesterIDEQ(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldRequesterID, v))
}

// RequesterIDNEQ applies the NEQ predicate on the "requester_id" field.
func RequesterIDNEQ(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldRequesterID, v))
}

// RequesterIDIn applies the In predicate on the "requester_id" field.
func RequesterIDIn(vs ...uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldRequesterID, vs...))
}

// RequesterIDNotIn applies the NotIn predicate on the "requester_id" field.
func RequesterIDNotIn(vs ...uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldRequesterID, vs...))
}

// RequesterIDGT applies the GT predicate on the "requester_id" field.
func RequesterIDGT(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldRequesterID, v))
}

// RequesterIDGTE applies the GTE predicate on the "requester_id" field.
func RequesterIDGTE(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldRequesterID, v))
}

// RequesterIDLT applies the LT predicate on the "requester_id" field.
func RequesterIDLT(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldRequesterID, v))
}

// RequesterIDLTE applies the LTE predicate on the "requester_id" field.
func RequesterIDLTE(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldRequesterID, v))
}

// TargetServiceEQ applies the EQ predicate on the "target_service" field.
func TargetServiceEQ(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldTargetService, v))
}

// TargetServiceNEQ applies the NEQ predicate on the "target_service" field.
func TargetServiceNEQ(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldTargetService, v))
}

// TargetServiceIn applies the In predicate on the "target_service" field.
func TargetServiceIn(vs ...string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldTargetService, vs...))
}

// TargetServiceNotIn applies the NotIn predicate on the "target_service" field.
func TargetServiceNotIn(vs ...string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldTargetService, vs...))
}

// TargetServiceGT applies the GT predicate on the "target_service" field.
func TargetServiceGT(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldTargetService, v))
}

// TargetServiceGTE applies the GTE predicate on the "target_service" field.
func TargetServiceGTE(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldTargetService, v))
}

// TargetServiceLT applies the LT predicate on the "target_service" field.
func TargetServiceLT(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldTargetService, v))
}

// TargetServiceLTE applies the LTE predicate on the "target_service" field.
func TargetServiceLTE(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldTargetService, v))
}

// TargetServiceContains applies the Contains predicate on the "target_service" field.
func TargetServiceContains(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldContains(FieldTargetService, v))
}

// TargetServiceHasPrefix applies the HasPrefix predicate on the "target_service" field.
func TargetServiceHasPrefix(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldHasPrefix(FieldTargetService, v))
}

// TargetServiceHasSuffix applies the HasSuffix predicate on the "target_service" field.
func TargetServiceHasSuffix(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldHasSuffix(FieldTargetService, v))
}

// TargetServiceIsNil applies the IsNil predicate on the "target_service" field.
func TargetServiceIsNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIsNull(FieldTargetService))
}

// TargetServiceNotNil applies the NotNil predicate on the "target_service" field.
func TargetServiceNotNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotNull(FieldTargetService))
}

// TargetServiceEqualFold applies the EqualFold predicate on the "target_service" field.
func TargetServiceEqualFold(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEqualFold(FieldTargetService, v))
}

// TargetServiceContainsFold applies the ContainsFold predicate on the "target_service" field.
func TargetServiceContainsFold(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldContainsFold(FieldTargetService, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldContainsFold(FieldReason, v))
}

// RequestedDurationMinutesEQ applies the EQ predicate on the "requested_duration_minutes" field.
func RequestedDurationMinutesEQ(v int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldRequestedDurationMinutes, v))
}

// RequestedDurationMinutesNEQ applies the NEQ predicate on the "requested_duration_minutes" field.
func RequestedDurationMinutesNEQ(v int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldRequestedDurationMinutes, v))
}

// RequestedDurationMinutesIn applies the In predicate on the "requested_duration_minutes" field.
func RequestedDurationMinutesIn(vs ...int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldRequestedDurationMinutes, vs...))
}

// RequestedDurationMinutesNotIn applies the NotIn predicate on the "requested_duration_minutes" field.
func RequestedDurationMinutesNotIn(vs ...int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldRequestedDurationMinutes, vs...))
}

// RequestedDurationMinutesGT applies the GT predicate on the "requested_duration_minutes" field.
func RequestedDurationMinutesGT(v int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldRequestedDurationMinutes, v))
}

// RequestedDurationMinutesGTE applies the GTE predicate on the "requested_duration_minutes" field.
func RequestedDurationMinutesGTE(v int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldRequestedDurationMinutes, v))
}

// RequestedDurationMinutesLT applies the LT predicate on the "requested_duration_minutes" field.
func RequestedDurationMinutesLT(v int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldRequestedDurationMinutes, v))
}

// RequestedDurationMinutesLTE applies the LTE predicate on the "requested_duration_minutes" field.
func RequestedDurationMinutesLTE(v int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldRequestedDurationMinutes, v))
}

// ApprovedDurationMinutesEQ applies the EQ predicate on the "approved_duration_minutes" field.
func ApprovedDurationMinutesEQ(v int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldApprovedDurationMinutes, v))
}

// ApprovedDurationMinutesNEQ applies the NEQ predicate on the "approved_duration_minutes" field.
func ApprovedDurationMinutesNEQ(v int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldApprovedDurationMinutes, v))
}

// ApprovedDurationMinutesIn applies the In predicate on the "approved_duration_minutes" field.
func ApprovedDurationMinutesIn(vs ...int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldApprovedDurationMinutes, vs...))
}

// ApprovedDurationMinutesNotIn applies the NotIn predicate on the "approved_duration_minutes" field.
func ApprovedDurationMinutesNotIn(vs ...int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldApprovedDurationMinutes, vs...))
}

// ApprovedDurationMinutesGT applies the GT predicate on the "approved_duration_minutes" field.
func ApprovedDurationMinutesGT(v int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldApprovedDurationMinutes, v))
}

// ApprovedDurationMinutesGTE applies the GTE predicate on the "approved_duration_minutes" field.
func ApprovedDurationMinutesGTE(v int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldApprovedDurationMinutes, v))
}

// ApprovedDurationMinutesLT applies the LT predicate on the "approved_duration_minutes" field.
func ApprovedDurationMinutesLT(v int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldApprovedDurationMinutes, v))
}

// ApprovedDurationMinutesLTE applies the LTE predicate on the "approved_duration_minutes" field.
func ApprovedDurationMinutesLTE(v int) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldApprovedDurationMinutes, v))
}

// ApprovedDurationMinutesIsNil applies the IsNil predicate on the "approved_duration_minutes" field.
func ApprovedDurationMinutesIsNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIsNull(FieldApprovedDurationMinutes))
}

// ApprovedDurationMinutesNotNil applies the NotNil predicate on the "approved_duration_minutes" field.
func ApprovedDurationMinutesNotNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotNull(FieldApprovedDurationMinutes))
}

// RequestedScopeEQ applies the EQ predicate on the "requested_scope" field.
func RequestedScopeEQ(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldRequestedScope, v))
}

// RequestedScopeNEQ applies the NEQ predicate on the "requested_scope" field.
func RequestedScopeNEQ(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldRequestedScope, v))
}

// RequestedScopeIn applies the In predicate on the "requested_scope" field.
func RequestedScopeIn(vs ...string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldRequestedScope, vs...))
}

// RequestedScopeNotIn applies the NotIn predicate on the "requested_scope" field.
func RequestedScopeNotIn(vs ...string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldRequestedScope, vs...))
}

// RequestedScopeGT applies the GT predicate on the "requested_scope" field.
func RequestedScopeGT(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldRequestedScope, v))
}

// RequestedScopeGTE applies the GTE predicate on the "requested_scope" field.
func RequestedScopeGTE(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldRequestedScope, v))
}

// RequestedScopeLT applies the LT predicate on the "requested_scope" field.
func RequestedScopeLT(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldRequestedScope, v))
}

// RequestedScopeLTE applies the LTE predicate on the "requested_scope" field.
func RequestedScopeLTE(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldRequestedScope, v))
}

// RequestedScopeContains applies the Contains predicate on the "requested_scope" field.
func RequestedScopeContains(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldContains(FieldRequestedScope, v))
}

// RequestedScopeHasPrefix applies the HasPrefix predicate on the "requested_scope" field.
func RequestedScopeHasPrefix(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldHasPrefix(FieldRequestedScope, v))
}

// RequestedScopeHasSuffix applies the HasSuffix predicate on the "requested_scope" field.
func RequestedScopeHasSuffix(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldHasSuffix(FieldRequestedScope, v))
}

// RequestedScopeEqualFold applies the EqualFold predicate on the "requested_scope" field.
func RequestedScopeEqualFold(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEqualFold(FieldRequestedScope, v))
}

// RequestedScopeContainsFold applies the ContainsFold predicate on the "requested_scope" field.
func RequestedScopeContainsFold(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldContainsFold(FieldRequestedScope, v))
}

// ApprovedScopeEQ applies the EQ predicate on the "approved_scope" field.
func ApprovedScopeEQ(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldApprovedScope, v))
}

// ApprovedScopeNEQ applies the NEQ predicate on the "approved_scope" field.
func ApprovedScopeNEQ(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldApprovedScope, v))
}

// ApprovedScopeIn applies the In predicate on the "approved_scope" field.
func ApprovedScopeIn(vs ...string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldApprovedScope, vs...))
}

// ApprovedScopeNotIn applies the NotIn predicate on the "approved_scope" field.
func ApprovedScopeNotIn(vs ...string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldApprovedScope, vs...))
}

// ApprovedScopeGT applies the GT predicate on the "approved_scope" field.
func ApprovedScopeGT(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldApprovedScope, v))
}

// ApprovedScopeGTE applies the GTE predicate on the "approved_scope" field.
func ApprovedScopeGTE(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldApprovedScope, v))
}

// ApprovedScopeLT applies the LT predicate on the "approved_scope" field.
func ApprovedScopeLT(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldApprovedScope, v))
}

// ApprovedScopeLTE applies the LTE predicate on the "approved_scope" field.
func ApprovedScopeLTE(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldApprovedScope, v))
}

// ApprovedScopeContains applies the Contains predicate on the "approved_scope" field.
func ApprovedScopeContains(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldContains(FieldApprovedScope, v))
}

// ApprovedScopeHasPrefix applies the HasPrefix predicate on the "approved_scope" field.
func ApprovedScopeHasPrefix(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldHasPrefix(FieldApprovedScope, v))
}

// ApprovedScopeHasSuffix applies the HasSuffix predicate on the "approved_scope" field.
func ApprovedScopeHasSuffix(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldHasSuffix(FieldApprovedScope, v))
}

// ApprovedScopeIsNil applies the IsNil predicate on the "approved_scope" field.
func ApprovedScopeIsNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIsNull(FieldApprovedScope))
}

// ApprovedScopeNotNil applies the NotNil predicate on the "approved_scope" field.
func ApprovedScopeNotNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotNull(FieldApprovedScope))
}

// ApprovedScopeEqualFold applies the EqualFold predicate on the "approved_scope" field.
func ApprovedScopeEqualFold(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEqualFold(FieldApprovedScope, v))
}

// ApprovedScopeContainsFold applies the ContainsFold predicate on the "approved_scope" field.
func ApprovedScopeContainsFold(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldContainsFold(FieldApprovedScope, v))
}

// RequestedIpsIsNil applies the IsNil predicate on the "requested_ips" field.
func RequestedIpsIsNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIsNull(FieldRequestedIps))
}

// RequestedIpsNotNil applies the NotNil predicate on the "requested_ips" field.
func RequestedIpsNotNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotNull(FieldRequestedIps))
}

// ApprovedIpsIsNil applies the IsNil predicate on the "approved_ips" field.
func ApprovedIpsIsNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIsNull(FieldApprovedIps))
}

// ApprovedIpsNotNil applies the NotNil predicate on the "approved_ips" field.
func ApprovedIpsNotNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotNull(FieldApprovedIps))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldContainsFold(FieldStatus, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldExpiresAt, v))
}

// ApprovedByIDEQ applies the EQ predicate on the "approved_by_id" field.
func ApprovedByIDEQ(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldApprovedByID, v))
}

// ApprovedByIDNEQ applies the NEQ predicate on the "approved_by_id" field.
func ApprovedByIDNEQ(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldApprovedByID, v))
}

// ApprovedByIDIn applies the In predicate on the "approved_by_id" field.
func ApprovedByIDIn(vs ...uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldApprovedByID, vs...))
}

// ApprovedByIDNotIn applies the NotIn predicate on the "approved_by_id" field.
func ApprovedByIDNotIn(vs ...uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldApprovedByID, vs...))
}

// ApprovedByIDGT applies the GT predicate on the "approved_by_id" field.
func ApprovedByIDGT(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldApprovedByID, v))
}

// ApprovedByIDGTE applies the GTE predicate on the "approved_by_id" field.
func ApprovedByIDGTE(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldApprovedByID, v))
}

// ApprovedByIDLT applies the LT predicate on the "approved_by_id" field.
func ApprovedByIDLT(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldApprovedByID, v))
}

// ApprovedByIDLTE applies the LTE predicate on the "approved_by_id" field.
func ApprovedByIDLTE(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldApprovedByID, v))
}

// ApprovedByIDIsNil applies the IsNil predicate on the "approved_by_id" field.
func ApprovedByIDIsNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIsNull(FieldApprovedByID))
}

// ApprovedByIDNotNil applies the NotNil predicate on the "approved_by_id" field.
func ApprovedByIDNotNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotNull(FieldApprovedByID))
}

// ApprovedAtEQ applies the EQ predicate on the "approved_at" field.
func ApprovedAtEQ(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldApprovedAt, v))
}

// ApprovedAtNEQ applies the NEQ predicate on the "approved_at" field.
func ApprovedAtNEQ(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldApprovedAt, v))
}

// ApprovedAtIn applies the In predicate on the "approved_at" field.
func ApprovedAtIn(vs ...time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldApprovedAt, vs...))
}

// ApprovedAtNotIn applies the NotIn predicate on the "approved_at" field.
func ApprovedAtNotIn(vs ...time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldApprovedAt, vs...))
}

// ApprovedAtGT applies the GT predicate on the "approved_at" field.
func ApprovedAtGT(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldApprovedAt, v))
}

// ApprovedAtGTE applies the GTE predicate on the "approved_at" field.
func ApprovedAtGTE(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldApprovedAt, v))
}

// ApprovedAtLT applies the LT predicate on the "approved_at" field.
func ApprovedAtLT(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldApprovedAt, v))
}

// ApprovedAtLTE applies the LTE predicate on the "approved_at" field.
func ApprovedAtLTE(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldApprovedAt, v))
}

// ApprovedAtIsNil applies the IsNil predicate on the "approved_at" field.
func ApprovedAtIsNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIsNull(FieldApprovedAt))
}

// ApprovedAtNotNil applies the NotNil predicate on the "approved_at" field.
func ApprovedAtNotNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotNull(FieldApprovedAt))
}

// RejectedByIDEQ applies the EQ predicate on the "rejected_by_id" field.
func RejectedByIDEQ(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldRejectedByID, v))
}

// RejectedByIDNEQ applies the NEQ predicate on the "rejected_by_id" field.
func RejectedByIDNEQ(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldRejectedByID, v))
}

// RejectedByIDIn applies the In predicate on the "rejected_by_id" field.
func RejectedByIDIn(vs ...uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldRejectedByID, vs...))
}

// RejectedByIDNotIn applies the NotIn predicate on the "rejected_by_id" field.
func RejectedByIDNotIn(vs ...uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldRejectedByID, vs...))
}

// RejectedByIDGT applies the GT predicate on the "rejected_by_id" field.
func RejectedByIDGT(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldRejectedByID, v))
}

// RejectedByIDGTE applies the GTE predicate on the "rejected_by_id" field.
func RejectedByIDGTE(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldRejectedByID, v))
}

// RejectedByIDLT applies the LT predicate on the "rejected_by_id" field.
func RejectedByIDLT(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldRejectedByID, v))
}

// RejectedByIDLTE applies the LTE predicate on the "rejected_by_id" field.
func RejectedByIDLTE(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldRejectedByID, v))
}

// RejectedByIDIsNil applies the IsNil predicate on the "rejected_by_id" field.
func RejectedByIDIsNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIsNull(FieldRejectedByID))
}

// RejectedByIDNotNil applies the NotNil predicate on the "rejected_by_id" field.
func RejectedByIDNotNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotNull(FieldRejectedByID))
}

// RejectionReasonEQ applies the EQ predicate on the "rejection_reason" field.
func RejectionReasonEQ(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldRejectionReason, v))
}

// RejectionReasonNEQ applies the NEQ predicate on the "rejection_reason" field.
func RejectionReasonNEQ(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldRejectionReason, v))
}

// RejectionReasonIn applies the In predicate on the "rejection_reason" field.
func RejectionReasonIn(vs ...string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldRejectionReason, vs...))
}

// RejectionReasonNotIn applies the NotIn predicate on the "rejection_reason" field.
func RejectionReasonNotIn(vs ...string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldRejectionReason, vs...))
}

// RejectionReasonGT applies the GT predicate on the "rejection_reason" field.
func RejectionReasonGT(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldRejectionReason, v))
}

// RejectionReasonGTE applies the GTE predicate on the "rejection_reason" field.
func RejectionReasonGTE(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldRejectionReason, v))
}

// RejectionReasonLT applies the LT predicate on the "rejection_reason" field.
func RejectionReasonLT(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldRejectionReason, v))
}

// RejectionReasonLTE applies the LTE predicate on the "rejection_reason" field.
func RejectionReasonLTE(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldRejectionReason, v))
}

// RejectionReasonContains applies the Contains predicate on the "rejection_reason" field.
func RejectionReasonContains(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldContains(FieldRejectionReason, v))
}

// RejectionReasonHasPrefix applies the HasPrefix predicate on the "rejection_reason" field.
func RejectionReasonHasPrefix(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldHasPrefix(FieldRejectionReason, v))
}

// RejectionReasonHasSuffix applies the HasSuffix predicate on the "rejection_reason" field.
func RejectionReasonHasSuffix(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldHasSuffix(FieldRejectionReason, v))
}

// RejectionReasonIsNil applies the IsNil predicate on the "rejection_reason" field.
func RejectionReasonIsNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIsNull(FieldRejectionReason))
}

// RejectionReasonNotNil applies the NotNil predicate on the "rejection_reason" field.
func RejectionReasonNotNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotNull(FieldRejectionReason))
}

// RejectionReasonEqualFold applies the EqualFold predicate on the "rejection_reason" field.
func RejectionReasonEqualFold(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEqualFold(FieldRejectionReason, v))
}

// RejectionReasonContainsFold applies the ContainsFold predicate on the "rejection_reason" field.
func RejectionReasonContainsFold(v string) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldContainsFold(FieldRejectionReason, v))
}

// RejectedAtEQ applies the EQ predicate on the "rejected_at" field.
func RejectedAtEQ(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldRejectedAt, v))
}

// RejectedAtNEQ applies the NEQ predicate on the "rejected_at" field.
func RejectedAtNEQ(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldRejectedAt, v))
}

// RejectedAtIn applies the In predicate on the "rejected_at" field.
func RejectedAtIn(vs ...time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldRejectedAt, vs...))
}

// RejectedAtNotIn applies the NotIn predicate on the "rejected_at" field.
func RejectedAtNotIn(vs ...time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldRejectedAt, vs...))
}

// RejectedAtGT applies the GT predicate on the "rejected_at" field.
func RejectedAtGT(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldRejectedAt, v))
}

// RejectedAtGTE applies the GTE predicate on the "rejected_at" field.
func RejectedAtGTE(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldRejectedAt, v))
}

// RejectedAtLT applies the LT predicate on the "rejected_at" field.
func RejectedAtLT(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldRejectedAt, v))
}

// RejectedAtLTE applies the LTE predicate on the "rejected_at" field.
func RejectedAtLTE(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldRejectedAt, v))
}

// RejectedAtIsNil applies the IsNil predicate on the "rejected_at" field.
func RejectedAtIsNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIsNull(FieldRejectedAt))
}

// RejectedAtNotNil applies the NotNil predicate on the "rejected_at" field.
func RejectedAtNotNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotNull(FieldRejectedAt))
}

// CancelledAtEQ applies the EQ predicate on the "cancelled_at" field.
func CancelledAtEQ(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldCancelledAt, v))
}

// CancelledAtNEQ applies the NEQ predicate on the "cancelled_at" field.
func CancelledAtNEQ(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldCancelledAt, v))
}

// CancelledAtIn applies the In predicate on the "cancelled_at" field.
func CancelledAtIn(vs ...time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldCancelledAt, vs...))
}

// CancelledAtNotIn applies the NotIn predicate on the "cancelled_at" field.
func CancelledAtNotIn(vs ...time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldCancelledAt, vs...))
}

// CancelledAtGT applies the GT predicate on the "cancelled_at" field.
func CancelledAtGT(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldCancelledAt, v))
}

// CancelledAtGTE applies the GTE predicate on the "cancelled_at" field.
func CancelledAtGTE(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldCancelledAt, v))
}

// CancelledAtLT applies the LT predicate on the "cancelled_at" field.
func CancelledAtLT(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldCancelledAt, v))
}

// CancelledAtLTE applies the LTE predicate on the "cancelled_at" field.
func CancelledAtLTE(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldCancelledAt, v))
}

// CancelledAtIsNil applies the IsNil predicate on the "cancelled_at" field.
func CancelledAtIsNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIsNull(FieldCancelledAt))
}

// CancelledAtNotNil applies the NotNil predicate on the "cancelled_at" field.
func CancelledAtNotNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotNull(FieldCancelledAt))
}

// SupportGrantIDEQ applies the EQ predicate on the "support_grant_id" field.
func SupportGrantIDEQ(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldSupportGrantID, v))
}

// SupportGrantIDNEQ applies the NEQ predicate on the "support_grant_id" field.
func SupportGrantIDNEQ(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldSupportGrantID, v))
}

// SupportGrantIDIn applies the In predicate on the "support_grant_id" field.
func SupportGrantIDIn(vs ...uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldSupportGrantID, vs...))
}

// SupportGrantIDNotIn applies the NotIn predicate on the "support_grant_id" field.
func SupportGrantIDNotIn(vs ...uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldSupportGrantID, vs...))
}

// SupportGrantIDGT applies the GT predicate on the "support_grant_id" field.
func SupportGrantIDGT(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldSupportGrantID, v))
}

// SupportGrantIDGTE applies the GTE predicate on the "support_grant_id" field.
func SupportGrantIDGTE(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldSupportGrantID, v))
}

// SupportGrantIDLT applies the LT predicate on the "support_grant_id" field.
func SupportGrantIDLT(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldSupportGrantID, v))
}

// SupportGrantIDLTE applies the LTE predicate on the "support_grant_id" field.
func SupportGrantIDLTE(v uuid.UUID) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldSupportGrantID, v))
}

// SupportGrantIDIsNil applies the IsNil predicate on the "support_grant_id" field.
func SupportGrantIDIsNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIsNull(FieldSupportGrantID))
}

// SupportGrantIDNotNil applies the NotNil predicate on the "support_grant_id" field.
func SupportGrantIDNotNil() predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotNull(FieldSupportGrantID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccessRequest {
	return predicate.AccessRequest(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccessRequest) predicate.AccessRequest {
	return predicate.AccessRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccessRequest) predicate.AccessRequest {
	return predicate.AccessRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccessRequest) predicate.AccessRequest {
	return predicate.AccessRequest(sql.NotPredicates(p))
}
