// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GsAccessRequestsColumns holds the columns for the "gs_access_requests" table.
	GsAccessRequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "institution_id", Type: field.TypeUUID},
		{Name: "requester_id", Type: field.TypeUUID},
		{Name: "target_service", Type: field.TypeString, Nullable: true, Size: 128},
		{Name: "reason", Type: field.TypeString},
		{Name: "requested_duration_minutes", Type: field.TypeInt},
		{Name: "approved_duration_minutes", Type: field.TypeInt, Nullable: true},
		{Name: "requested_scope", Type: field.TypeString, Default: "FULL_ACCESS"},
		{Name: "approved_scope", Type: field.TypeString, Nullable: true},
		{Name: "requested_ips", Type: field.TypeJSON, Nullable: true},
		{Name: "approved_ips", Type: field.TypeJSON, Nullable: true},
		{Name: "status", Type: field.TypeString, Size: 32, Default: "PENDING"},
		{Name: "expires_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime(6)", "postgres": "timestamptz"}},
		{Name: "approved_by_id", Type: field.TypeUUID, Nullable: true},
		{Name: "approved_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"mysql": "datetime(6)", "postgres": "timestamptz"}},
		{Name: "rejected_by_id", Type: field.TypeUUID, Nullable: true},
		{Name: "rejection_reason", Type: field.TypeString, Nullable: true},
		{Name: "rejected_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"mysql": "datetime(6)", "postgres": "timestamptz"}},
		{Name: "cancelled_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"mysql": "datetime(6)", "postgres": "timestamptz"}},
		{Name: "support_grant_id", Type: field.TypeUUID, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime(6)", "postgres": "timestamptz"}},
	}
	// GsAccessRequestsTable holds the schema information for the "gs_access_requests" table.
	GsAccessRequestsTable = &schema.Table{
		Name:       "gs_access_requests",
		Columns:    GsAccessRequestsColumns,
		PrimaryKey: []*schema.Column{GsAccessRequestsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "accessrequest_institution_id_status",
				Unique:  false,
				Columns: []*schema.Column{GsAccessRequestsColumns[1], GsAccessRequestsColumns[11]},
			},
			{
				Name:    "accessrequest_institution_id_requester_id",
				Unique:  false,
				Columns: []*schema.Column{GsAccessRequestsColumns[1], GsAccessRequestsColumns[2]},
			},
			{
				Name:    "accessrequest_expires_at",
				Unique:  false,
				Columns: []*schema.Column{GsAccessRequestsColumns[12]},
			},
		},
	}
	// GsAuditEventsColumns holds the columns for the "gs_audit_events" table.
	GsAuditEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "institution_id", Type: field.TypeUUID},
		{Name: "actor_id", Type: field.TypeUUID},
		{Name: "event_type", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "hash_chain", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime(6)", "postgres": "timestamptz"}},
	}
	// GsAuditEventsTable holds the schema information for the "gs_audit_events" table.
	GsAuditEventsTable = &schema.Table{
		Name:       "gs_audit_events",
		Columns:    GsAuditEventsColumns,
		PrimaryKey: []*schema.Column{GsAuditEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "auditevent_institution_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{GsAuditEventsColumns[1], GsAuditEventsColumns[6]},
			},
			{
				Name:    "auditevent_actor_id",
				Unique:  false,
				Columns: []*schema.Column{GsAuditEventsColumns[2]},
			},
			{
				Name:    "auditevent_event_type",
				Unique:  false,
				Columns: []*schema.Column{GsAuditEventsColumns[3]},
			},
		},
	}
	// GsSupportGrantsColumns holds the columns for the "gs_support_grants" table.
	GsSupportGrantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "institution_id", Type: field.TypeUUID},
		{Name: "granted_by_id", Type: field.TypeUUID},
		{Name: "used_by_id", Type: field.TypeUUID, Nullable: true},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "is_used", Type: field.TypeBool, Default: false},
		{Name: "used_at", Type: field.TypeTime, Nullable: true},
		{Name: "scope", Type: field.TypeString, Default: "FULL_ACCESS"},
		{Name: "whitelisted_ips", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// GsSupportGrantsTable holds the schema information for the "gs_support_grants" table.
	GsSupportGrantsTable = &schema.Table{
		Name:       "gs_support_grants",
		Columns:    GsSupportGrantsColumns,
		PrimaryKey: []*schema.Column{GsSupportGrantsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GsAccessRequestsTable,
		GsAuditEventsTable,
		GsSupportGrantsTable,
	}
)

func init() {
	GsAccessRequestsTable.Annotation = &entsql.Annotation{
		Table: "gs_access_requests",
	}
	GsAuditEventsTable.Annotation = &entsql.Annotation{
		Table: "gs_audit_events",
	}
	GsSupportGrantsTable.Annotation = &entsql.Annotation{
		Table: "gs_support_grants",
	}
}
