// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GsAuditEventsColumns holds the columns for the "gs_audit_events" table.
	GsAuditEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "institution_id", Type: field.TypeUUID},
		{Name: "actor_id", Type: field.TypeUUID},
		{Name: "event_type", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "hash_chain", Type: field.TypeString, Nullable: true},
		{Name: "signature", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime(6)", "postgres": "timestamptz"}},
	}
	// GsAuditEventsTable holds the schema information for the "gs_audit_events" table.
	GsAuditEventsTable = &schema.Table{
		Name:       "gs_audit_events",
		Columns:    GsAuditEventsColumns,
		PrimaryKey: []*schema.Column{GsAuditEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "auditevent_institution_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{GsAuditEventsColumns[1], GsAuditEventsColumns[7]},
			},
			{
				Name:    "auditevent_actor_id",
				Unique:  false,
				Columns: []*schema.Column{GsAuditEventsColumns[2]},
			},
			{
				Name:    "auditevent_event_type",
				Unique:  false,
				Columns: []*schema.Column{GsAuditEventsColumns[3]},
			},
		},
	}
	// GsSupportGrantsColumns holds the columns for the "gs_support_grants" table.
	GsSupportGrantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "institution_id", Type: field.TypeUUID},
		{Name: "granted_by_id", Type: field.TypeUUID},
		{Name: "used_by_id", Type: field.TypeUUID, Nullable: true},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "is_used", Type: field.TypeBool, Default: false},
		{Name: "used_at", Type: field.TypeTime, Nullable: true},
		{Name: "scope", Type: field.TypeString, Default: "FULL_ACCESS"},
		{Name: "whitelisted_ips", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// GsSupportGrantsTable holds the schema information for the "gs_support_grants" table.
	GsSupportGrantsTable = &schema.Table{
		Name:       "gs_support_grants",
		Columns:    GsSupportGrantsColumns,
		PrimaryKey: []*schema.Column{GsSupportGrantsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GsAuditEventsTable,
		GsSupportGrantsTable,
	}
)

func init() {
	GsAuditEventsTable.Annotation = &entsql.Annotation{
		Table: "gs_audit_events",
	}
	GsSupportGrantsTable.Annotation = &entsql.Annotation{
		Table: "gs_support_grants",
	}
}
