// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AuditEventColumns holds the columns for the "AuditEvent" table.
	AuditEventColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "institution_id", Type: field.TypeUUID},
		{Name: "actor_id", Type: field.TypeUUID},
		{Name: "event_type", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "hash_chain", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AuditEventTable holds the schema information for the "AuditEvent" table.
	AuditEventTable = &schema.Table{
		Name:       "AuditEvent",
		Columns:    AuditEventColumns,
		PrimaryKey: []*schema.Column{AuditEventColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "auditevent_institution_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{AuditEventColumns[1], AuditEventColumns[6]},
			},
			{
				Name:    "auditevent_actor_id",
				Unique:  false,
				Columns: []*schema.Column{AuditEventColumns[2]},
			},
			{
				Name:    "auditevent_event_type",
				Unique:  false,
				Columns: []*schema.Column{AuditEventColumns[3]},
			},
		},
	}
	// SupportGrantColumns holds the columns for the "SupportGrant" table.
	SupportGrantColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "institution_id", Type: field.TypeUUID},
		{Name: "granted_by_id", Type: field.TypeUUID},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "is_used", Type: field.TypeBool, Default: false},
		{Name: "used_at", Type: field.TypeTime, Nullable: true},
		{Name: "scope", Type: field.TypeString, Default: "FULL_ACCESS"},
		{Name: "whitelisted_ips", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// SupportGrantTable holds the schema information for the "SupportGrant" table.
	SupportGrantTable = &schema.Table{
		Name:       "SupportGrant",
		Columns:    SupportGrantColumns,
		PrimaryKey: []*schema.Column{SupportGrantColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AuditEventTable,
		SupportGrantTable,
	}
)

func init() {
	AuditEventTable.Annotation = &entsql.Annotation{
		Table: "AuditEvent",
	}
	SupportGrantTable.Annotation = &entsql.Annotation{
		Table: "SupportGrant",
	}
}
