// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"grantsupport/ent/accessrequest"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// AccessRequest is the model entity for the AccessRequest schema.
type AccessRequest struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// InstitutionID holds the value of the "institution_id" field.
	InstitutionID uuid.UUID `json:"institution_id,omitempty"`
	// RequesterID holds the value of the "requester_id" field.
	RequesterID uuid.UUID `json:"requester_id,omitempty"`
	// TargetService holds the value of the "target_service" field.
	TargetService *string `json:"target_service,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// RequestedDurationMinutes holds the value of the "requested_duration_minutes" field.
	RequestedDurationMinutes int `json:"requested_duration_minutes,omitempty"`
	// ApprovedDurationMinutes holds the value of the "approved_duration_minutes" field.
	ApprovedDurationMinutes *int `json:"approved_duration_minutes,omitempty"`
	// RequestedScope holds the value of the "requested_scope" field.
	RequestedScope string `json:"requested_scope,omitempty"`
	// ApprovedScope holds the value of the "approved_scope" field.
	ApprovedScope *string `json:"approved_scope,omitempty"`
	// RequestedIps holds the value of the "requested_ips" field.
	RequestedIps []string `json:"requested_ips,omitempty"`
	// ApprovedIps holds the value of the "approved_ips" field.
	ApprovedIps []string `json:"approved_ips,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// ApprovedByID holds the value of the "approved_by_id" field.
	ApprovedByID *uuid.UUID `json:"approved_by_id,omitempty"`
	// ApprovedAt holds the value of the "approved_at" field.
	ApprovedAt *time.Time `json:"approved_at,omitempty"`
	// RejectedByID holds the value of the "rejected_by_id" field.
	RejectedByID *uuid.UUID `json:"rejected_by_id,omitempty"`
	// RejectionReason holds the value of the "rejection_reason" field.
	RejectionReason *string `json:"rejection_reason,omitempty"`
	// RejectedAt holds the value of the "rejected_at" field.
	RejectedAt *time.Time `json:"rejected_at,omitempty"`
	// CancelledAt holds the value of the "cancelled_at" field.
	CancelledAt *time.Time `json:"cancelled_at,omitempty"`
	// SupportGrantID holds the value of the "support_grant_id" field.
	SupportGrantID *uuid.UUID `json:"support_grant_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccessRequest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accessrequest.FieldApprovedByID, accessrequest.FieldRejectedByID, accessrequest.FieldSupportGrantID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case accessrequest.FieldRequestedIps, accessrequest.FieldApprovedIps:
			values[i] = new([]byte)
		case accessrequest.FieldRequestedDurationMinutes, accessrequest.FieldApprovedDurationMinutes:
			values[i] = new(sql.NullInt64)
		case accessrequest.FieldTargetService, accessrequest.FieldReason, accessrequest.FieldRequestedScope, accessrequest.FieldApprovedScope, accessrequest.FieldStatus, accessrequest.FieldRejectionReason:
			values[i] = new(sql.NullString)
		case accessrequest.FieldExpiresAt, accessrequest.FieldApprovedAt, accessrequest.FieldRejectedAt, accessrequest.FieldCancelledAt, accessrequest.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case accessrequest.FieldID, accessrequest.FieldInstitutionID, accessrequest.FieldRequesterID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccessRequest fields.
func (ar *AccessRequest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accessrequest.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ar.ID = *value
			}
		case accessrequest.FieldInstitutionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field institution_id", values[i])
			} else if value != nil {
				ar.InstitutionID = *value
			}
		case accessrequest.FieldRequesterID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field requester_id", values[i])
			} else if value != nil {
				ar.RequesterID = *value
			}
		case accessrequest.FieldTargetService:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_service", values[i])
			} else if value.Valid {
				ar.TargetService = new(string)
				*ar.TargetService = value.String
			}
		case accessrequest.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				ar.Reason = value.String
			}
		case accessrequest.FieldRequestedDurationMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field requested_duration_minutes", values[i])
			} else if value.Valid {
				ar.RequestedDurationMinutes = int(value.Int64)
			}
		case accessrequest.FieldApprovedDurationMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field approved_duration_minutes", values[i])
			} else if value.Valid {
				ar.ApprovedDurationMinutes = new(int)
				*ar.ApprovedDurationMinutes = int(value.Int64)
			}
		case accessrequest.FieldRequestedScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field requested_scope", values[i])
			} else if value.Valid {
				ar.RequestedScope = value.String
			}
		case accessrequest.FieldApprovedScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field approved_scope", values[i])
			} else if value.Valid {
				ar.ApprovedScope = new(string)
				*ar.ApprovedScope = value.String
			}
		case accessrequest.FieldRequestedIps:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field requested_ips", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &ar.RequestedIps); err != nil {
					return fmt.Errorf("unmarshal field requested_ips: %w", err)
				}
			}
		case accessrequest.FieldApprovedIps:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field approved_ips", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &ar.ApprovedIps); err != nil {
					return fmt.Errorf("unmarshal field approved_ips: %w", err)
				}
			}
		case accessrequest.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				ar.Status = value.String
			}
		case accessrequest.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				ar.ExpiresAt = value.Time
			}
		case accessrequest.FieldApprovedByID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field approved_by_id", values[i])
			} else if value.Valid {
				ar.ApprovedByID = new(uuid.UUID)
				*ar.ApprovedByID = *value.S.(*uuid.UUID)
			}
		case accessrequest.FieldApprovedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field approved_at", values[i])
			} else if value.Valid {
				ar.ApprovedAt = new(time.Time)
				*ar.ApprovedAt = value.Time
			}
		case accessrequest.FieldRejectedByID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field rejected_by_id", values[i])
			} else if value.Valid {
				ar.RejectedByID = new(uuid.UUID)
				*ar.RejectedByID = *value.S.(*uuid.UUID)
			}
		case accessrequest.FieldRejectionReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rejection_reason", values[i])
			} else if value.Valid {
				ar.RejectionReason = new(string)
				*ar.RejectionReason = value.String
			}
		case accessrequest.FieldRejectedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field rejected_at", values[i])
			} else if value.Valid {
				ar.RejectedAt = new(time.Time)
				*ar.RejectedAt = value.Time
			}
		case accessrequest.FieldCancelledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field cancelled_at", values[i])
			} else if value.Valid {
				ar.CancelledAt = new(time.Time)
				*ar.CancelledAt = value.Time
			}
		case accessrequest.FieldSupportGrantID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field support_grant_id", values[i])
			} else if value.Valid {
				ar.SupportGrantID = new(uuid.UUID)
				*ar.SupportGrantID = *value.S.(*uuid.UUID)
			}
		case accessrequest.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ar.CreatedAt = value.Time
			}
		default:
			ar.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccessRequest.
// This includes values selected through modifiers, order, etc.
func (ar *AccessRequest) Value(name string) (ent.Value, error) {
	return ar.selectValues.Get(name)
}

// Update returns a builder for updating this AccessRequest.
// Note that you need to call AccessRequest.Unwrap() before calling this method if this AccessRequest
// was returned from a transaction, and the transaction was committed or rolled back.
func (ar *AccessRequest) Update() *AccessRequestUpdateOne {
	return NewAccessRequestClient(ar.config).UpdateOne(ar)
}

// Unwrap unwraps the AccessRequest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ar *AccessRequest) Unwrap() *AccessRequest {
	_tx, ok := ar.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccessRequest is not a transactional entity")
	}
	ar.config.driver = _tx.drv
	return ar
}

// String implements the fmt.Stringer.
func (ar *AccessRequest) String() string {
	var builder strings.Builder
	builder.WriteString("AccessRequest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ar.ID))
	builder.WriteString("institution_id=")
	builder.WriteString(fmt.Sprintf("%v", ar.InstitutionID))
	builder.WriteString(", ")
	builder.WriteString("requester_id=")
	builder.WriteString(fmt.Sprintf("%v", ar.RequesterID))
	builder.WriteString(", ")
	if v := ar.TargetService; v != nil {
		builder.WriteString("target_service=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(ar.Reason)
	builder.WriteString(", ")
	builder.WriteString("requested_duration_minutes=")
	builder.WriteString(fmt.Sprintf("%v", ar.RequestedDurationMinutes))
	builder.WriteString(", ")
	if v := ar.ApprovedDurationMinutes; v != nil {
		builder.WriteString("approved_duration_minutes=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("requested_scope=")
	builder.WriteString(ar.RequestedScope)
	builder.WriteString(", ")
	if v := ar.ApprovedScope; v != nil {
		builder.WriteString("approved_scope=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("requested_ips=")
	builder.WriteString(fmt.Sprintf("%v", ar.RequestedIps))
	builder.WriteString(", ")
	builder.WriteString("approved_ips=")
	builder.WriteString(fmt.Sprintf("%v", ar.ApprovedIps))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(ar.Status)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(ar.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := ar.ApprovedByID; v != nil {
		builder.WriteString("approved_by_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := ar.ApprovedAt; v != nil {
		builder.WriteString("approved_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := ar.RejectedByID; v != nil {
		builder.WriteString("rejected_by_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := ar.RejectionReason; v != nil {
		builder.WriteString("rejection_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := ar.RejectedAt; v != nil {
		builder.WriteString("rejected_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := ar.CancelledAt; v != nil {
		builder.WriteString("cancelled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := ar.SupportGrantID; v != nil {
		builder.WriteString("support_grant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ar.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AccessRequests is a parsable slice of AccessRequest.
type AccessRequests []*AccessRequest
