// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"grantsupport/ent/accessrequest"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AccessRequestCreate is the builder for creating a AccessRequest entity.
type AccessRequestCreate struct {
	config
	mutation *AccessRequestMutation
	hooks    []Hook
}

// SetInstitutionID sets the "institution_id" field.
func (arc *AccessRequestCreate) SetInstitutionID(u uuid.UUID) *AccessRequestCreate {
	arc.mutation.SetInstitutionID(u)
	return arc
}

// SetRequesterID sets the "requester_id" field.
func (arc *AccessRequestCreate) SetRequesterID(u uuid.UUID) *AccessRequestCreate {
	arc.mutation.SetRequesterID(u)
	return arc
}

// SetTargetService sets the "target_service" field.
func (arc *AccessRequestCreate) SetTargetService(s string) *AccessRequestCreate {
	arc.mutation.SetTargetService(s)
	return arc
}

// SetNillableTargetService sets the "target_service" field if the given value is not nil.
func (arc *AccessRequestCreate) SetNillableTargetService(s *string) *AccessRequestCreate {
	if s != nil {
		arc.SetTargetService(*s)
	}
	return arc
}

// SetReason sets the "reason" field.
func (arc *AccessRequestCreate) SetReason(s string) *AccessRequestCreate {
	arc.mutation.SetReason(s)
	return arc
}

// SetRequestedDurationMinutes sets the "requested_duration_minutes" field.
func (arc *AccessRequestCreate) SetRequestedDurationMinutes(i int) *AccessRequestCreate {
	arc.mutation.SetRequestedDurationMinutes(i)
	return arc
}

// SetApprovedDurationMinutes sets the "approved_duration_minutes" field.
func (arc *AccessRequestCreate) SetApprovedDurationMinutes(i int) *AccessRequestCreate {
	arc.mutation.SetApprovedDurationMinutes(i)
	return arc
}

// SetNillableApprovedDurationMinutes sets the "approved_duration_minutes" field if the given value is not nil.
func (arc *AccessRequestCreate) SetNillableApprovedDurationMinutes(i *int) *AccessRequestCreate {
	if i != nil {
		arc.SetApprovedDurationMinutes(*i)
	}
	return arc
}

// SetRequestedScope sets the "requested_scope" field.
func (arc *AccessRequestCreate) SetRequestedScope(s string) *AccessRequestCreate {
	arc.mutation.SetRequestedScope(s)
	return arc
}

// SetNillableRequestedScope sets the "requested_scope" field if the given value is not nil.
func (arc *AccessRequestCreate) SetNillableRequestedScope(s *string) *AccessRequestCreate {
	if s != nil {
		arc.SetRequestedScope(*s)
	}
	return arc
}

// SetApprovedScope sets the "approved_scope" field.
func (arc *AccessRequestCreate) SetApprovedScope(s string) *AccessRequestCreate {
	arc.mutation.SetApprovedScope(s)
	return arc
}

// SetNillableApprovedScope sets the "approved_scope" field if the given value is not nil.
func (arc *AccessRequestCreate) SetNillableApprovedScope(s *string) *AccessRequestCreate {
	if s != nil {
		arc.SetApprovedScope(*s)
	}
	return arc
}

// SetRequestedIps sets the "requested_ips" field.
func (arc *AccessRequestCreate) SetRequestedIps(s []string) *AccessRequestCreate {
	arc.mutation.SetRequestedIps(s)
	return arc
}

// SetApprovedIps sets the "approved_ips" field.
func (arc *AccessRequestCreate) SetApprovedIps(s []string) *AccessRequestCreate {
	arc.mutation.SetApprovedIps(s)
	return arc
}

// SetStatus sets the "status" field.
func (arc *AccessRequestCreate) SetStatus(s string) *AccessRequestCreate {
	arc.mutation.SetStatus(s)
	return arc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (arc *AccessRequestCreate) SetNillableStatus(s *string) *AccessRequestCreate {
	if s != nil {
		arc.SetStatus(*s)
	}
	return arc
}

// SetExpiresAt sets the "expires_at" field.
func (arc *AccessRequestCreate) SetExpiresAt(t time.Time) *AccessRequestCreate {
	arc.mutation.SetExpiresAt(t)
	return arc
}

// SetApprovedByID sets the "approved_by_id" field.
func (arc *AccessRequestCreate) SetApprovedByID(u uuid.UUID) *AccessRequestCreate {
	arc.mutation.SetApprovedByID(u)
	return arc
}

// SetNillableApprovedByID sets the "approved_by_id" field if the given value is not nil.
func (arc *AccessRequestCreate) SetNillableApprovedByID(u *uuid.UUID) *AccessRequestCreate {
	if u != nil {
		arc.SetApprovedByID(*u)
	}
	return arc
}

// SetApprovedAt sets the "approved_at" field.
func (arc *AccessRequestCreate) SetApprovedAt(t time.Time) *AccessRequestCreate {
	arc.mutation.SetApprovedAt(t)
	return arc
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (arc *AccessRequestCreate) SetNillableApprovedAt(t *time.Time) *AccessRequestCreate {
	if t != nil {
		arc.SetApprovedAt(*t)
	}
	return arc
}

// SetRejectedByID sets the "rejected_by_id" field.
func (arc *AccessRequestCreate) SetRejectedByID(u uuid.UUID) *AccessRequestCreate {
	arc.mutation.SetRejectedByID(u)
	return arc
}

// SetNillableRejectedByID sets the "rejected_by_id" field if the given value is not nil.
func (arc *AccessRequestCreate) SetNillableRejectedByID(u *uuid.UUID) *AccessRequestCreate {
	if u != nil {
		arc.SetRejectedByID(*u)
	}
	return arc
}

// SetRejectionReason sets the "rejection_reason" field.
func (arc *AccessRequestCreate) SetRejectionReason(s string) *AccessRequestCreate {
	arc.mutation.SetRejectionReason(s)
	return arc
}

// SetNillableRejectionReason sets the "rejection_reason" field if the given value is not nil.
func (arc *AccessRequestCreate) SetNillableRejectionReason(s *string) *AccessRequestCreate {
	if s != nil {
		arc.SetRejectionReason(*s)
	}
	return arc
}

// SetRejectedAt sets the "rejected_at" field.
func (arc *AccessRequestCreate) SetRejectedAt(t time.Time) *AccessRequestCreate {
	arc.mutation.SetRejectedAt(t)
	return arc
}

// SetNillableRejectedAt sets the "rejected_at" field if the given value is not nil.
func (arc *AccessRequestCreate) SetNillableRejectedAt(t *time.Time) *AccessRequestCreate {
	if t != nil {
		arc.SetRejectedAt(*t)
	}
	return arc
}

// SetCancelledAt sets the "cancelled_at" field.
func (arc *AccessRequestCreate) SetCancelledAt(t time.Time) *AccessRequestCreate {
	arc.mutation.SetCancelledAt(t)
	return arc
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (arc *AccessRequestCreate) SetNillableCancelledAt(t *time.Time) *AccessRequestCreate {
	if t != nil {
		arc.SetCancelledAt(*t)
	}
	return arc
}

// SetSupportGrantID sets the "support_grant_id" field.
func (arc *AccessRequestCreate) SetSupportGrantID(u uuid.UUID) *AccessRequestCreate {
	arc.mutation.SetSupportGrantID(u)
	return arc
}

// SetNillableSupportGrantID sets the "support_grant_id" field if the given value is not nil.
func (arc *AccessRequestCreate) SetNillableSupportGrantID(u *uuid.UUID) *AccessRequestCreate {
	if u != nil {
		arc.SetSupportGrantID(*u)
	}
	return arc
}

// SetCreatedAt sets the "created_at" field.
func (arc *AccessRequestCreate) SetCreatedAt(t time.Time) *AccessRequestCreate {
	arc.mutation.SetCreatedAt(t)
	return arc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (arc *AccessRequestCreate) SetNillableCreatedAt(t *time.Time) *AccessRequestCreate {
	if t != nil {
		arc.SetCreatedAt(*t)
	}
	return arc
}

// SetID sets the "id" field.
func (arc *AccessRequestCreate) SetID(u uuid.UUID) *AccessRequestCreate {
	arc.mutation.SetID(u)
	return arc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (arc *AccessRequestCreate) SetNillableID(u *uuid.UUID) *AccessRequestCreate {
	if u != nil {
		arc.SetID(*u)
	}
	return arc
}

// Mutation returns the AccessRequestMutation object of the builder.
func (arc *AccessRequestCreate) Mutation() *AccessRequestMutation {
	return arc.mutation
}

// Save creates the AccessRequest in the database.
func (arc *AccessRequestCreate) Save(ctx context.Context) (*AccessRequest, error) {
	arc.defaults()
	return withHooks(ctx, arc.sqlSave, arc.mutation, arc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (arc *AccessRequestCreate) SaveX(ctx context.Context) *AccessRequest {
	v, err := arc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (arc *AccessRequestCreate) Exec(ctx context.Context) error {
	_, err := arc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (arc *AccessRequestCreate) ExecX(ctx context.Context) {
	if err := arc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (arc *AccessRequestCreate) defaults() {
	if _, ok := arc.mutation.RequestedScope(); !ok {
		v := accessrequest.DefaultRequestedScope
		arc.mutation.SetRequestedScope(v)
	}
	if _, ok := arc.mutation.RequestedIps(); !ok {
		v := accessrequest.DefaultRequestedIps
		arc.mutation.SetRequestedIps(v)
	}
	if _, ok := arc.mutation.ApprovedIps(); !ok {
		v := accessrequest.DefaultApprovedIps
		arc.mutation.SetApprovedIps(v)
	}
	if _, ok := arc.mutation.Status(); !ok {
		v := accessrequest.DefaultStatus
		arc.mutation.SetStatus(v)
	}
	if _, ok := arc.mutation.CreatedAt(); !ok {
		v := accessrequest.DefaultCreatedAt()
		arc.mutation.SetCreatedAt(v)
	}
	if _, ok := arc.mutation.ID(); !ok {
		v := accessrequest.DefaultID()
		arc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (arc *AccessRequestCreate) check() error {
	if _, ok := arc.mutation.InstitutionID(); !ok {
		return &ValidationError{Name: "institution_id", err: errors.New(`ent: missing required field "AccessRequest.institution_id"`)}
	}
	if _, ok := arc.mutation.RequesterID(); !ok {
		return &ValidationError{Name: "requester_id", err: errors.New(`ent: missing required field "AccessRequest.requester_id"`)}
	}
	if v, ok := arc.mutation.TargetService(); ok {
		if err := accessrequest.TargetServiceValidator(v); err != nil {
			return &ValidationError{Name: "target_service", err: fmt.Errorf(`ent: validator failed for field "AccessRequest.target_service": %w`, err)}
		}
	}
	if _, ok := arc.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "AccessRequest.reason"`)}
	}
	if v, ok := arc.mutation.Reason(); ok {
		if err := accessrequest.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "AccessRequest.reason": %w`, err)}
		}
	}
	if _, ok := arc.mutation.RequestedDurationMinutes(); !ok {
		return &ValidationError{Name: "requested_duration_minutes", err: errors.New(`ent: missing required field "AccessRequest.requested_duration_minutes"`)}
	}
	if v, ok := arc.mutation.RequestedDurationMinutes(); ok {
		if err := accessrequest.RequestedDurationMinutesValidator(v); err != nil {
			return &ValidationError{Name: "requested_duration_minutes", err: fmt.Errorf(`ent: validator failed for field "AccessRequest.requested_duration_minutes": %w`, err)}
		}
	}
	if _, ok := arc.mutation.RequestedScope(); !ok {
		return &ValidationError{Name: "requested_scope", err: errors.New(`ent: missing required field "AccessRequest.requested_scope"`)}
	}
	if _, ok := arc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AccessRequest.status"`)}
	}
	if v, ok := arc.mutation.Status(); ok {
		if err := accessrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AccessRequest.status": %w`, err)}
		}
	}
	if _, ok := arc.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "AccessRequest.expires_at"`)}
	}
	if _, ok := arc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccessRequest.created_at"`)}
	}
	return nil
}

func (arc *AccessRequestCreate) sqlSave(ctx context.Context) (*AccessRequest, error) {
	if err := arc.check(); err != nil {
		return nil, err
	}
	_node, _spec := arc.createSpec()
	if err := sqlgraph.CreateNode(ctx, arc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	arc.mutation.id = &_node.ID
	arc.mutation.done = true
	return _node, nil
}

func (arc *AccessRequestCreate) createSpec() (*AccessRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &AccessRequest{config: arc.config}
		_spec = sqlgraph.NewCreateSpec(accessrequest.Table, sqlgraph.NewFieldSpec(accessrequest.FieldID, field.TypeUUID))
	)
	if id, ok := arc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := arc.mutation.InstitutionID(); ok {
		_spec.SetField(accessrequest.FieldInstitutionID, field.TypeUUID, value)
		_node.InstitutionID = value
	}
	if value, ok := arc.mutation.RequesterID(); ok {
		_spec.SetField(accessrequest.FieldRequesterID, field.TypeUUID, value)
		_node.RequesterID = value
	}
	if value, ok := arc.mutation.TargetService(); ok {
		_spec.SetField(accessrequest.FieldTargetService, field.TypeString, value)
		_node.TargetService = &value
	}
	if value, ok := arc.mutation.Reason(); ok {
		_spec.SetField(accessrequest.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := arc.mutation.RequestedDurationMinutes(); ok {
		_spec.SetField(accessrequest.FieldRequestedDurationMinutes, field.TypeInt, value)
		_node.RequestedDurationMinutes = value
	}
	if value, ok := arc.mutation.ApprovedDurationMinutes(); ok {
		_spec.SetField(accessrequest.FieldApprovedDurationMinutes, field.TypeInt, value)
		_node.ApprovedDurationMinutes = &value
	}
	if value, ok := arc.mutation.RequestedScope(); ok {
		_spec.SetField(accessrequest.FieldRequestedScope, field.TypeString, value)
		_node.RequestedScope = value
	}
	if value, ok := arc.mutation.ApprovedScope(); ok {
		_spec.SetField(accessrequest.FieldApprovedScope, field.TypeString, value)
		_node.ApprovedScope = &value
	}
	if value, ok := arc.mutation.RequestedIps(); ok {
		_spec.SetField(accessrequest.FieldRequestedIps, field.TypeJSON, value)
		_node.RequestedIps = value
	}
	if value, ok := arc.mutation.ApprovedIps(); ok {
		_spec.SetField(accessrequest.FieldApprovedIps, field.TypeJSON, value)
		_node.ApprovedIps = value
	}
	if value, ok := arc.mutation.Status(); ok {
		_spec.SetField(accessrequest.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := arc.mutation.ExpiresAt(); ok {
		_spec.SetField(accessrequest.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := arc.mutation.ApprovedByID(); ok {
		_spec.SetField(accessrequest.FieldApprovedByID, field.TypeUUID, value)
		_node.ApprovedByID = &value
	}
	if value, ok := arc.mutation.ApprovedAt(); ok {
		_spec.SetField(accessrequest.FieldApprovedAt, field.TypeTime, value)
		_node.ApprovedAt = &value
	}
	if value, ok := arc.mutation.RejectedByID(); ok {
		_spec.SetField(accessrequest.FieldRejectedByID, field.TypeUUID, value)
		_node.RejectedByID = &value
	}
	if value, ok := arc.mutation.RejectionReason(); ok {
		_spec.SetField(accessrequest.FieldRejectionReason, field.TypeString, value)
		_node.RejectionReason = &value
	}
	if value, ok := arc.mutation.RejectedAt(); ok {
		_spec.SetField(accessrequest.FieldRejectedAt, field.TypeTime, value)
		_node.RejectedAt = &value
	}
	if value, ok := arc.mutation.CancelledAt(); ok {
		_spec.SetField(accessrequest.FieldCancelledAt, field.TypeTime, value)
		_node.CancelledAt = &value
	}
	if value, ok := arc.mutation.SupportGrantID(); ok {
		_spec.SetField(accessrequest.FieldSupportGrantID, field.TypeUUID, value)
		_node.SupportGrantID = &value
	}
	if value, ok := arc.mutation.CreatedAt(); ok {
		_spec.SetField(accessrequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// AccessRequestCreateBulk is the builder for creating many AccessRequest entities in bulk.
type AccessRequestCreateBulk struct {
	config
	err      error
	builders []*AccessRequestCreate
}

// Save creates the AccessRequest entities in the database.
func (arcb *AccessRequestCreateBulk) Save(ctx context.Context) ([]*AccessRequest, error) {
	if arcb.err != nil {
		return nil, arcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(arcb.builders))
	nodes := make([]*AccessRequest, len(arcb.builders))
	mutators := make([]Mutator, len(arcb.builders))
	for i := range arcb.builders {
		func(i int, root context.Context) {
			builder := arcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccessRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, arcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, arcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, arcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (arcb *AccessRequestCreateBulk) SaveX(ctx context.Context) []*AccessRequest {
	v, err := arcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (arcb *AccessRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := arcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (arcb *AccessRequestCreateBulk) ExecX(ctx context.Context) {
	if err := arcb.Exec(ctx); err != nil {
		panic(err)
	}
}
