// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"grantsupport/ent/accessrequest"
	"grantsupport/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AccessRequestUpdate is the builder for updating AccessRequest entities.
type AccessRequestUpdate struct {
	config
	hooks    []Hook
	mutation *AccessRequestMutation
}

// Where appends a list predicates to the AccessRequestUpdate builder.
func (aru *AccessRequestUpdate) Where(ps ...predicate.AccessRequest) *AccessRequestUpdate {
	aru.mutation.Where(ps...)
	return aru
}

// SetInstitutionID sets the "institution_id" field.
func (aru *AccessRequestUpdate) SetInstitutionID(u uuid.UUID) *AccessRequestUpdate {
	aru.mutation.SetInstitutionID(u)
	return aru
}

// SetNillableInstitutionID sets the "institution_id" field if the given value is not nil.
func (aru *AccessRequestUpdate) SetNillableInstitutionID(u *uuid.UUID) *AccessRequestUpdate {
	if u != nil {
		aru.SetInstitutionID(*u)
	}
	return aru
}

// SetRequesterID sets the "requester_id" field.
func (aru *AccessRequestUpdate) SetRequesterID(u uuid.UUID) *AccessRequestUpdate {
	aru.mutation.SetRequesterID(u)
	return aru
}

// SetNillableRequesterID sets the "requester_id" field if the given value is not nil.
func (aru *AccessRequestUpdate) SetNillableRequesterID(u *uuid.UUID) *AccessRequestUpdate {
	if u != nil {
		aru.SetRequesterID(*u)
	}
	return aru
}

// SetTargetService sets the "target_service" field.
func (aru *AccessRequestUpdate) SetTargetService(s string) *AccessRequestUpdate {
	aru.mutation.SetTargetService(s)
	return aru
}

// SetNillableTargetService sets the "target_service" field if the given value is not nil.
func (aru *AccessRequestUpdate) SetNillableTargetService(s *string) *AccessRequestUpdate {
	if s != nil {
		aru.SetTargetService(*s)
	}
	return aru
}

// ClearTargetService clears the value of the "target_service" field.
func (aru *AccessRequestUpdate) ClearTargetService() *AccessRequestUpdate {
	aru.mutation.ClearTargetService()
	return aru
}

// SetReason sets the "reason" field.
func (aru *AccessRequestUpdate) SetReason(s string) *AccessRequestUpdate {
	aru.mutation.SetReason(s)
	return aru
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (aru *AccessRequestUpdate) SetNillableReason(s *string) *AccessRequestUpdate {
	if s != nil {
		aru.SetReason(*s)
	}
	return aru
}

// SetRequestedDurationMinutes sets the "requested_duration_minutes" field.
func (aru *AccessRequestUpdate) SetRequestedDurationMinutes(i int) *AccessRequestUpdate {
	aru.mutation.ResetRequestedDurationMinutes()
	aru.mutation.SetRequestedDurationMinutes(i)
	return aru
}

// SetNillableRequestedDurationMinutes sets the "requested_duration_minutes" field if the given value is not nil.
func (aru *AccessRequestUpdate) SetNillableRequestedDurationMinutes(i *int) *AccessRequestUpdate {
	if i != nil {
		aru.SetRequestedDurationMinutes(*i)
	}
	return aru
}

// AddRequestedDurationMinutes adds i to the "requested_duration_minutes" field.
func (aru *AccessRequestUpdate) AddRequestedDurationMinutes(i int) *AccessRequestUpdate {
	aru.mutation.AddRequestedDurationMinutes(i)
	return aru
}

// SetApprovedDurationMinutes sets the "approved_duration_minutes" field.
func (aru *AccessRequestUpdate) SetApprovedDurationMinutes(i int) *AccessRequestUpdate {
	aru.mutation.ResetApprovedDurationMinutes()
	aru.mutation.SetApprovedDurationMinutes(i)
	return aru
}

// SetNillableApprovedDurationMinutes sets the "approved_duration_minutes" field if the given value is not nil.
func (aru *AccessRequestUpdate) SetNillableApprovedDurationMinutes(i *int) *AccessRequestUpdate {
	if i != nil {
		aru.SetApprovedDurationMinutes(*i)
	}
	return aru
}

// AddApprovedDurationMinutes adds i to the "approved_duration_minutes" field.
func (aru *AccessRequestUpdate) AddApprovedDurationMinutes(i int) *AccessRequestUpdate {
	aru.mutation.AddApprovedDurationMinutes(i)
	return aru
}

// ClearApprovedDurationMinutes clears the value of the "approved_duration_minutes" field.
func (aru *AccessRequestUpdate) ClearApprovedDurationMinutes() *AccessRequestUpdate {
	aru.mutation.ClearApprovedDurationMinutes()
	return aru
}

// SetRequestedScope sets the "requested_scope" field.
func (aru *AccessRequestUpdate) SetRequestedScope(s string) *AccessRequestUpdate {
	aru.mutation.SetRequestedScope(s)
	return aru
}

// SetNillableRequestedScope sets the "requested_scope" field if the given value is not nil.
func (aru *AccessRequestUpdate) SetNillableRequestedScope(s *string) *AccessRequestUpdate {
	if s != nil {
		aru.SetRequestedScope(*s)
	}
	return aru
}

// SetApprovedScope sets the "approved_scope" field.
func (aru *AccessRequestUpdate) SetApprovedScope(s string) *AccessRequestUpdate {
	aru.mutation.SetApprovedScope(s)
	return aru
}

// SetNillableApprovedScope sets the "approved_scope" field if the given value is not nil.
func (aru *AccessRequestUpdate) SetNillableApprovedScope(s *string) *AccessRequestUpdate {
	if s != nil {
		aru.SetApprovedScope(*s)
	}
	return aru
}

// ClearApprovedScope clears the value of the "approved_scope" field.
func (aru *AccessRequestUpdate) ClearApprovedScope() *AccessRequestUpdate {
	aru.mutation.ClearApprovedScope()
	return aru
}

// SetRequestedIps sets the "requested_ips" field.
func (aru *AccessRequestUpdate) SetRequestedIps(s []string) *AccessRequestUpdate {
	aru.mutation.SetRequestedIps(s)
	return aru
}

// AppendRequestedIps appends s to the "requested_ips" field.
func (aru *AccessRequestUpdate) AppendRequestedIps(s []string) *AccessRequestUpdate {
	aru.mutation.AppendRequestedIps(s)
	return aru
}

// ClearRequestedIps clears the value of the "requested_ips" field.
func (aru *AccessRequestUpdate) ClearRequestedIps() *AccessRequestUpdate {
	aru.mutation.ClearRequestedIps()
	return aru
}

// SetApprovedIps sets the "approved_ips" field.
func (aru *AccessRequestUpdate) SetApprovedIps(s []string) *AccessRequestUpdate {
	aru.mutation.SetApprovedIps(s)
	return aru
}

// AppendApprovedIps appends s to the "approved_ips" field.
func (aru *AccessRequestUpdate) AppendApprovedIps(s []string) *AccessRequestUpdate {
	aru.mutation.AppendApprovedIps(s)
	return aru
}

// ClearApprovedIps clears the value of the "approved_ips" field.
func (aru *AccessRequestUpdate) ClearApprovedIps() *AccessRequestUpdate {
	aru.mutation.ClearApprovedIps()
	return aru
}

// SetStatus sets the "status" field.
func (aru *AccessRequestUpdate) SetStatus(s string) *AccessRequestUpdate {
	aru.mutation.SetStatus(s)
	return aru
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (aru *AccessRequestUpdate) SetNillableStatus(s *string) *AccessRequestUpdate {
	if s != nil {
		aru.SetStatus(*s)
	}
	return aru
}

// SetExpiresAt sets the "expires_at" field.
func (aru *AccessRequestUpdate) SetExpiresAt(t time.Time) *AccessRequestUpdate {
	aru.mutation.SetExpiresAt(t)
	return aru
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (aru *AccessRequestUpdate) SetNillableExpiresAt(t *time.Time) *AccessRequestUpdate {
	if t != nil {
		aru.SetExpiresAt(*t)
	}
	return aru
}

// SetApprovedByID sets the "approved_by_id" field.
func (aru *AccessRequestUpdate) SetApprovedByID(u uuid.UUID) *AccessRequestUpdate {
	aru.mutation.SetApprovedByID(u)
	return aru
}

// SetNillableApprovedByID sets the "approved_by_id" field if the given value is not nil.
func (aru *AccessRequestUpdate) SetNillableApprovedByID(u *uuid.UUID) *AccessRequestUpdate {
	if u != nil {
		aru.SetApprovedByID(*u)
	}
	return aru
}

// ClearApprovedByID clears the value of the "approved_by_id" field.
func (aru *AccessRequestUpdate) ClearApprovedByID() *AccessRequestUpdate {
	aru.mutation.ClearApprovedByID()
	return aru
}

// SetApprovedAt sets the "approved_at" field.
func (aru *AccessRequestUpdate) SetApprovedAt(t time.Time) *AccessRequestUpdate {
	aru.mutation.SetApprovedAt(t)
	return aru
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (aru *AccessRequestUpdate) SetNillableApprovedAt(t *time.Time) *AccessRequestUpdate {
	if t != nil {
		aru.SetApprovedAt(*t)
	}
	return aru
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (aru *AccessRequestUpdate) ClearApprovedAt() *AccessRequestUpdate {
	aru.mutation.ClearApprovedAt()
	return aru
}

// SetRejectedByID sets the "rejected_by_id" field.
func (aru *AccessRequestUpdate) SetRejectedByID(u uuid.UUID) *AccessRequestUpdate {
	aru.mutation.SetRejectedByID(u)
	return aru
}

// SetNillableRejectedByID sets the "rejected_by_id" field if the given value is not nil.
func (aru *AccessRequestUpdate) SetNillableRejectedByID(u *uuid.UUID) *AccessRequestUpdate {
	if u != nil {
		aru.SetRejectedByID(*u)
	}
	return aru
}

// ClearRejectedByID clears the value of the "rejected_by_id" field.
func (aru *AccessRequestUpdate) ClearRejectedByID() *AccessRequestUpdate {
	aru.mutation.ClearRejectedByID()
	return aru
}

// SetRejectionReason sets the "rejection_reason" field.
func (aru *AccessRequestUpdate) SetRejectionReason(s string) *AccessRequestUpdate {
	aru.mutation.SetRejectionReason(s)
	return aru
}

// SetNillableRejectionReason sets the "rejection_reason" field if the given value is not nil.
func (aru *AccessRequestUpdate) SetNillableRejectionReason(s *string) *AccessRequestUpdate {
	if s != nil {
		aru.SetRejectionReason(*s)
	}
	return aru
}

// ClearRejectionReason clears the value of the "rejection_reason" field.
func (aru *AccessRequestUpdate) ClearRejectionReason() *AccessRequestUpdate {
	aru.mutation.ClearRejectionReason()
	return aru
}

// SetRejectedAt sets the "rejected_at" field.
func (aru *AccessRequestUpdate) SetRejectedAt(t time.Time) *AccessRequestUpdate {
	aru.mutation.SetRejectedAt(t)
	return aru
}

// SetNillableRejectedAt sets the "rejected_at" field if the given value is not nil.
func (aru *AccessRequestUpdate) SetNillableRejectedAt(t *time.Time) *AccessRequestUpdate {
	if t != nil {
		aru.SetRejectedAt(*t)
	}
	return aru
}

// ClearRejectedAt clears the value of the "rejected_at" field.
func (aru *AccessRequestUpdate) ClearRejectedAt() *AccessRequestUpdate {
	aru.mutation.ClearRejectedAt()
	return aru
}

// SetCancelledAt sets the "cancelled_at" field.
func (aru *AccessRequestUpdate) SetCancelledAt(t time.Time) *AccessRequestUpdate {
	aru.mutation.SetCancelledAt(t)
	return aru
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (aru *AccessRequestUpdate) SetNillableCancelledAt(t *time.Time) *AccessRequestUpdate {
	if t != nil {
		aru.SetCancelledAt(*t)
	}
	return aru
}

// ClearCancelledAt clears the value of the "cancelled_at" field.
func (aru *AccessRequestUpdate) ClearCancelledAt() *AccessRequestUpdate {
	aru.mutation.ClearCancelledAt()
	return aru
}

// SetSupportGrantID sets the "support_grant_id" field.
func (aru *AccessRequestUpdate) SetSupportGrantID(u uuid.UUID) *AccessRequestUpdate {
	aru.mutation.SetSupportGrantID(u)
	return aru
}

// SetNillableSupportGrantID sets the "support_grant_id" field if the given value is not nil.
func (aru *AccessRequestUpdate) SetNillableSupportGrantID(u *uuid.UUID) *AccessRequestUpdate {
	if u != nil {
		aru.SetSupportGrantID(*u)
	}
	return aru
}

// ClearSupportGrantID clears the value of the "support_grant_id" field.
func (aru *AccessRequestUpdate) ClearSupportGrantID() *AccessRequestUpdate {
	aru.mutation.ClearSupportGrantID()
	return aru
}

// SetCreatedAt sets the "created_at" field.
func (aru *AccessRequestUpdate) SetCreatedAt(t time.Time) *AccessRequestUpdate {
	aru.mutation.SetCreatedAt(t)
	return aru
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (aru *AccessRequestUpdate) SetNillableCreatedAt(t *time.Time) *AccessRequestUpdate {
	if t != nil {
		aru.SetCreatedAt(*t)
	}
	return aru
}

// Mutation returns the AccessRequestMutation object of the builder.
func (aru *AccessRequestUpdate) Mutation() *AccessRequestMutation {
	return aru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (aru *AccessRequestUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, aru.sqlSave, aru.mutation, aru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aru *AccessRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := aru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (aru *AccessRequestUpdate) Exec(ctx context.Context) error {
	_, err := aru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aru *AccessRequestUpdate) ExecX(ctx context.Context) {
	if err := aru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aru *AccessRequestUpdate) check() error {
	if v, ok := aru.mutation.TargetService(); ok {
		if err := accessrequest.TargetServiceValidator(v); err != nil {
			return &ValidationError{Name: "target_service", err: fmt.Errorf(`ent: validator failed for field "AccessRequest.target_service": %w`, err)}
		}
	}
	if v, ok := aru.mutation.Reason(); ok {
		if err := accessrequest.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "AccessRequest.reason": %w`, err)}
		}
	}
	if v, ok := aru.mutation.RequestedDurationMinutes(); ok {
		if err := accessrequest.RequestedDurationMinutesValidator(v); err != nil {
			return &ValidationError{Name: "requested_duration_minutes", err: fmt.Errorf(`ent: validator failed for field "AccessRequest.requested_duration_minutes": %w`, err)}
		}
	}
	if v, ok := aru.mutation.Status(); ok {
		if err := accessrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AccessRequest.status": %w`, err)}
		}
	}
	return nil
}

func (aru *AccessRequestUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := aru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(accessrequest.Table, accessrequest.Columns, sqlgraph.NewFieldSpec(accessrequest.FieldID, field.TypeUUID))
	if ps := aru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aru.mutation.InstitutionID(); ok {
		_spec.SetField(accessrequest.FieldInstitutionID, field.TypeUUID, value)
	}
	if value, ok := aru.mutation.RequesterID(); ok {
		_spec.SetField(accessrequest.FieldRequesterID, field.TypeUUID, value)
	}
	if value, ok := aru.mutation.TargetService(); ok {
		_spec.SetField(accessrequest.FieldTargetService, field.TypeString, value)
	}
	if aru.mutation.TargetServiceCleared() {
		_spec.ClearField(accessrequest.FieldTargetService, field.TypeString)
	}
	if value, ok := aru.mutation.Reason(); ok {
		_spec.SetField(accessrequest.FieldReason, field.TypeString, value)
	}
	if value, ok := aru.mutation.RequestedDurationMinutes(); ok {
		_spec.SetField(accessrequest.FieldRequestedDurationMinutes, field.TypeInt, value)
	}
	if value, ok := aru.mutation.AddedRequestedDurationMinutes(); ok {
		_spec.AddField(accessrequest.FieldRequestedDurationMinutes, field.TypeInt, value)
	}
	if value, ok := aru.mutation.ApprovedDurationMinutes(); ok {
		_spec.SetField(accessrequest.FieldApprovedDurationMinutes, field.TypeInt, value)
	}
	if value, ok := aru.mutation.AddedApprovedDurationMinutes(); ok {
		_spec.AddField(accessrequest.FieldApprovedDurationMinutes, field.TypeInt, value)
	}
	if aru.mutation.ApprovedDurationMinutesCleared() {
		_spec.ClearField(accessrequest.FieldApprovedDurationMinutes, field.TypeInt)
	}
	if value, ok := aru.mutation.RequestedScope(); ok {
		_spec.SetField(accessrequest.FieldRequestedScope, field.TypeString, value)
	}
	if value, ok := aru.mutation.ApprovedScope(); ok {
		_spec.SetField(accessrequest.FieldApprovedScope, field.TypeString, value)
	}
	if aru.mutation.ApprovedScopeCleared() {
		_spec.ClearField(accessrequest.FieldApprovedScope, field.TypeString)
	}
	if value, ok := aru.mutation.RequestedIps(); ok {
		_spec.SetField(accessrequest.FieldRequestedIps, field.TypeJSON, value)
	}
	if value, ok := aru.mutation.AppendedRequestedIps(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, accessrequest.FieldRequestedIps, value)
		})
	}
	if aru.mutation.RequestedIpsCleared() {
		_spec.ClearField(accessrequest.FieldRequestedIps, field.TypeJSON)
	}
	if value, ok := aru.mutation.ApprovedIps(); ok {
		_spec.SetField(accessrequest.FieldApprovedIps, field.TypeJSON, value)
	}
	if value, ok := aru.mutation.AppendedApprovedIps(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, accessrequest.FieldApprovedIps, value)
		})
	}
	if aru.mutation.ApprovedIpsCleared() {
		_spec.ClearField(accessrequest.FieldApprovedIps, field.TypeJSON)
	}
	if value, ok := aru.mutation.Status(); ok {
		_spec.SetField(accessrequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := aru.mutation.ExpiresAt(); ok {
		_spec.SetField(accessrequest.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := aru.mutation.ApprovedByID(); ok {
		_spec.SetField(accessrequest.FieldApprovedByID, field.TypeUUID, value)
	}
	if aru.mutation.ApprovedByIDCleared() {
		_spec.ClearField(accessrequest.FieldApprovedByID, field.TypeUUID)
	}
	if value, ok := aru.mutation.ApprovedAt(); ok {
		_spec.SetField(accessrequest.FieldApprovedAt, field.TypeTime, value)
	}
	if aru.mutation.ApprovedAtCleared() {
		_spec.ClearField(accessrequest.FieldApprovedAt, field.TypeTime)
	}
	if value, ok := aru.mutation.RejectedByID(); ok {
		_spec.SetField(accessrequest.FieldRejectedByID, field.TypeUUID, value)
	}
	if aru.mutation.RejectedByIDCleared() {
		_spec.ClearField(accessrequest.FieldRejectedByID, field.TypeUUID)
	}
	if value, ok := aru.mutation.RejectionReason(); ok {
		_spec.SetField(accessrequest.FieldRejectionReason, field.TypeString, value)
	}
	if aru.mutation.RejectionReasonCleared() {
		_spec.ClearField(accessrequest.FieldRejectionReason, field.TypeString)
	}
	if value, ok := aru.mutation.RejectedAt(); ok {
		_spec.SetField(accessrequest.FieldRejectedAt, field.TypeTime, value)
	}
	if aru.mutation.RejectedAtCleared() {
		_spec.ClearField(accessrequest.FieldRejectedAt, field.TypeTime)
	}
	if value, ok := aru.mutation.CancelledAt(); ok {
		_spec.SetField(accessrequest.FieldCancelledAt, field.TypeTime, value)
	}
	if aru.mutation.CancelledAtCleared() {
		_spec.ClearField(accessrequest.FieldCancelledAt, field.TypeTime)
	}
	if value, ok := aru.mutation.SupportGrantID(); ok {
		_spec.SetField(accessrequest.FieldSupportGrantID, field.TypeUUID, value)
	}
	if aru.mutation.SupportGrantIDCleared() {
		_spec.ClearField(accessrequest.FieldSupportGrantID, field.TypeUUID)
	}
	if value, ok := aru.mutation.CreatedAt(); ok {
		_spec.SetField(accessrequest.FieldCreatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, aru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accessrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	aru.mutation.done = true
	return n, nil
}

// AccessRequestUpdateOne is the builder for updating a single AccessRequest entity.
type AccessRequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccessRequestMutation
}

// SetInstitutionID sets the "institution_id" field.
func (aruo *AccessRequestUpdateOne) SetInstitutionID(u uuid.UUID) *AccessRequestUpdateOne {
	aruo.mutation.SetInstitutionID(u)
	return aruo
}

// SetNillableInstitutionID sets the "institution_id" field if the given value is not nil.
func (aruo *AccessRequestUpdateOne) SetNillableInstitutionID(u *uuid.UUID) *AccessRequestUpdateOne {
	if u != nil {
		aruo.SetInstitutionID(*u)
	}
	return aruo
}

// SetRequesterID sets the "requester_id" field.
func (aruo *AccessRequestUpdateOne) SetRequesterID(u uuid.UUID) *AccessRequestUpdateOne {
	aruo.mutation.SetRequesterID(u)
	return aruo
}

// SetNillableRequesterID sets the "requester_id" field if the given value is not nil.
func (aruo *AccessRequestUpdateOne) SetNillableRequesterID(u *uuid.UUID) *AccessRequestUpdateOne {
	if u != nil {
		aruo.SetRequesterID(*u)
	}
	return aruo
}

// SetTargetService sets the "target_service" field.
func (aruo *AccessRequestUpdateOne) SetTargetService(s string) *AccessRequestUpdateOne {
	aruo.mutation.SetTargetService(s)
	return aruo
}

// SetNillableTargetService sets the "target_service" field if the given value is not nil.
func (aruo *AccessRequestUpdateOne) SetNillableTargetService(s *string) *AccessRequestUpdateOne {
	if s != nil {
		aruo.SetTargetService(*s)
	}
	return aruo
}

// ClearTargetService clears the value of the "target_service" field.
func (aruo *AccessRequestUpdateOne) ClearTargetService() *AccessRequestUpdateOne {
	aruo.mutation.ClearTargetService()
	return aruo
}

// SetReason sets the "reason" field.
func (aruo *AccessRequestUpdateOne) SetReason(s string) *AccessRequestUpdateOne {
	aruo.mutation.SetReason(s)
	return aruo
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (aruo *AccessRequestUpdateOne) SetNillableReason(s *string) *AccessRequestUpdateOne {
	if s != nil {
		aruo.SetReason(*s)
	}
	return aruo
}

// SetRequestedDurationMinutes sets the "requested_duration_minutes" field.
func (aruo *AccessRequestUpdateOne) SetRequestedDurationMinutes(i int) *AccessRequestUpdateOne {
	aruo.mutation.ResetRequestedDurationMinutes()
	aruo.mutation.SetRequestedDurationMinutes(i)
	return aruo
}

// SetNillableRequestedDurationMinutes sets the "requested_duration_minutes" field if the given value is not nil.
func (aruo *AccessRequestUpdateOne) SetNillableRequestedDurationMinutes(i *int) *AccessRequestUpdateOne {
	if i != nil {
		aruo.SetRequestedDurationMinutes(*i)
	}
	return aruo
}

// AddRequestedDurationMinutes adds i to the "requested_duration_minutes" field.
func (aruo *AccessRequestUpdateOne) AddRequestedDurationMinutes(i int) *AccessRequestUpdateOne {
	aruo.mutation.AddRequestedDurationMinutes(i)
	return aruo
}

// SetApprovedDurationMinutes sets the "approved_duration_minutes" field.
func (aruo *AccessRequestUpdateOne) SetApprovedDurationMinutes(i int) *AccessRequestUpdateOne {
	aruo.mutation.ResetApprovedDurationMinutes()
	aruo.mutation.SetApprovedDurationMinutes(i)
	return aruo
}

// SetNillableApprovedDurationMinutes sets the "approved_duration_minutes" field if the given value is not nil.
func (aruo *AccessRequestUpdateOne) SetNillableApprovedDurationMinutes(i *int) *AccessRequestUpdateOne {
	if i != nil {
		aruo.SetApprovedDurationMinutes(*i)
	}
	return aruo
}

// AddApprovedDurationMinutes adds i to the "approved_duration_minutes" field.
func (aruo *AccessRequestUpdateOne) AddApprovedDurationMinutes(i int) *AccessRequestUpdateOne {
	aruo.mutation.AddApprovedDurationMinutes(i)
	return aruo
}

// ClearApprovedDurationMinutes clears the value of the "approved_duration_minutes" field.
func (aruo *AccessRequestUpdateOne) ClearApprovedDurationMinutes() *AccessRequestUpdateOne {
	aruo.mutation.ClearApprovedDurationMinutes()
	return aruo
}

// SetRequestedScope sets the "requested_scope" field.
func (aruo *AccessRequestUpdateOne) SetRequestedScope(s string) *AccessRequestUpdateOne {
	aruo.mutation.SetRequestedScope(s)
	return aruo
}

// SetNillableRequestedScope sets the "requested_scope" field if the given value is not nil.
func (aruo *AccessRequestUpdateOne) SetNillableRequestedScope(s *string) *AccessRequestUpdateOne {
	if s != nil {
		aruo.SetRequestedScope(*s)
	}
	return aruo
}

// SetApprovedScope sets the "approved_scope" field.
func (aruo *AccessRequestUpdateOne) SetApprovedScope(s string) *AccessRequestUpdateOne {
	aruo.mutation.SetApprovedScope(s)
	return aruo
}

// SetNillableApprovedScope sets the "approved_scope" field if the given value is not nil.
func (aruo *AccessRequestUpdateOne) SetNillableApprovedScope(s *string) *AccessRequestUpdateOne {
	if s != nil {
		aruo.SetApprovedScope(*s)
	}
	return aruo
}

// ClearApprovedScope clears the value of the "approved_scope" field.
func (aruo *AccessRequestUpdateOne) ClearApprovedScope() *AccessRequestUpdateOne {
	aruo.mutation.ClearApprovedScope()
	return aruo
}

// SetRequestedIps sets the "requested_ips" field.
func (aruo *AccessRequestUpdateOne) SetRequestedIps(s []string) *AccessRequestUpdateOne {
	aruo.mutation.SetRequestedIps(s)
	return aruo
}

// AppendRequestedIps appends s to the "requested_ips" field.
func (aruo *AccessRequestUpdateOne) AppendRequestedIps(s []string) *AccessRequestUpdateOne {
	aruo.mutation.AppendRequestedIps(s)
	return aruo
}

// ClearRequestedIps clears the value of the "requested_ips" field.
func (aruo *AccessRequestUpdateOne) ClearRequestedIps() *AccessRequestUpdateOne {
	aruo.mutation.ClearRequestedIps()
	return aruo
}

// SetApprovedIps sets the "approved_ips" field.
func (aruo *AccessRequestUpdateOne) SetApprovedIps(s []string) *AccessRequestUpdateOne {
	aruo.mutation.SetApprovedIps(s)
	return aruo
}

// AppendApprovedIps appends s to the "approved_ips" field.
func (aruo *AccessRequestUpdateOne) AppendApprovedIps(s []string) *AccessRequestUpdateOne {
	aruo.mutation.AppendApprovedIps(s)
	return aruo
}

// ClearApprovedIps clears the value of the "approved_ips" field.
func (aruo *AccessRequestUpdateOne) ClearApprovedIps() *AccessRequestUpdateOne {
	aruo.mutation.ClearApprovedIps()
	return aruo
}

// SetStatus sets the "status" field.
func (aruo *AccessRequestUpdateOne) SetStatus(s string) *AccessRequestUpdateOne {
	aruo.mutation.SetStatus(s)
	return aruo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (aruo *AccessRequestUpdateOne) SetNillableStatus(s *string) *AccessRequestUpdateOne {
	if s != nil {
		aruo.SetStatus(*s)
	}
	return aruo
}

// SetExpiresAt sets the "expires_at" field.
func (aruo *AccessRequestUpdateOne) SetExpiresAt(t time.Time) *AccessRequestUpdateOne {
	aruo.mutation.SetExpiresAt(t)
	return aruo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (aruo *AccessRequestUpdateOne) SetNillableExpiresAt(t *time.Time) *AccessRequestUpdateOne {
	if t != nil {
		aruo.SetExpiresAt(*t)
	}
	return aruo
}

// SetApprovedByID sets the "approved_by_id" field.
func (aruo *AccessRequestUpdateOne) SetApprovedByID(u uuid.UUID) *AccessRequestUpdateOne {
	aruo.mutation.SetApprovedByID(u)
	return aruo
}

// SetNillableApprovedByID sets the "approved_by_id" field if the given value is not nil.
func (aruo *AccessRequestUpdateOne) SetNillableApprovedByID(u *uuid.UUID) *AccessRequestUpdateOne {
	if u != nil {
		aruo.SetApprovedByID(*u)
	}
	return aruo
}

// ClearApprovedByID clears the value of the "approved_by_id" field.
func (aruo *AccessRequestUpdateOne) ClearApprovedByID() *AccessRequestUpdateOne {
	aruo.mutation.ClearApprovedByID()
	return aruo
}

// SetApprovedAt sets the "approved_at" field.
func (aruo *AccessRequestUpdateOne) SetApprovedAt(t time.Time) *AccessRequestUpdateOne {
	aruo.mutation.SetApprovedAt(t)
	return aruo
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (aruo *AccessRequestUpdateOne) SetNillableApprovedAt(t *time.Time) *AccessRequestUpdateOne {
	if t != nil {
		aruo.SetApprovedAt(*t)
	}
	return aruo
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (aruo *AccessRequestUpdateOne) ClearApprovedAt() *AccessRequestUpdateOne {
	aruo.mutation.ClearApprovedAt()
	return aruo
}

// SetRejectedByID sets the "rejected_by_id" field.
func (aruo *AccessRequestUpdateOne) SetRejectedByID(u uuid.UUID) *AccessRequestUpdateOne {
	aruo.mutation.SetRejectedByID(u)
	return aruo
}

// SetNillableRejectedByID sets the "rejected_by_id" field if the given value is not nil.
func (aruo *AccessRequestUpdateOne) SetNillableRejectedByID(u *uuid.UUID) *AccessRequestUpdateOne {
	if u != nil {
		aruo.SetRejectedByID(*u)
	}
	return aruo
}

// ClearRejectedByID clears the value of the "rejected_by_id" field.
func (aruo *AccessRequestUpdateOne) ClearRejectedByID() *AccessRequestUpdateOne {
	aruo.mutation.ClearRejectedByID()
	return aruo
}

// SetRejectionReason sets the "rejection_reason" field.
func (aruo *AccessRequestUpdateOne) SetRejectionReason(s string) *AccessRequestUpdateOne {
	aruo.mutation.SetRejectionReason(s)
	return aruo
}

// SetNillableRejectionReason sets the "rejection_reason" field if the given value is not nil.
func (aruo *AccessRequestUpdateOne) SetNillableRejectionReason(s *string) *AccessRequestUpdateOne {
	if s != nil {
		aruo.SetRejectionReason(*s)
	}
	return aruo
}

// ClearRejectionReason clears the value of the "rejection_reason" field.
func (aruo *AccessRequestUpdateOne) ClearRejectionReason() *AccessRequestUpdateOne {
	aruo.mutation.ClearRejectionReason()
	return aruo
}

// SetRejectedAt sets the "rejected_at" field.
func (aruo *AccessRequestUpdateOne) SetRejectedAt(t time.Time) *AccessRequestUpdateOne {
	aruo.mutation.SetRejectedAt(t)
	return aruo
}

// SetNillableRejectedAt sets the "rejected_at" field if the given value is not nil.
func (aruo *AccessRequestUpdateOne) SetNillableRejectedAt(t *time.Time) *AccessRequestUpdateOne {
	if t != nil {
		aruo.SetRejectedAt(*t)
	}
	return aruo
}

// ClearRejectedAt clears the value of the "rejected_at" field.
func (aruo *AccessRequestUpdateOne) ClearRejectedAt() *AccessRequestUpdateOne {
	aruo.mutation.ClearRejectedAt()
	return aruo
}

// SetCancelledAt sets the "cancelled_at" field.
func (aruo *AccessRequestUpdateOne) SetCancelledAt(t time.Time) *AccessRequestUpdateOne {
	aruo.mutation.SetCancelledAt(t)
	return aruo
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (aruo *AccessRequestUpdateOne) SetNillableCancelledAt(t *time.Time) *AccessRequestUpdateOne {
	if t != nil {
		aruo.SetCancelledAt(*t)
	}
	return aruo
}

// ClearCancelledAt clears the value of the "cancelled_at" field.
func (aruo *AccessRequestUpdateOne) ClearCancelledAt() *AccessRequestUpdateOne {
	aruo.mutation.ClearCancelledAt()
	return aruo
}

// SetSupportGrantID sets the "support_grant_id" field.
func (aruo *AccessRequestUpdateOne) SetSupportGrantID(u uuid.UUID) *AccessRequestUpdateOne {
	aruo.mutation.SetSupportGrantID(u)
	return aruo
}

// SetNillableSupportGrantID sets the "support_grant_id" field if the given value is not nil.
func (aruo *AccessRequestUpdateOne) SetNillableSupportGrantID(u *uuid.UUID) *AccessRequestUpdateOne {
	if u != nil {
		aruo.SetSupportGrantID(*u)
	}
	return aruo
}

// ClearSupportGrantID clears the value of the "support_grant_id" field.
func (aruo *AccessRequestUpdateOne) ClearSupportGrantID() *AccessRequestUpdateOne {
	aruo.mutation.ClearSupportGrantID()
	return aruo
}

// SetCreatedAt sets the "created_at" field.
func (aruo *AccessRequestUpdateOne) SetCreatedAt(t time.Time) *AccessRequestUpdateOne {
	aruo.mutation.SetCreatedAt(t)
	return aruo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (aruo *AccessRequestUpdateOne) SetNillableCreatedAt(t *time.Time) *AccessRequestUpdateOne {
	if t != nil {
		aruo.SetCreatedAt(*t)
	}
	return aruo
}

// Mutation returns the AccessRequestMutation object of the builder.
func (aruo *AccessRequestUpdateOne) Mutation() *AccessRequestMutation {
	return aruo.mutation
}

// Where appends a list predicates to the AccessRequestUpdate builder.
func (aruo *AccessRequestUpdateOne) Where(ps ...predicate.AccessRequest) *AccessRequestUpdateOne {
	aruo.mutation.Where(ps...)
	return aruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (aruo *AccessRequestUpdateOne) Select(field string, fields ...string) *AccessRequestUpdateOne {
	aruo.fields = append([]string{field}, fields...)
	return aruo
}

// Save executes the query and returns the updated AccessRequest entity.
func (aruo *AccessRequestUpdateOne) Save(ctx context.Context) (*AccessRequest, error) {
	return withHooks(ctx, aruo.sqlSave, aruo.mutation, aruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aruo *AccessRequestUpdateOne) SaveX(ctx context.Context) *AccessRequest {
	node, err := aruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (aruo *AccessRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := aruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aruo *AccessRequestUpdateOne) ExecX(ctx context.Context) {
	if err := aruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aruo *AccessRequestUpdateOne) check() error {
	if v, ok := aruo.mutation.TargetService(); ok {
		if err := accessrequest.TargetServiceValidator(v); err != nil {
			return &ValidationError{Name: "target_service", err: fmt.Errorf(`ent: validator failed for field "AccessRequest.target_service": %w`, err)}
		}
	}
	if v, ok := aruo.mutation.Reason(); ok {
		if err := accessrequest.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "AccessRequest.reason": %w`, err)}
		}
	}
	if v, ok := aruo.mutation.RequestedDurationMinutes(); ok {
		if err := accessrequest.RequestedDurationMinutesValidator(v); err != nil {
			return &ValidationError{Name: "requested_duration_minutes", err: fmt.Errorf(`ent: validator failed for field "AccessRequest.requested_duration_minutes": %w`, err)}
		}
	}
	if v, ok := aruo.mutation.Status(); ok {
		if err := accessrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AccessRequest.status": %w`, err)}
		}
	}
	return nil
}

func (aruo *AccessRequestUpdateOne) sqlSave(ctx context.Context) (_node *AccessRequest, err error) {
	if err := aruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accessrequest.Table, accessrequest.Columns, sqlgraph.NewFieldSpec(accessrequest.FieldID, field.TypeUUID))
	id, ok := aruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccessRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := aruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accessrequest.FieldID)
		for _, f := range fields {
			if !accessrequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accessrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := aruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aruo.mutation.InstitutionID(); ok {
		_spec.SetField(accessrequest.FieldInstitutionID, field.TypeUUID, value)
	}
	if value, ok := aruo.mutation.RequesterID(); ok {
		_spec.SetField(accessrequest.FieldRequesterID, field.TypeUUID, value)
	}
	if value, ok := aruo.mutation.TargetService(); ok {
		_spec.SetField(accessrequest.FieldTargetService, field.TypeString, value)
	}
	if aruo.mutation.TargetServiceCleared() {
		_spec.ClearField(accessrequest.FieldTargetService, field.TypeString)
	}
	if value, ok := aruo.mutation.Reason(); ok {
		_spec.SetField(accessrequest.FieldReason, field.TypeString, value)
	}
	if value, ok := aruo.mutation.RequestedDurationMinutes(); ok {
		_spec.SetField(accessrequest.FieldRequestedDurationMinutes, field.TypeInt, value)
	}
	if value, ok := aruo.mutation.AddedRequestedDurationMinutes(); ok {
		_spec.AddField(accessrequest.FieldRequestedDurationMinutes, field.TypeInt, value)
	}
	if value, ok := aruo.mutation.ApprovedDurationMinutes(); ok {
		_spec.SetField(accessrequest.FieldApprovedDurationMinutes, field.TypeInt, value)
	}
	if value, ok := aruo.mutation.AddedApprovedDurationMinutes(); ok {
		_spec.AddField(accessrequest.FieldApprovedDurationMinutes, field.TypeInt, value)
	}
	if aruo.mutation.ApprovedDurationMinutesCleared() {
		_spec.ClearField(accessrequest.FieldApprovedDurationMinutes, field.TypeInt)
	}
	if value, ok := aruo.mutation.RequestedScope(); ok {
		_spec.SetField(accessrequest.FieldRequestedScope, field.TypeString, value)
	}
	if value, ok := aruo.mutation.ApprovedScope(); ok {
		_spec.SetField(accessrequest.FieldApprovedScope, field.TypeString, value)
	}
	if aruo.mutation.ApprovedScopeCleared() {
		_spec.ClearField(accessrequest.FieldApprovedScope, field.TypeString)
	}
	if value, ok := aruo.mutation.RequestedIps(); ok {
		_spec.SetField(accessrequest.FieldRequestedIps, field.TypeJSON, value)
	}
	if value, ok := aruo.mutation.AppendedRequestedIps(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, accessrequest.FieldRequestedIps, value)
		})
	}
	if aruo.mutation.RequestedIpsCleared() {
		_spec.ClearField(accessrequest.FieldRequestedIps, field.TypeJSON)
	}
	if value, ok := aruo.mutation.ApprovedIps(); ok {
		_spec.SetField(accessrequest.FieldApprovedIps, field.TypeJSON, value)
	}
	if value, ok := aruo.mutation.AppendedApprovedIps(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, accessrequest.FieldApprovedIps, value)
		})
	}
	if aruo.mutation.ApprovedIpsCleared() {
		_spec.ClearField(accessrequest.FieldApprovedIps, field.TypeJSON)
	}
	if value, ok := aruo.mutation.Status(); ok {
		_spec.SetField(accessrequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := aruo.mutation.ExpiresAt(); ok {
		_spec.SetField(accessrequest.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := aruo.mutation.ApprovedByID(); ok {
		_spec.SetField(accessrequest.FieldApprovedByID, field.TypeUUID, value)
	}
	if aruo.mutation.ApprovedByIDCleared() {
		_spec.ClearField(accessrequest.FieldApprovedByID, field.TypeUUID)
	}
	if value, ok := aruo.mutation.ApprovedAt(); ok {
		_spec.SetField(accessrequest.FieldApprovedAt, field.TypeTime, value)
	}
	if aruo.mutation.ApprovedAtCleared() {
		_spec.ClearField(accessrequest.FieldApprovedAt, field.TypeTime)
	}
	if value, ok := aruo.mutation.RejectedByID(); ok {
		_spec.SetField(accessrequest.FieldRejectedByID, field.TypeUUID, value)
	}
	if aruo.mutation.RejectedByIDCleared() {
		_spec.ClearField(accessrequest.FieldRejectedByID, field.TypeUUID)
	}
	if value, ok := aruo.mutation.RejectionReason(); ok {
		_spec.SetField(accessrequest.FieldRejectionReason, field.TypeString, value)
	}
	if aruo.mutation.RejectionReasonCleared() {
		_spec.ClearField(accessrequest.FieldRejectionReason, field.TypeString)
	}
	if value, ok := aruo.mutation.RejectedAt(); ok {
		_spec.SetField(accessrequest.FieldRejectedAt, field.TypeTime, value)
	}
	if aruo.mutation.RejectedAtCleared() {
		_spec.ClearField(accessrequest.FieldRejectedAt, field.TypeTime)
	}
	if value, ok := aruo.mutation.CancelledAt(); ok {
		_spec.SetField(accessrequest.FieldCancelledAt, field.TypeTime, value)
	}
	if aruo.mutation.CancelledAtCleared() {
		_spec.ClearField(accessrequest.FieldCancelledAt, field.TypeTime)
	}
	if value, ok := aruo.mutation.SupportGrantID(); ok {
		_spec.SetField(accessrequest.FieldSupportGrantID, field.TypeUUID, value)
	}
	if aruo.mutation.SupportGrantIDCleared() {
		_spec.ClearField(accessrequest.FieldSupportGrantID, field.TypeUUID)
	}
	if value, ok := aruo.mutation.CreatedAt(); ok {
		_spec.SetField(accessrequest.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &AccessRequest{config: aruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, aruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accessrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	aruo.mutation.done = true
	return _node, nil
}
