// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"grantsupport/ent/auditevent"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AuditEventCreate is the builder for creating a AuditEvent entity.
type AuditEventCreate struct {
	config
	mutation *AuditEventMutation
	hooks    []Hook
}

// SetInstitutionID sets the "institution_id" field.
func (aec *AuditEventCreate) SetInstitutionID(u uuid.UUID) *AuditEventCreate {
	aec.mutation.SetInstitutionID(u)
	return aec
}

// SetActorID sets the "actor_id" field.
func (aec *AuditEventCreate) SetActorID(u uuid.UUID) *AuditEventCreate {
	aec.mutation.SetActorID(u)
	return aec
}

// SetEventType sets the "event_type" field.
func (aec *AuditEventCreate) SetEventType(s string) *AuditEventCreate {
	aec.mutation.SetEventType(s)
	return aec
}

// SetDescription sets the "description" field.
func (aec *AuditEventCreate) SetDescription(s string) *AuditEventCreate {
	aec.mutation.SetDescription(s)
	return aec
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (aec *AuditEventCreate) SetNillableDescription(s *string) *AuditEventCreate {
	if s != nil {
		aec.SetDescription(*s)
	}
	return aec
}

// SetHashChain sets the "hash_chain" field.
func (aec *AuditEventCreate) SetHashChain(s string) *AuditEventCreate {
	aec.mutation.SetHashChain(s)
	return aec
}

// SetNillableHashChain sets the "hash_chain" field if the given value is not nil.
func (aec *AuditEventCreate) SetNillableHashChain(s *string) *AuditEventCreate {
	if s != nil {
		aec.SetHashChain(*s)
	}
	return aec
}

// SetCreatedAt sets the "created_at" field.
func (aec *AuditEventCreate) SetCreatedAt(t time.Time) *AuditEventCreate {
	aec.mutation.SetCreatedAt(t)
	return aec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (aec *AuditEventCreate) SetNillableCreatedAt(t *time.Time) *AuditEventCreate {
	if t != nil {
		aec.SetCreatedAt(*t)
	}
	return aec
}

// SetID sets the "id" field.
func (aec *AuditEventCreate) SetID(u uuid.UUID) *AuditEventCreate {
	aec.mutation.SetID(u)
	return aec
}

// SetNillableID sets the "id" field if the given value is not nil.
func (aec *AuditEventCreate) SetNillableID(u *uuid.UUID) *AuditEventCreate {
	if u != nil {
		aec.SetID(*u)
	}
	return aec
}

// Mutation returns the AuditEventMutation object of the builder.
func (aec *AuditEventCreate) Mutation() *AuditEventMutation {
	return aec.mutation
}

// Save creates the AuditEvent in the database.
func (aec *AuditEventCreate) Save(ctx context.Context) (*AuditEvent, error) {
	aec.defaults()
	return withHooks(ctx, aec.sqlSave, aec.mutation, aec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (aec *AuditEventCreate) SaveX(ctx context.Context) *AuditEvent {
	v, err := aec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aec *AuditEventCreate) Exec(ctx context.Context) error {
	_, err := aec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aec *AuditEventCreate) ExecX(ctx context.Context) {
	if err := aec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (aec *AuditEventCreate) defaults() {
	if _, ok := aec.mutation.CreatedAt(); !ok {
		v := auditevent.DefaultCreatedAt()
		aec.mutation.SetCreatedAt(v)
	}
	if _, ok := aec.mutation.ID(); !ok {
		v := auditevent.DefaultID()
		aec.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aec *AuditEventCreate) check() error {
	if _, ok := aec.mutation.InstitutionID(); !ok {
		return &ValidationError{Name: "institution_id", err: errors.New(`ent: missing required field "AuditEvent.institution_id"`)}
	}
	if _, ok := aec.mutation.ActorID(); !ok {
		return &ValidationError{Name: "actor_id", err: errors.New(`ent: missing required field "AuditEvent.actor_id"`)}
	}
	if _, ok := aec.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "AuditEvent.event_type"`)}
	}
	if _, ok := aec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuditEvent.created_at"`)}
	}
	return nil
}

func (aec *AuditEventCreate) sqlSave(ctx context.Context) (*AuditEvent, error) {
	if err := aec.check(); err != nil {
		return nil, err
	}
	_node, _spec := aec.createSpec()
	if err := sqlgraph.CreateNode(ctx, aec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	aec.mutation.id = &_node.ID
	aec.mutation.done = true
	return _node, nil
}

func (aec *AuditEventCreate) createSpec() (*AuditEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &AuditEvent{config: aec.config}
		_spec = sqlgraph.NewCreateSpec(auditevent.Table, sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeUUID))
	)
	if id, ok := aec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := aec.mutation.InstitutionID(); ok {
		_spec.SetField(auditevent.FieldInstitutionID, field.TypeUUID, value)
		_node.InstitutionID = value
	}
	if value, ok := aec.mutation.ActorID(); ok {
		_spec.SetField(auditevent.FieldActorID, field.TypeUUID, value)
		_node.ActorID = value
	}
	if value, ok := aec.mutation.EventType(); ok {
		_spec.SetField(auditevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := aec.mutation.Description(); ok {
		_spec.SetField(auditevent.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := aec.mutation.HashChain(); ok {
		_spec.SetField(auditevent.FieldHashChain, field.TypeString, value)
		_node.HashChain = value
	}
	if value, ok := aec.mutation.CreatedAt(); ok {
		_spec.SetField(auditevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// AuditEventCreateBulk is the builder for creating many AuditEvent entities in bulk.
type AuditEventCreateBulk struct {
	config
	err      error
	builders []*AuditEventCreate
}

// Save creates the AuditEvent entities in the database.
func (aecb *AuditEventCreateBulk) Save(ctx context.Context) ([]*AuditEvent, error) {
	if aecb.err != nil {
		return nil, aecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(aecb.builders))
	nodes := make([]*AuditEvent, len(aecb.builders))
	mutators := make([]Mutator, len(aecb.builders))
	for i := range aecb.builders {
		func(i int, root context.Context) {
			builder := aecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuditEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, aecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, aecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, aecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (aecb *AuditEventCreateBulk) SaveX(ctx context.Context) []*AuditEvent {
	v, err := aecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aecb *AuditEventCreateBulk) Exec(ctx context.Context) error {
	_, err := aecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aecb *AuditEventCreateBulk) ExecX(ctx context.Context) {
	if err := aecb.Exec(ctx); err != nil {
		panic(err)
	}
}
