// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"grantsupport/ent/auditevent"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// AuditEvent is the model entity for the AuditEvent schema.
type AuditEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// InstitutionID holds the value of the "institution_id" field.
	InstitutionID uuid.UUID `json:"institution_id,omitempty"`
	// ActorID holds the value of the "actor_id" field.
	ActorID uuid.UUID `json:"actor_id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// HashChain holds the value of the "hash_chain" field.
	HashChain string `json:"hash_chain,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AuditEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case auditevent.FieldEventType, auditevent.FieldDescription, auditevent.FieldHashChain:
			values[i] = new(sql.NullString)
		case auditevent.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case auditevent.FieldID, auditevent.FieldInstitutionID, auditevent.FieldActorID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AuditEvent fields.
func (ae *AuditEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case auditevent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ae.ID = *value
			}
		case auditevent.FieldInstitutionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field institution_id", values[i])
			} else if value != nil {
				ae.InstitutionID = *value
			}
		case auditevent.FieldActorID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field actor_id", values[i])
			} else if value != nil {
				ae.ActorID = *value
			}
		case auditevent.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				ae.EventType = value.String
			}
		case auditevent.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				ae.Description = value.String
			}
		case auditevent.FieldHashChain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hash_chain", values[i])
			} else if value.Valid {
				ae.HashChain = value.String
			}
		case auditevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ae.CreatedAt = value.Time
			}
		default:
			ae.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AuditEvent.
// This includes values selected through modifiers, order, etc.
func (ae *AuditEvent) Value(name string) (ent.Value, error) {
	return ae.selectValues.Get(name)
}

// Update returns a builder for updating this AuditEvent.
// Note that you need to call AuditEvent.Unwrap() before calling this method if this AuditEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (ae *AuditEvent) Update() *AuditEventUpdateOne {
	return NewAuditEventClient(ae.config).UpdateOne(ae)
}

// Unwrap unwraps the AuditEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ae *AuditEvent) Unwrap() *AuditEvent {
	_tx, ok := ae.config.driver.(*txDriver)
	if !ok {
		panic("ent: AuditEvent is not a transactional entity")
	}
	ae.config.driver = _tx.drv
	return ae
}

// String implements the fmt.Stringer.
func (ae *AuditEvent) String() string {
	var builder strings.Builder
	builder.WriteString("AuditEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ae.ID))
	builder.WriteString("institution_id=")
	builder.WriteString(fmt.Sprintf("%v", ae.InstitutionID))
	builder.WriteString(", ")
	builder.WriteString("actor_id=")
	builder.WriteString(fmt.Sprintf("%v", ae.ActorID))
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(ae.EventType)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(ae.Description)
	builder.WriteString(", ")
	builder.WriteString("hash_chain=")
	builder.WriteString(ae.HashChain)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ae.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AuditEvents is a parsable slice of AuditEvent.
type AuditEvents []*AuditEvent
