// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"grantsupport/ent/auditevent"
	"grantsupport/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AuditEventUpdate is the builder for updating AuditEvent entities.
type AuditEventUpdate struct {
	config
	hooks    []Hook
	mutation *AuditEventMutation
}

// Where appends a list predicates to the AuditEventUpdate builder.
func (aeu *AuditEventUpdate) Where(ps ...predicate.AuditEvent) *AuditEventUpdate {
	aeu.mutation.Where(ps...)
	return aeu
}

// SetInstitutionID sets the "institution_id" field.
func (aeu *AuditEventUpdate) SetInstitutionID(u uuid.UUID) *AuditEventUpdate {
	aeu.mutation.SetInstitutionID(u)
	return aeu
}

// SetNillableInstitutionID sets the "institution_id" field if the given value is not nil.
func (aeu *AuditEventUpdate) SetNillableInstitutionID(u *uuid.UUID) *AuditEventUpdate {
	if u != nil {
		aeu.SetInstitutionID(*u)
	}
	return aeu
}

// SetActorID sets the "actor_id" field.
func (aeu *AuditEventUpdate) SetActorID(u uuid.UUID) *AuditEventUpdate {
	aeu.mutation.SetActorID(u)
	return aeu
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (aeu *AuditEventUpdate) SetNillableActorID(u *uuid.UUID) *AuditEventUpdate {
	if u != nil {
		aeu.SetActorID(*u)
	}
	return aeu
}

// SetEventType sets the "event_type" field.
func (aeu *AuditEventUpdate) SetEventType(s string) *AuditEventUpdate {
	aeu.mutation.SetEventType(s)
	return aeu
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (aeu *AuditEventUpdate) SetNillableEventType(s *string) *AuditEventUpdate {
	if s != nil {
		aeu.SetEventType(*s)
	}
	return aeu
}

// SetDescription sets the "description" field.
func (aeu *AuditEventUpdate) SetDescription(s string) *AuditEventUpdate {
	aeu.mutation.SetDescription(s)
	return aeu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (aeu *AuditEventUpdate) SetNillableDescription(s *string) *AuditEventUpdate {
	if s != nil {
		aeu.SetDescription(*s)
	}
	return aeu
}

// ClearDescription clears the value of the "description" field.
func (aeu *AuditEventUpdate) ClearDescription() *AuditEventUpdate {
	aeu.mutation.ClearDescription()
	return aeu
}

// SetHashChain sets the "hash_chain" field.
func (aeu *AuditEventUpdate) SetHashChain(s string) *AuditEventUpdate {
	aeu.mutation.SetHashChain(s)
	return aeu
}

// SetNillableHashChain sets the "hash_chain" field if the given value is not nil.
func (aeu *AuditEventUpdate) SetNillableHashChain(s *string) *AuditEventUpdate {
	if s != nil {
		aeu.SetHashChain(*s)
	}
	return aeu
}

// ClearHashChain clears the value of the "hash_chain" field.
func (aeu *AuditEventUpdate) ClearHashChain() *AuditEventUpdate {
	aeu.mutation.ClearHashChain()
	return aeu
}

// SetSignature sets the "signature" field.
func (aeu *AuditEventUpdate) SetSignature(s string) *AuditEventUpdate {
	aeu.mutation.SetSignature(s)
	return aeu
}

// SetNillableSignature sets the "signature" field if the given value is not nil.
func (aeu *AuditEventUpdate) SetNillableSignature(s *string) *AuditEventUpdate {
	if s != nil {
		aeu.SetSignature(*s)
	}
	return aeu
}

// ClearSignature clears the value of the "signature" field.
func (aeu *AuditEventUpdate) ClearSignature() *AuditEventUpdate {
	aeu.mutation.ClearSignature()
	return aeu
}

// SetCreatedAt sets the "created_at" field.
func (aeu *AuditEventUpdate) SetCreatedAt(t time.Time) *AuditEventUpdate {
	aeu.mutation.SetCreatedAt(t)
	return aeu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (aeu *AuditEventUpdate) SetNillableCreatedAt(t *time.Time) *AuditEventUpdate {
	if t != nil {
		aeu.SetCreatedAt(*t)
	}
	return aeu
}

// Mutation returns the AuditEventMutation object of the builder.
func (aeu *AuditEventUpdate) Mutation() *AuditEventMutation {
	return aeu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (aeu *AuditEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, aeu.sqlSave, aeu.mutation, aeu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aeu *AuditEventUpdate) SaveX(ctx context.Context) int {
	affected, err := aeu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (aeu *AuditEventUpdate) Exec(ctx context.Context) error {
	_, err := aeu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aeu *AuditEventUpdate) ExecX(ctx context.Context) {
	if err := aeu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (aeu *AuditEventUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(auditevent.Table, auditevent.Columns, sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeUUID))
	if ps := aeu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aeu.mutation.InstitutionID(); ok {
		_spec.SetField(auditevent.FieldInstitutionID, field.TypeUUID, value)
	}
	if value, ok := aeu.mutation.ActorID(); ok {
		_spec.SetField(auditevent.FieldActorID, field.TypeUUID, value)
	}
	if value, ok := aeu.mutation.EventType(); ok {
		_spec.SetField(auditevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := aeu.mutation.Description(); ok {
		_spec.SetField(auditevent.FieldDescription, field.TypeString, value)
	}
	if aeu.mutation.DescriptionCleared() {
		_spec.ClearField(auditevent.FieldDescription, field.TypeString)
	}
	if value, ok := aeu.mutation.HashChain(); ok {
		_spec.SetField(auditevent.FieldHashChain, field.TypeString, value)
	}
	if aeu.mutation.HashChainCleared() {
		_spec.ClearField(auditevent.FieldHashChain, field.TypeString)
	}
	if value, ok := aeu.mutation.Signature(); ok {
		_spec.SetField(auditevent.FieldSignature, field.TypeString, value)
	}
	if aeu.mutation.SignatureCleared() {
		_spec.ClearField(auditevent.FieldSignature, field.TypeString)
	}
	if value, ok := aeu.mutation.CreatedAt(); ok {
		_spec.SetField(auditevent.FieldCreatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, aeu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	aeu.mutation.done = true
	return n, nil
}

// AuditEventUpdateOne is the builder for updating a single AuditEvent entity.
type AuditEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditEventMutation
}

// SetInstitutionID sets the "institution_id" field.
func (aeuo *AuditEventUpdateOne) SetInstitutionID(u uuid.UUID) *AuditEventUpdateOne {
	aeuo.mutation.SetInstitutionID(u)
	return aeuo
}

// SetNillableInstitutionID sets the "institution_id" field if the given value is not nil.
func (aeuo *AuditEventUpdateOne) SetNillableInstitutionID(u *uuid.UUID) *AuditEventUpdateOne {
	if u != nil {
		aeuo.SetInstitutionID(*u)
	}
	return aeuo
}

// SetActorID sets the "actor_id" field.
func (aeuo *AuditEventUpdateOne) SetActorID(u uuid.UUID) *AuditEventUpdateOne {
	aeuo.mutation.SetActorID(u)
	return aeuo
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (aeuo *AuditEventUpdateOne) SetNillableActorID(u *uuid.UUID) *AuditEventUpdateOne {
	if u != nil {
		aeuo.SetActorID(*u)
	}
	return aeuo
}

// SetEventType sets the "event_type" field.
func (aeuo *AuditEventUpdateOne) SetEventType(s string) *AuditEventUpdateOne {
	aeuo.mutation.SetEventType(s)
	return aeuo
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (aeuo *AuditEventUpdateOne) SetNillableEventType(s *string) *AuditEventUpdateOne {
	if s != nil {
		aeuo.SetEventType(*s)
	}
	return aeuo
}

// SetDescription sets the "description" field.
func (aeuo *AuditEventUpdateOne) SetDescription(s string) *AuditEventUpdateOne {
	aeuo.mutation.SetDescription(s)
	return aeuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (aeuo *AuditEventUpdateOne) SetNillableDescription(s *string) *AuditEventUpdateOne {
	if s != nil {
		aeuo.SetDescription(*s)
	}
	return aeuo
}

// ClearDescription clears the value of the "description" field.
func (aeuo *AuditEventUpdateOne) ClearDescription() *AuditEventUpdateOne {
	aeuo.mutation.ClearDescription()
	return aeuo
}

// SetHashChain sets the "hash_chain" field.
func (aeuo *AuditEventUpdateOne) SetHashChain(s string) *AuditEventUpdateOne {
	aeuo.mutation.SetHashChain(s)
	return aeuo
}

// SetNillableHashChain sets the "hash_chain" field if the given value is not nil.
func (aeuo *AuditEventUpdateOne) SetNillableHashChain(s *string) *AuditEventUpdateOne {
	if s != nil {
		aeuo.SetHashChain(*s)
	}
	return aeuo
}

// ClearHashChain clears the value of the "hash_chain" field.
func (aeuo *AuditEventUpdateOne) ClearHashChain() *AuditEventUpdateOne {
	aeuo.mutation.ClearHashChain()
	return aeuo
}

// SetSignature sets the "signature" field.
func (aeuo *AuditEventUpdateOne) SetSignature(s string) *AuditEventUpdateOne {
	aeuo.mutation.SetSignature(s)
	return aeuo
}

// SetNillableSignature sets the "signature" field if the given value is not nil.
func (aeuo *AuditEventUpdateOne) SetNillableSignature(s *string) *AuditEventUpdateOne {
	if s != nil {
		aeuo.SetSignature(*s)
	}
	return aeuo
}

// ClearSignature clears the value of the "signature" field.
func (aeuo *AuditEventUpdateOne) ClearSignature() *AuditEventUpdateOne {
	aeuo.mutation.ClearSignature()
	return aeuo
}

// SetCreatedAt sets the "created_at" field.
func (aeuo *AuditEventUpdateOne) SetCreatedAt(t time.Time) *AuditEventUpdateOne {
	aeuo.mutation.SetCreatedAt(t)
	return aeuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (aeuo *AuditEventUpdateOne) SetNillableCreatedAt(t *time.Time) *AuditEventUpdateOne {
	if t != nil {
		aeuo.SetCreatedAt(*t)
	}
	return aeuo
}

// Mutation returns the AuditEventMutation object of the builder.
func (aeuo *AuditEventUpdateOne) Mutation() *AuditEventMutation {
	return aeuo.mutation
}

// Where appends a list predicates to the AuditEventUpdate builder.
func (aeuo *AuditEventUpdateOne) Where(ps ...predicate.AuditEvent) *AuditEventUpdateOne {
	aeuo.mutation.Where(ps...)
	return aeuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (aeuo *AuditEventUpdateOne) Select(field string, fields ...string) *AuditEventUpdateOne {
	aeuo.fields = append([]string{field}, fields...)
	return aeuo
}

// Save executes the query and returns the updated AuditEvent entity.
func (aeuo *AuditEventUpdateOne) Save(ctx context.Context) (*AuditEvent, error) {
	return withHooks(ctx, aeuo.sqlSave, aeuo.mutation, aeuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aeuo *AuditEventUpdateOne) SaveX(ctx context.Context) *AuditEvent {
	node, err := aeuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (aeuo *AuditEventUpdateOne) Exec(ctx context.Context) error {
	_, err := aeuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aeuo *AuditEventUpdateOne) ExecX(ctx context.Context) {
	if err := aeuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (aeuo *AuditEventUpdateOne) sqlSave(ctx context.Context) (_node *AuditEvent, err error) {
	_spec := sqlgraph.NewUpdateSpec(auditevent.Table, auditevent.Columns, sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeUUID))
	id, ok := aeuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuditEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := aeuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditevent.FieldID)
		for _, f := range fields {
			if !auditevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auditevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := aeuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aeuo.mutation.InstitutionID(); ok {
		_spec.SetField(auditevent.FieldInstitutionID, field.TypeUUID, value)
	}
	if value, ok := aeuo.mutation.ActorID(); ok {
		_spec.SetField(auditevent.FieldActorID, field.TypeUUID, value)
	}
	if value, ok := aeuo.mutation.EventType(); ok {
		_spec.SetField(auditevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := aeuo.mutation.Description(); ok {
		_spec.SetField(auditevent.FieldDescription, field.TypeString, value)
	}
	if aeuo.mutation.DescriptionCleared() {
		_spec.ClearField(auditevent.FieldDescription, field.TypeString)
	}
	if value, ok := aeuo.mutation.HashChain(); ok {
		_spec.SetField(auditevent.FieldHashChain, field.TypeString, value)
	}
	if aeuo.mutation.HashChainCleared() {
		_spec.ClearField(auditevent.FieldHashChain, field.TypeString)
	}
	if value, ok := aeuo.mutation.Signature(); ok {
		_spec.SetField(auditevent.FieldSignature, field.TypeString, value)
	}
	if aeuo.mutation.SignatureCleared() {
		_spec.ClearField(auditevent.FieldSignature, field.TypeString)
	}
	if value, ok := aeuo.mutation.CreatedAt(); ok {
		_spec.SetField(auditevent.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &AuditEvent{config: aeuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, aeuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	aeuo.mutation.done = true
	return _node, nil
}
