// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"grantsupport/ent/auditevent"
	"grantsupport/ent/predicate"
	"grantsupport/ent/supportgrant"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeAuditEvent   = "AuditEvent"
	TypeSupportGrant = "SupportGrant"
)

// AuditEventMutation represents an operation that mutates the AuditEvent nodes in the graph.
type AuditEventMutation struct {
	config
	op             Op
	typ            string
	id             *uuid.UUID
	institution_id *uuid.UUID
	actor_id       *uuid.UUID
	event_type     *string
	description    *string
	hash_chain     *string
	signature      *string
	created_at     *time.Time
	clearedFields  map[string]struct{}
	done           bool
	oldValue       func(context.Context) (*AuditEvent, error)
	predicates     []predicate.AuditEvent
}

var _ ent.Mutation = (*AuditEventMutation)(nil)

// auditeventOption allows management of the mutation configuration using functional options.
type auditeventOption func(*AuditEventMutation)

// newAuditEventMutation creates new mutation for the AuditEvent entity.
func newAuditEventMutation(c config, op Op, opts ...auditeventOption) *AuditEventMutation {
	m := &AuditEventMutation{
		config:        c,
		op:            op,
		typ:           TypeAuditEvent,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withAuditEventID sets the ID field of the mutation.
func withAuditEventID(id uuid.UUID) auditeventOption {
	return func(m *AuditEventMutation) {
		var (
			err   error
			once  sync.Once
			value *AuditEvent
		)
		m.oldValue = func(ctx context.Context) (*AuditEvent, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().AuditEvent.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withAuditEvent sets the old AuditEvent of the mutation.
func withAuditEvent(node *AuditEvent) auditeventOption {
	return func(m *AuditEventMutation) {
		m.oldValue = func(context.Context) (*AuditEvent, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m AuditEventMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m AuditEventMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of AuditEvent entities.
func (m *AuditEventMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *AuditEventMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *AuditEventMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().AuditEvent.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetInstitutionID sets the "institution_id" field.
func (m *AuditEventMutation) SetInstitutionID(u uuid.UUID) {
	m.institution_id = &u
}

// InstitutionID returns the value of the "institution_id" field in the mutation.
func (m *AuditEventMutation) InstitutionID() (r uuid.UUID, exists bool) {
	v := m.institution_id
	if v == nil {
		return
	}
	return *v, true
}

// OldInstitutionID returns the old "institution_id" field's value of the AuditEvent entity.
// If the AuditEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditEventMutation) OldInstitutionID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldInstitutionID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldInstitutionID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldInstitutionID: %w", err)
	}
	return oldValue.InstitutionID, nil
}

// ResetInstitutionID resets all changes to the "institution_id" field.
func (m *AuditEventMutation) ResetInstitutionID() {
	m.institution_id = nil
}

// SetActorID sets the "actor_id" field.
func (m *AuditEventMutation) SetActorID(u uuid.UUID) {
	m.actor_id = &u
}

// ActorID returns the value of the "actor_id" field in the mutation.
func (m *AuditEventMutation) ActorID() (r uuid.UUID, exists bool) {
	v := m.actor_id
	if v == nil {
		return
	}
	return *v, true
}

// OldActorID returns the old "actor_id" field's value of the AuditEvent entity.
// If the AuditEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditEventMutation) OldActorID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldActorID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldActorID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldActorID: %w", err)
	}
	return oldValue.ActorID, nil
}

// ResetActorID resets all changes to the "actor_id" field.
func (m *AuditEventMutation) ResetActorID() {
	m.actor_id = nil
}

// SetEventType sets the "event_type" field.
func (m *AuditEventMutation) SetEventType(s string) {
	m.event_type = &s
}

// EventType returns the value of the "event_type" field in the mutation.
func (m *AuditEventMutation) EventType() (r string, exists bool) {
	v := m.event_type
	if v == nil {
		return
	}
	return *v, true
}

// OldEventType returns the old "event_type" field's value of the AuditEvent entity.
// If the AuditEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditEventMutation) OldEventType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEventType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEventType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEventType: %w", err)
	}
	return oldValue.EventType, nil
}

// ResetEventType resets all changes to the "event_type" field.
func (m *AuditEventMutation) ResetEventType() {
	m.event_type = nil
}

// SetDescription sets the "description" field.
func (m *AuditEventMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *AuditEventMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the AuditEvent entity.
// If the AuditEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditEventMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ClearDescription clears the value of the "description" field.
func (m *AuditEventMutation) ClearDescription() {
	m.description = nil
	m.clearedFields[auditevent.FieldDescription] = struct{}{}
}

// DescriptionCleared returns if the "description" field was cleared in this mutation.
func (m *AuditEventMutation) DescriptionCleared() bool {
	_, ok := m.clearedFields[auditevent.FieldDescription]
	return ok
}

// ResetDescription resets all changes to the "description" field.
func (m *AuditEventMutation) ResetDescription() {
	m.description = nil
	delete(m.clearedFields, auditevent.FieldDescription)
}

// SetHashChain sets the "hash_chain" field.
func (m *AuditEventMutation) SetHashChain(s string) {
	m.hash_chain = &s
}

// HashChain returns the value of the "hash_chain" field in the mutation.
func (m *AuditEventMutation) HashChain() (r string, exists bool) {
	v := m.hash_chain
	if v == nil {
		return
	}
	return *v, true
}

// OldHashChain returns the old "hash_chain" field's value of the AuditEvent entity.
// If the AuditEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditEventMutation) OldHashChain(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHashChain is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHashChain requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHashChain: %w", err)
	}
	return oldValue.HashChain, nil
}

// ClearHashChain clears the value of the "hash_chain" field.
func (m *AuditEventMutation) ClearHashChain() {
	m.hash_chain = nil
	m.clearedFields[auditevent.FieldHashChain] = struct{}{}
}

// HashChainCleared returns if the "hash_chain" field was cleared in this mutation.
func (m *AuditEventMutation) HashChainCleared() bool {
	_, ok := m.clearedFields[auditevent.FieldHashChain]
	return ok
}

// ResetHashChain resets all changes to the "hash_chain" field.
func (m *AuditEventMutation) ResetHashChain() {
	m.hash_chain = nil
	delete(m.clearedFields, auditevent.FieldHashChain)
}

// SetSignature sets the "signature" field.
func (m *AuditEventMutation) SetSignature(s string) {
	m.signature = &s
}

// Signature returns the value of the "signature" field in the mutation.
func (m *AuditEventMutation) Signature() (r string, exists bool) {
	v := m.signature
	if v == nil {
		return
	}
	return *v, true
}

// OldSignature returns the old "signature" field's value of the AuditEvent entity.
// If the AuditEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditEventMutation) OldSignature(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSignature is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSignature requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSignature: %w", err)
	}
	return oldValue.Signature, nil
}

// ClearSignature clears the value of the "signature" field.
func (m *AuditEventMutation) ClearSignature() {
	m.signature = nil
	m.clearedFields[auditevent.FieldSignature] = struct{}{}
}

// SignatureCleared returns if the "signature" field was cleared in this mutation.
func (m *AuditEventMutation) SignatureCleared() bool {
	_, ok := m.clearedFields[auditevent.FieldSignature]
	return ok
}

// ResetSignature resets all changes to the "signature" field.
func (m *AuditEventMutation) ResetSignature() {
	m.signature = nil
	delete(m.clearedFields, auditevent.FieldSignature)
}

// SetCreatedAt sets the "created_at" field.
func (m *AuditEventMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *AuditEventMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the AuditEvent entity.
// If the AuditEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditEventMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *AuditEventMutation) ResetCreatedAt() {
	m.created_at = nil
}

// Where appends a list predicates to the AuditEventMutation builder.
func (m *AuditEventMutation) Where(ps ...predicate.AuditEvent) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the AuditEventMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *AuditEventMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.AuditEvent, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *AuditEventMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *AuditEventMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (AuditEvent).
func (m *AuditEventMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *AuditEventMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.institution_id != nil {
		fields = append(fields, auditevent.FieldInstitutionID)
	}
	if m.actor_id != nil {
		fields = append(fields, auditevent.FieldActorID)
	}
	if m.event_type != nil {
		fields = append(fields, auditevent.FieldEventType)
	}
	if m.description != nil {
		fields = append(fields, auditevent.FieldDescription)
	}
	if m.hash_chain != nil {
		fields = append(fields, auditevent.FieldHashChain)
	}
	if m.signature != nil {
		fields = append(fields, auditevent.FieldSignature)
	}
	if m.created_at != nil {
		fields = append(fields, auditevent.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *AuditEventMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case auditevent.FieldInstitutionID:
		return m.InstitutionID()
	case auditevent.FieldActorID:
		return m.ActorID()
	case auditevent.FieldEventType:
		return m.EventType()
	case auditevent.FieldDescription:
		return m.Description()
	case auditevent.FieldHashChain:
		return m.HashChain()
	case auditevent.FieldSignature:
		return m.Signature()
	case auditevent.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *AuditEventMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case auditevent.FieldInstitutionID:
		return m.OldInstitutionID(ctx)
	case auditevent.FieldActorID:
		return m.OldActorID(ctx)
	case auditevent.FieldEventType:
		return m.OldEventType(ctx)
	case auditevent.FieldDescription:
		return m.OldDescription(ctx)
	case auditevent.FieldHashChain:
		return m.OldHashChain(ctx)
	case auditevent.FieldSignature:
		return m.OldSignature(ctx)
	case auditevent.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown AuditEvent field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AuditEventMutation) SetField(name string, value ent.Value) error {
	switch name {
	case auditevent.FieldInstitutionID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetInstitutionID(v)
		return nil
	case auditevent.FieldActorID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetActorID(v)
		return nil
	case auditevent.FieldEventType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEventType(v)
		return nil
	case auditevent.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case auditevent.FieldHashChain:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHashChain(v)
		return nil
	case auditevent.FieldSignature:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSignature(v)
		return nil
	case auditevent.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown AuditEvent field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *AuditEventMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *AuditEventMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AuditEventMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown AuditEvent numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *AuditEventMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(auditevent.FieldDescription) {
		fields = append(fields, auditevent.FieldDescription)
	}
	if m.FieldCleared(auditevent.FieldHashChain) {
		fields = append(fields, auditevent.FieldHashChain)
	}
	if m.FieldCleared(auditevent.FieldSignature) {
		fields = append(fields, auditevent.FieldSignature)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *AuditEventMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *AuditEventMutation) ClearField(name string) error {
	switch name {
	case auditevent.FieldDescription:
		m.ClearDescription()
		return nil
	case auditevent.FieldHashChain:
		m.ClearHashChain()
		return nil
	case auditevent.FieldSignature:
		m.ClearSignature()
		return nil
	}
	return fmt.Errorf("unknown AuditEvent nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *AuditEventMutation) ResetField(name string) error {
	switch name {
	case auditevent.FieldInstitutionID:
		m.ResetInstitutionID()
		return nil
	case auditevent.FieldActorID:
		m.ResetActorID()
		return nil
	case auditevent.FieldEventType:
		m.ResetEventType()
		return nil
	case auditevent.FieldDescription:
		m.ResetDescription()
		return nil
	case auditevent.FieldHashChain:
		m.ResetHashChain()
		return nil
	case auditevent.FieldSignature:
		m.ResetSignature()
		return nil
	case auditevent.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown AuditEvent field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *AuditEventMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *AuditEventMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *AuditEventMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *AuditEventMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *AuditEventMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *AuditEventMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *AuditEventMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown AuditEvent unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *AuditEventMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown AuditEvent edge %s", name)
}

// SupportGrantMutation represents an operation that mutates the SupportGrant nodes in the graph.
type SupportGrantMutation struct {
	config
	op                    Op
	typ                   string
	id                    *uuid.UUID
	institution_id        *uuid.UUID
	granted_by_id         *uuid.UUID
	used_by_id            *uuid.UUID
	token_hash            *string
	expires_at            *time.Time
	is_used               *bool
	used_at               *time.Time
	scope                 *string
	whitelisted_ips       *[]string
	appendwhitelisted_ips []string
	created_at            *time.Time
	clearedFields         map[string]struct{}
	done                  bool
	oldValue              func(context.Context) (*SupportGrant, error)
	predicates            []predicate.SupportGrant
}

var _ ent.Mutation = (*SupportGrantMutation)(nil)

// supportgrantOption allows management of the mutation configuration using functional options.
type supportgrantOption func(*SupportGrantMutation)

// newSupportGrantMutation creates new mutation for the SupportGrant entity.
func newSupportGrantMutation(c config, op Op, opts ...supportgrantOption) *SupportGrantMutation {
	m := &SupportGrantMutation{
		config:        c,
		op:            op,
		typ:           TypeSupportGrant,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSupportGrantID sets the ID field of the mutation.
func withSupportGrantID(id uuid.UUID) supportgrantOption {
	return func(m *SupportGrantMutation) {
		var (
			err   error
			once  sync.Once
			value *SupportGrant
		)
		m.oldValue = func(ctx context.Context) (*SupportGrant, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().SupportGrant.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSupportGrant sets the old SupportGrant of the mutation.
func withSupportGrant(node *SupportGrant) supportgrantOption {
	return func(m *SupportGrantMutation) {
		m.oldValue = func(context.Context) (*SupportGrant, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SupportGrantMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SupportGrantMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of SupportGrant entities.
func (m *SupportGrantMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SupportGrantMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SupportGrantMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().SupportGrant.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetInstitutionID sets the "institution_id" field.
func (m *SupportGrantMutation) SetInstitutionID(u uuid.UUID) {
	m.institution_id = &u
}

// InstitutionID returns the value of the "institution_id" field in the mutation.
func (m *SupportGrantMutation) InstitutionID() (r uuid.UUID, exists bool) {
	v := m.institution_id
	if v == nil {
		return
	}
	return *v, true
}

// OldInstitutionID returns the old "institution_id" field's value of the SupportGrant entity.
// If the SupportGrant object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SupportGrantMutation) OldInstitutionID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldInstitutionID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldInstitutionID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldInstitutionID: %w", err)
	}
	return oldValue.InstitutionID, nil
}

// ResetInstitutionID resets all changes to the "institution_id" field.
func (m *SupportGrantMutation) ResetInstitutionID() {
	m.institution_id = nil
}

// SetGrantedByID sets the "granted_by_id" field.
func (m *SupportGrantMutation) SetGrantedByID(u uuid.UUID) {
	m.granted_by_id = &u
}

// GrantedByID returns the value of the "granted_by_id" field in the mutation.
func (m *SupportGrantMutation) GrantedByID() (r uuid.UUID, exists bool) {
	v := m.granted_by_id
	if v == nil {
		return
	}
	return *v, true
}

// OldGrantedByID returns the old "granted_by_id" field's value of the SupportGrant entity.
// If the SupportGrant object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SupportGrantMutation) OldGrantedByID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGrantedByID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGrantedByID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGrantedByID: %w", err)
	}
	return oldValue.GrantedByID, nil
}

// ResetGrantedByID resets all changes to the "granted_by_id" field.
func (m *SupportGrantMutation) ResetGrantedByID() {
	m.granted_by_id = nil
}

// SetUsedByID sets the "used_by_id" field.
func (m *SupportGrantMutation) SetUsedByID(u uuid.UUID) {
	m.used_by_id = &u
}

// UsedByID returns the value of the "used_by_id" field in the mutation.
func (m *SupportGrantMutation) UsedByID() (r uuid.UUID, exists bool) {
	v := m.used_by_id
	if v == nil {
		return
	}
	return *v, true
}

// OldUsedByID returns the old "used_by_id" field's value of the SupportGrant entity.
// If the SupportGrant object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SupportGrantMutation) OldUsedByID(ctx context.Context) (v *uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUsedByID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUsedByID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUsedByID: %w", err)
	}
	return oldValue.UsedByID, nil
}

// ClearUsedByID clears the value of the "used_by_id" field.
func (m *SupportGrantMutation) ClearUsedByID() {
	m.used_by_id = nil
	m.clearedFields[supportgrant.FieldUsedByID] = struct{}{}
}

// UsedByIDCleared returns if the "used_by_id" field was cleared in this mutation.
func (m *SupportGrantMutation) UsedByIDCleared() bool {
	_, ok := m.clearedFields[supportgrant.FieldUsedByID]
	return ok
}

// ResetUsedByID resets all changes to the "used_by_id" field.
func (m *SupportGrantMutation) ResetUsedByID() {
	m.used_by_id = nil
	delete(m.clearedFields, supportgrant.FieldUsedByID)
}

// SetTokenHash sets the "token_hash" field.
func (m *SupportGrantMutation) SetTokenHash(s string) {
	m.token_hash = &s
}

// TokenHash returns the value of the "token_hash" field in the mutation.
func (m *SupportGrantMutation) TokenHash() (r string, exists bool) {
	v := m.token_hash
	if v == nil {
		return
	}
	return *v, true
}

// OldTokenHash returns the old "token_hash" field's value of the SupportGrant entity.
// If the SupportGrant object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SupportGrantMutation) OldTokenHash(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTokenHash is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTokenHash requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTokenHash: %w", err)
	}
	return oldValue.TokenHash, nil
}

// ResetTokenHash resets all changes to the "token_hash" field.
func (m *SupportGrantMutation) ResetTokenHash() {
	m.token_hash = nil
}

// SetExpiresAt sets the "expires_at" field.
func (m *SupportGrantMutation) SetExpiresAt(t time.Time) {
	m.expires_at = &t
}

// ExpiresAt returns the value of the "expires_at" field in the mutation.
func (m *SupportGrantMutation) ExpiresAt() (r time.Time, exists bool) {
	v := m.expires_at
	if v == nil {
		return
	}
	return *v, true
}

// OldExpiresAt returns the old "expires_at" field's value of the SupportGrant entity.
// If the SupportGrant object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SupportGrantMutation) OldExpiresAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExpiresAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExpiresAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExpiresAt: %w", err)
	}
	return oldValue.ExpiresAt, nil
}

// ResetExpiresAt resets all changes to the "expires_at" field.
func (m *SupportGrantMutation) ResetExpiresAt() {
	m.expires_at = nil
}

// SetIsUsed sets the "is_used" field.
func (m *SupportGrantMutation) SetIsUsed(b bool) {
	m.is_used = &b
}

// IsUsed returns the value of the "is_used" field in the mutation.
func (m *SupportGrantMutation) IsUsed() (r bool, exists bool) {
	v := m.is_used
	if v == nil {
		return
	}
	return *v, true
}

// OldIsUsed returns the old "is_used" field's value of the SupportGrant entity.
// If the SupportGrant object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SupportGrantMutation) OldIsUsed(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsUsed is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsUsed requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsUsed: %w", err)
	}
	return oldValue.IsUsed, nil
}

// ResetIsUsed resets all changes to the "is_used" field.
func (m *SupportGrantMutation) ResetIsUsed() {
	m.is_used = nil
}

// SetUsedAt sets the "used_at" field.
func (m *SupportGrantMutation) SetUsedAt(t time.Time) {
	m.used_at = &t
}

// UsedAt returns the value of the "used_at" field in the mutation.
func (m *SupportGrantMutation) UsedAt() (r time.Time, exists bool) {
	v := m.used_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUsedAt returns the old "used_at" field's value of the SupportGrant entity.
// If the SupportGrant object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SupportGrantMutation) OldUsedAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUsedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUsedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUsedAt: %w", err)
	}
	return oldValue.UsedAt, nil
}

// ClearUsedAt clears the value of the "used_at" field.
func (m *SupportGrantMutation) ClearUsedAt() {
	m.used_at = nil
	m.clearedFields[supportgrant.FieldUsedAt] = struct{}{}
}

// UsedAtCleared returns if the "used_at" field was cleared in this mutation.
func (m *SupportGrantMutation) UsedAtCleared() bool {
	_, ok := m.clearedFields[supportgrant.FieldUsedAt]
	return ok
}

// ResetUsedAt resets all changes to the "used_at" field.
func (m *SupportGrantMutation) ResetUsedAt() {
	m.used_at = nil
	delete(m.clearedFields, supportgrant.FieldUsedAt)
}

// SetScope sets the "scope" field.
func (m *SupportGrantMutation) SetScope(s string) {
	m.scope = &s
}

// Scope returns the value of the "scope" field in the mutation.
func (m *SupportGrantMutation) Scope() (r string, exists bool) {
	v := m.scope
	if v == nil {
		return
	}
	return *v, true
}

// OldScope returns the old "scope" field's value of the SupportGrant entity.
// If the SupportGrant object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SupportGrantMutation) OldScope(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldScope is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldScope requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldScope: %w", err)
	}
	return oldValue.Scope, nil
}

// ResetScope resets all changes to the "scope" field.
func (m *SupportGrantMutation) ResetScope() {
	m.scope = nil
}

// SetWhitelistedIps sets the "whitelisted_ips" field.
func (m *SupportGrantMutation) SetWhitelistedIps(s []string) {
	m.whitelisted_ips = &s
	m.appendwhitelisted_ips = nil
}

// WhitelistedIps returns the value of the "whitelisted_ips" field in the mutation.
func (m *SupportGrantMutation) WhitelistedIps() (r []string, exists bool) {
	v := m.whitelisted_ips
	if v == nil {
		return
	}
	return *v, true
}

// OldWhitelistedIps returns the old "whitelisted_ips" field's value of the SupportGrant entity.
// If the SupportGrant object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SupportGrantMutation) OldWhitelistedIps(ctx context.Context) (v []string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldWhitelistedIps is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldWhitelistedIps requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldWhitelistedIps: %w", err)
	}
	return oldValue.WhitelistedIps, nil
}

// AppendWhitelistedIps adds s to the "whitelisted_ips" field.
func (m *SupportGrantMutation) AppendWhitelistedIps(s []string) {
	m.appendwhitelisted_ips = append(m.appendwhitelisted_ips, s...)
}

// AppendedWhitelistedIps returns the list of values that were appended to the "whitelisted_ips" field in this mutation.
func (m *SupportGrantMutation) AppendedWhitelistedIps() ([]string, bool) {
	if len(m.appendwhitelisted_ips) == 0 {
		return nil, false
	}
	return m.appendwhitelisted_ips, true
}

// ClearWhitelistedIps clears the value of the "whitelisted_ips" field.
func (m *SupportGrantMutation) ClearWhitelistedIps() {
	m.whitelisted_ips = nil
	m.appendwhitelisted_ips = nil
	m.clearedFields[supportgrant.FieldWhitelistedIps] = struct{}{}
}

// WhitelistedIpsCleared returns if the "whitelisted_ips" field was cleared in this mutation.
func (m *SupportGrantMutation) WhitelistedIpsCleared() bool {
	_, ok := m.clearedFields[supportgrant.FieldWhitelistedIps]
	return ok
}

// ResetWhitelistedIps resets all changes to the "whitelisted_ips" field.
func (m *SupportGrantMutation) ResetWhitelistedIps() {
	m.whitelisted_ips = nil
	m.appendwhitelisted_ips = nil
	delete(m.clearedFields, supportgrant.FieldWhitelistedIps)
}

// SetCreatedAt sets the "created_at" field.
func (m *SupportGrantMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *SupportGrantMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the SupportGrant entity.
// If the SupportGrant object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SupportGrantMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *SupportGrantMutation) ResetCreatedAt() {
	m.created_at = nil
}

// Where appends a list predicates to the SupportGrantMutation builder.
func (m *SupportGrantMutation) Where(ps ...predicate.SupportGrant) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SupportGrantMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SupportGrantMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.SupportGrant, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SupportGrantMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SupportGrantMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (SupportGrant).
func (m *SupportGrantMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SupportGrantMutation) Fields() []string {
	fields := make([]string, 0, 10)
	if m.institution_id != nil {
		fields = append(fields, supportgrant.FieldInstitutionID)
	}
	if m.granted_by_id != nil {
		fields = append(fields, supportgrant.FieldGrantedByID)
	}
	if m.used_by_id != nil {
		fields = append(fields, supportgrant.FieldUsedByID)
	}
	if m.token_hash != nil {
		fields = append(fields, supportgrant.FieldTokenHash)
	}
	if m.expires_at != nil {
		fields = append(fields, supportgrant.FieldExpiresAt)
	}
	if m.is_used != nil {
		fields = append(fields, supportgrant.FieldIsUsed)
	}
	if m.used_at != nil {
		fields = append(fields, supportgrant.FieldUsedAt)
	}
	if m.scope != nil {
		fields = append(fields, supportgrant.FieldScope)
	}
	if m.whitelisted_ips != nil {
		fields = append(fields, supportgrant.FieldWhitelistedIps)
	}
	if m.created_at != nil {
		fields = append(fields, supportgrant.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SupportGrantMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case supportgrant.FieldInstitutionID:
		return m.InstitutionID()
	case supportgrant.FieldGrantedByID:
		return m.GrantedByID()
	case supportgrant.FieldUsedByID:
		return m.UsedByID()
	case supportgrant.FieldTokenHash:
		return m.TokenHash()
	case supportgrant.FieldExpiresAt:
		return m.ExpiresAt()
	case supportgrant.FieldIsUsed:
		return m.IsUsed()
	case supportgrant.FieldUsedAt:
		return m.UsedAt()
	case supportgrant.FieldScope:
		return m.Scope()
	case supportgrant.FieldWhitelistedIps:
		return m.WhitelistedIps()
	case supportgrant.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SupportGrantMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case supportgrant.FieldInstitutionID:
		return m.OldInstitutionID(ctx)
	case supportgrant.FieldGrantedByID:
		return m.OldGrantedByID(ctx)
	case supportgrant.FieldUsedByID:
		return m.OldUsedByID(ctx)
	case supportgrant.FieldTokenHash:
		return m.OldTokenHash(ctx)
	case supportgrant.FieldExpiresAt:
		return m.OldExpiresAt(ctx)
	case supportgrant.FieldIsUsed:
		return m.OldIsUsed(ctx)
	case supportgrant.FieldUsedAt:
		return m.OldUsedAt(ctx)
	case supportgrant.FieldScope:
		return m.OldScope(ctx)
	case supportgrant.FieldWhitelistedIps:
		return m.OldWhitelistedIps(ctx)
	case supportgrant.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown SupportGrant field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SupportGrantMutation) SetField(name string, value ent.Value) error {
	switch name {
	case supportgrant.FieldInstitutionID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetInstitutionID(v)
		return nil
	case supportgrant.FieldGrantedByID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGrantedByID(v)
		return nil
	case supportgrant.FieldUsedByID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUsedByID(v)
		return nil
	case supportgrant.FieldTokenHash:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTokenHash(v)
		return nil
	case supportgrant.FieldExpiresAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExpiresAt(v)
		return nil
	case supportgrant.FieldIsUsed:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsUsed(v)
		return nil
	case supportgrant.FieldUsedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUsedAt(v)
		return nil
	case supportgrant.FieldScope:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetScope(v)
		return nil
	case supportgrant.FieldWhitelistedIps:
		v, ok := value.([]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetWhitelistedIps(v)
		return nil
	case supportgrant.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown SupportGrant field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SupportGrantMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SupportGrantMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SupportGrantMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown SupportGrant numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SupportGrantMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(supportgrant.FieldUsedByID) {
		fields = append(fields, supportgrant.FieldUsedByID)
	}
	if m.FieldCleared(supportgrant.FieldUsedAt) {
		fields = append(fields, supportgrant.FieldUsedAt)
	}
	if m.FieldCleared(supportgrant.FieldWhitelistedIps) {
		fields = append(fields, supportgrant.FieldWhitelistedIps)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SupportGrantMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SupportGrantMutation) ClearField(name string) error {
	switch name {
	case supportgrant.FieldUsedByID:
		m.ClearUsedByID()
		return nil
	case supportgrant.FieldUsedAt:
		m.ClearUsedAt()
		return nil
	case supportgrant.FieldWhitelistedIps:
		m.ClearWhitelistedIps()
		return nil
	}
	return fmt.Errorf("unknown SupportGrant nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SupportGrantMutation) ResetField(name string) error {
	switch name {
	case supportgrant.FieldInstitutionID:
		m.ResetInstitutionID()
		return nil
	case supportgrant.FieldGrantedByID:
		m.ResetGrantedByID()
		return nil
	case supportgrant.FieldUsedByID:
		m.ResetUsedByID()
		return nil
	case supportgrant.FieldTokenHash:
		m.ResetTokenHash()
		return nil
	case supportgrant.FieldExpiresAt:
		m.ResetExpiresAt()
		return nil
	case supportgrant.FieldIsUsed:
		m.ResetIsUsed()
		return nil
	case supportgrant.FieldUsedAt:
		m.ResetUsedAt()
		return nil
	case supportgrant.FieldScope:
		m.ResetScope()
		return nil
	case supportgrant.FieldWhitelistedIps:
		m.ResetWhitelistedIps()
		return nil
	case supportgrant.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown SupportGrant field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SupportGrantMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SupportGrantMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SupportGrantMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SupportGrantMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SupportGrantMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SupportGrantMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SupportGrantMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown SupportGrant unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SupportGrantMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown SupportGrant edge %s", name)
}
