// Code generated by ent, DO NOT EDIT.

package ent

import (
	"grantsupport/ent/auditevent"
	"grantsupport/ent/schema"
	"grantsupport/ent/supportgrant"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	auditeventFields := schema.AuditEvent{}.Fields()
	_ = auditeventFields
	// auditeventDescCreatedAt is the schema descriptor for created_at field.
	auditeventDescCreatedAt := auditeventFields[7].Descriptor()
	// auditevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditevent.DefaultCreatedAt = auditeventDescCreatedAt.Default.(func() time.Time)
	// auditeventDescID is the schema descriptor for id field.
	auditeventDescID := auditeventFields[0].Descriptor()
	// auditevent.DefaultID holds the default value on creation for the id field.
	auditevent.DefaultID = auditeventDescID.Default.(func() uuid.UUID)
	supportgrantFields := schema.SupportGrant{}.Fields()
	_ = supportgrantFields
	// supportgrantDescIsUsed is the schema descriptor for is_used field.
	supportgrantDescIsUsed := supportgrantFields[6].Descriptor()
	// supportgrant.DefaultIsUsed holds the default value on creation for the is_used field.
	supportgrant.DefaultIsUsed = supportgrantDescIsUsed.Default.(bool)
	// supportgrantDescScope is the schema descriptor for scope field.
	supportgrantDescScope := supportgrantFields[8].Descriptor()
	// supportgrant.DefaultScope holds the default value on creation for the scope field.
	supportgrant.DefaultScope = supportgrantDescScope.Default.(string)
	// supportgrantDescCreatedAt is the schema descriptor for created_at field.
	supportgrantDescCreatedAt := supportgrantFields[10].Descriptor()
	// supportgrant.DefaultCreatedAt holds the default value on creation for the created_at field.
	supportgrant.DefaultCreatedAt = supportgrantDescCreatedAt.Default.(func() time.Time)
	// supportgrantDescID is the schema descriptor for id field.
	supportgrantDescID := supportgrantFields[0].Descriptor()
	// supportgrant.DefaultID holds the default value on creation for the id field.
	supportgrant.DefaultID = supportgrantDescID.Default.(func() uuid.UUID)
}
