// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"grantsupport/ent/predicate"
	"grantsupport/ent/supportgrant"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SupportGrantDelete is the builder for deleting a SupportGrant entity.
type SupportGrantDelete struct {
	config
	hooks    []Hook
	mutation *SupportGrantMutation
}

// Where appends a list predicates to the SupportGrantDelete builder.
func (sgd *SupportGrantDelete) Where(ps ...predicate.SupportGrant) *SupportGrantDelete {
	sgd.mutation.Where(ps...)
	return sgd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sgd *SupportGrantDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sgd.sqlExec, sgd.mutation, sgd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sgd *SupportGrantDelete) ExecX(ctx context.Context) int {
	n, err := sgd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sgd *SupportGrantDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(supportgrant.Table, sqlgraph.NewFieldSpec(supportgrant.FieldID, field.TypeUUID))
	if ps := sgd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sgd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sgd.mutation.done = true
	return affected, err
}

// SupportGrantDeleteOne is the builder for deleting a single SupportGrant entity.
type SupportGrantDeleteOne struct {
	sgd *SupportGrantDelete
}

// Where appends a list predicates to the SupportGrantDelete builder.
func (sgdo *SupportGrantDeleteOne) Where(ps ...predicate.SupportGrant) *SupportGrantDeleteOne {
	sgdo.sgd.mutation.Where(ps...)
	return sgdo
}

// Exec executes the deletion query.
func (sgdo *SupportGrantDeleteOne) Exec(ctx context.Context) error {
	n, err := sgdo.sgd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{supportgrant.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sgdo *SupportGrantDeleteOne) ExecX(ctx context.Context) {
	if err := sgdo.Exec(ctx); err != nil {
		panic(err)
	}
}
