// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"grantsupport/ent/predicate"
	"grantsupport/ent/supportgrant"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SupportGrantQuery is the builder for querying SupportGrant entities.
type SupportGrantQuery struct {
	config
	ctx        *QueryContext
	order      []supportgrant.OrderOption
	inters     []Interceptor
	predicates []predicate.SupportGrant
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SupportGrantQuery builder.
func (sgq *SupportGrantQuery) Where(ps ...predicate.SupportGrant) *SupportGrantQuery {
	sgq.predicates = append(sgq.predicates, ps...)
	return sgq
}

// Limit the number of records to be returned by this query.
func (sgq *SupportGrantQuery) Limit(limit int) *SupportGrantQuery {
	sgq.ctx.Limit = &limit
	return sgq
}

// Offset to start from.
func (sgq *SupportGrantQuery) Offset(offset int) *SupportGrantQuery {
	sgq.ctx.Offset = &offset
	return sgq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sgq *SupportGrantQuery) Unique(unique bool) *SupportGrantQuery {
	sgq.ctx.Unique = &unique
	return sgq
}

// Order specifies how the records should be ordered.
func (sgq *SupportGrantQuery) Order(o ...supportgrant.OrderOption) *SupportGrantQuery {
	sgq.order = append(sgq.order, o...)
	return sgq
}

// First returns the first SupportGrant entity from the query.
// Returns a *NotFoundError when no SupportGrant was found.
func (sgq *SupportGrantQuery) First(ctx context.Context) (*SupportGrant, error) {
	nodes, err := sgq.Limit(1).All(setContextOp(ctx, sgq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{supportgrant.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sgq *SupportGrantQuery) FirstX(ctx context.Context) *SupportGrant {
	node, err := sgq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SupportGrant ID from the query.
// Returns a *NotFoundError when no SupportGrant ID was found.
func (sgq *SupportGrantQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = sgq.Limit(1).IDs(setContextOp(ctx, sgq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{supportgrant.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sgq *SupportGrantQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := sgq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SupportGrant entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SupportGrant entity is found.
// Returns a *NotFoundError when no SupportGrant entities are found.
func (sgq *SupportGrantQuery) Only(ctx context.Context) (*SupportGrant, error) {
	nodes, err := sgq.Limit(2).All(setContextOp(ctx, sgq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{supportgrant.Label}
	default:
		return nil, &NotSingularError{supportgrant.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sgq *SupportGrantQuery) OnlyX(ctx context.Context) *SupportGrant {
	node, err := sgq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SupportGrant ID in the query.
// Returns a *NotSingularError when more than one SupportGrant ID is found.
// Returns a *NotFoundError when no entities are found.
func (sgq *SupportGrantQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = sgq.Limit(2).IDs(setContextOp(ctx, sgq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{supportgrant.Label}
	default:
		err = &NotSingularError{supportgrant.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sgq *SupportGrantQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := sgq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SupportGrants.
func (sgq *SupportGrantQuery) All(ctx context.Context) ([]*SupportGrant, error) {
	ctx = setContextOp(ctx, sgq.ctx, ent.OpQueryAll)
	if err := sgq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SupportGrant, *SupportGrantQuery]()
	return withInterceptors[[]*SupportGrant](ctx, sgq, qr, sgq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sgq *SupportGrantQuery) AllX(ctx context.Context) []*SupportGrant {
	nodes, err := sgq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SupportGrant IDs.
func (sgq *SupportGrantQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if sgq.ctx.Unique == nil && sgq.path != nil {
		sgq.Unique(true)
	}
	ctx = setContextOp(ctx, sgq.ctx, ent.OpQueryIDs)
	if err = sgq.Select(supportgrant.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sgq *SupportGrantQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := sgq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sgq *SupportGrantQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sgq.ctx, ent.OpQueryCount)
	if err := sgq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sgq, querierCount[*SupportGrantQuery](), sgq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sgq *SupportGrantQuery) CountX(ctx context.Context) int {
	count, err := sgq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sgq *SupportGrantQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sgq.ctx, ent.OpQueryExist)
	switch _, err := sgq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sgq *SupportGrantQuery) ExistX(ctx context.Context) bool {
	exist, err := sgq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SupportGrantQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sgq *SupportGrantQuery) Clone() *SupportGrantQuery {
	if sgq == nil {
		return nil
	}
	return &SupportGrantQuery{
		config:     sgq.config,
		ctx:        sgq.ctx.Clone(),
		order:      append([]supportgrant.OrderOption{}, sgq.order...),
		inters:     append([]Interceptor{}, sgq.inters...),
		predicates: append([]predicate.SupportGrant{}, sgq.predicates...),
		// clone intermediate query.
		sql:  sgq.sql.Clone(),
		path: sgq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		InstitutionID uuid.UUID `json:"institution_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SupportGrant.Query().
//		GroupBy(supportgrant.FieldInstitutionID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sgq *SupportGrantQuery) GroupBy(field string, fields ...string) *SupportGrantGroupBy {
	sgq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SupportGrantGroupBy{build: sgq}
	grbuild.flds = &sgq.ctx.Fields
	grbuild.label = supportgrant.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		InstitutionID uuid.UUID `json:"institution_id,omitempty"`
//	}
//
//	client.SupportGrant.Query().
//		Select(supportgrant.FieldInstitutionID).
//		Scan(ctx, &v)
func (sgq *SupportGrantQuery) Select(fields ...string) *SupportGrantSelect {
	sgq.ctx.Fields = append(sgq.ctx.Fields, fields...)
	sbuild := &SupportGrantSelect{SupportGrantQuery: sgq}
	sbuild.label = supportgrant.Label
	sbuild.flds, sbuild.scan = &sgq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SupportGrantSelect configured with the given aggregations.
func (sgq *SupportGrantQuery) Aggregate(fns ...AggregateFunc) *SupportGrantSelect {
	return sgq.Select().Aggregate(fns...)
}

func (sgq *SupportGrantQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sgq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sgq); err != nil {
				return err
			}
		}
	}
	for _, f := range sgq.ctx.Fields {
		if !supportgrant.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sgq.path != nil {
		prev, err := sgq.path(ctx)
		if err != nil {
			return err
		}
		sgq.sql = prev
	}
	return nil
}

func (sgq *SupportGrantQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SupportGrant, error) {
	var (
		nodes = []*SupportGrant{}
		_spec = sgq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SupportGrant).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SupportGrant{config: sgq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sgq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (sgq *SupportGrantQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sgq.querySpec()
	_spec.Node.Columns = sgq.ctx.Fields
	if len(sgq.ctx.Fields) > 0 {
		_spec.Unique = sgq.ctx.Unique != nil && *sgq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sgq.driver, _spec)
}

func (sgq *SupportGrantQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(supportgrant.Table, supportgrant.Columns, sqlgraph.NewFieldSpec(supportgrant.FieldID, field.TypeUUID))
	_spec.From = sgq.sql
	if unique := sgq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sgq.path != nil {
		_spec.Unique = true
	}
	if fields := sgq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supportgrant.FieldID)
		for i := range fields {
			if fields[i] != supportgrant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sgq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sgq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sgq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sgq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sgq *SupportGrantQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sgq.driver.Dialect())
	t1 := builder.Table(supportgrant.Table)
	columns := sgq.ctx.Fields
	if len(columns) == 0 {
		columns = supportgrant.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sgq.sql != nil {
		selector = sgq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sgq.ctx.Unique != nil && *sgq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sgq.predicates {
		p(selector)
	}
	for _, p := range sgq.order {
		p(selector)
	}
	if offset := sgq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sgq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SupportGrantGroupBy is the group-by builder for SupportGrant entities.
type SupportGrantGroupBy struct {
	selector
	build *SupportGrantQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sggb *SupportGrantGroupBy) Aggregate(fns ...AggregateFunc) *SupportGrantGroupBy {
	sggb.fns = append(sggb.fns, fns...)
	return sggb
}

// Scan applies the selector query and scans the result into the given value.
func (sggb *SupportGrantGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sggb.build.ctx, ent.OpQueryGroupBy)
	if err := sggb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SupportGrantQuery, *SupportGrantGroupBy](ctx, sggb.build, sggb, sggb.build.inters, v)
}

func (sggb *SupportGrantGroupBy) sqlScan(ctx context.Context, root *SupportGrantQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sggb.fns))
	for _, fn := range sggb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sggb.flds)+len(sggb.fns))
		for _, f := range *sggb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sggb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sggb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SupportGrantSelect is the builder for selecting fields of SupportGrant entities.
type SupportGrantSelect struct {
	*SupportGrantQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sgs *SupportGrantSelect) Aggregate(fns ...AggregateFunc) *SupportGrantSelect {
	sgs.fns = append(sgs.fns, fns...)
	return sgs
}

// Scan applies the selector query and scans the result into the given value.
func (sgs *SupportGrantSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sgs.ctx, ent.OpQuerySelect)
	if err := sgs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SupportGrantQuery, *SupportGrantSelect](ctx, sgs.SupportGrantQuery, sgs, sgs.inters, v)
}

func (sgs *SupportGrantSelect) sqlScan(ctx context.Context, root *SupportGrantQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sgs.fns))
	for _, fn := range sgs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sgs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sgs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
