// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"grantsupport/ent/predicate"
	"grantsupport/ent/supportgrant"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SupportGrantUpdate is the builder for updating SupportGrant entities.
type SupportGrantUpdate struct {
	config
	hooks    []Hook
	mutation *SupportGrantMutation
}

// Where appends a list predicates to the SupportGrantUpdate builder.
func (sgu *SupportGrantUpdate) Where(ps ...predicate.SupportGrant) *SupportGrantUpdate {
	sgu.mutation.Where(ps...)
	return sgu
}

// SetInstitutionID sets the "institution_id" field.
func (sgu *SupportGrantUpdate) SetInstitutionID(u uuid.UUID) *SupportGrantUpdate {
	sgu.mutation.SetInstitutionID(u)
	return sgu
}

// SetNillableInstitutionID sets the "institution_id" field if the given value is not nil.
func (sgu *SupportGrantUpdate) SetNillableInstitutionID(u *uuid.UUID) *SupportGrantUpdate {
	if u != nil {
		sgu.SetInstitutionID(*u)
	}
	return sgu
}

// SetGrantedByID sets the "granted_by_id" field.
func (sgu *SupportGrantUpdate) SetGrantedByID(u uuid.UUID) *SupportGrantUpdate {
	sgu.mutation.SetGrantedByID(u)
	return sgu
}

// SetNillableGrantedByID sets the "granted_by_id" field if the given value is not nil.
func (sgu *SupportGrantUpdate) SetNillableGrantedByID(u *uuid.UUID) *SupportGrantUpdate {
	if u != nil {
		sgu.SetGrantedByID(*u)
	}
	return sgu
}

// SetUsedByID sets the "used_by_id" field.
func (sgu *SupportGrantUpdate) SetUsedByID(u uuid.UUID) *SupportGrantUpdate {
	sgu.mutation.SetUsedByID(u)
	return sgu
}

// SetNillableUsedByID sets the "used_by_id" field if the given value is not nil.
func (sgu *SupportGrantUpdate) SetNillableUsedByID(u *uuid.UUID) *SupportGrantUpdate {
	if u != nil {
		sgu.SetUsedByID(*u)
	}
	return sgu
}

// ClearUsedByID clears the value of the "used_by_id" field.
func (sgu *SupportGrantUpdate) ClearUsedByID() *SupportGrantUpdate {
	sgu.mutation.ClearUsedByID()
	return sgu
}

// SetTokenHash sets the "token_hash" field.
func (sgu *SupportGrantUpdate) SetTokenHash(s string) *SupportGrantUpdate {
	sgu.mutation.SetTokenHash(s)
	return sgu
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (sgu *SupportGrantUpdate) SetNillableTokenHash(s *string) *SupportGrantUpdate {
	if s != nil {
		sgu.SetTokenHash(*s)
	}
	return sgu
}

// SetExpiresAt sets the "expires_at" field.
func (sgu *SupportGrantUpdate) SetExpiresAt(t time.Time) *SupportGrantUpdate {
	sgu.mutation.SetExpiresAt(t)
	return sgu
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (sgu *SupportGrantUpdate) SetNillableExpiresAt(t *time.Time) *SupportGrantUpdate {
	if t != nil {
		sgu.SetExpiresAt(*t)
	}
	return sgu
}

// SetIsUsed sets the "is_used" field.
func (sgu *SupportGrantUpdate) SetIsUsed(b bool) *SupportGrantUpdate {
	sgu.mutation.SetIsUsed(b)
	return sgu
}

// SetNillableIsUsed sets the "is_used" field if the given value is not nil.
func (sgu *SupportGrantUpdate) SetNillableIsUsed(b *bool) *SupportGrantUpdate {
	if b != nil {
		sgu.SetIsUsed(*b)
	}
	return sgu
}

// SetUsedAt sets the "used_at" field.
func (sgu *SupportGrantUpdate) SetUsedAt(t time.Time) *SupportGrantUpdate {
	sgu.mutation.SetUsedAt(t)
	return sgu
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (sgu *SupportGrantUpdate) SetNillableUsedAt(t *time.Time) *SupportGrantUpdate {
	if t != nil {
		sgu.SetUsedAt(*t)
	}
	return sgu
}

// ClearUsedAt clears the value of the "used_at" field.
func (sgu *SupportGrantUpdate) ClearUsedAt() *SupportGrantUpdate {
	sgu.mutation.ClearUsedAt()
	return sgu
}

// SetScope sets the "scope" field.
func (sgu *SupportGrantUpdate) SetScope(s string) *SupportGrantUpdate {
	sgu.mutation.SetScope(s)
	return sgu
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (sgu *SupportGrantUpdate) SetNillableScope(s *string) *SupportGrantUpdate {
	if s != nil {
		sgu.SetScope(*s)
	}
	return sgu
}

// SetWhitelistedIps sets the "whitelisted_ips" field.
func (sgu *SupportGrantUpdate) SetWhitelistedIps(s []string) *SupportGrantUpdate {
	sgu.mutation.SetWhitelistedIps(s)
	return sgu
}

// AppendWhitelistedIps appends s to the "whitelisted_ips" field.
func (sgu *SupportGrantUpdate) AppendWhitelistedIps(s []string) *SupportGrantUpdate {
	sgu.mutation.AppendWhitelistedIps(s)
	return sgu
}

// ClearWhitelistedIps clears the value of the "whitelisted_ips" field.
func (sgu *SupportGrantUpdate) ClearWhitelistedIps() *SupportGrantUpdate {
	sgu.mutation.ClearWhitelistedIps()
	return sgu
}

// SetCreatedAt sets the "created_at" field.
func (sgu *SupportGrantUpdate) SetCreatedAt(t time.Time) *SupportGrantUpdate {
	sgu.mutation.SetCreatedAt(t)
	return sgu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sgu *SupportGrantUpdate) SetNillableCreatedAt(t *time.Time) *SupportGrantUpdate {
	if t != nil {
		sgu.SetCreatedAt(*t)
	}
	return sgu
}

// Mutation returns the SupportGrantMutation object of the builder.
func (sgu *SupportGrantUpdate) Mutation() *SupportGrantMutation {
	return sgu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (sgu *SupportGrantUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, sgu.sqlSave, sgu.mutation, sgu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (sgu *SupportGrantUpdate) SaveX(ctx context.Context) int {
	affected, err := sgu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (sgu *SupportGrantUpdate) Exec(ctx context.Context) error {
	_, err := sgu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sgu *SupportGrantUpdate) ExecX(ctx context.Context) {
	if err := sgu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (sgu *SupportGrantUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(supportgrant.Table, supportgrant.Columns, sqlgraph.NewFieldSpec(supportgrant.FieldID, field.TypeUUID))
	if ps := sgu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sgu.mutation.InstitutionID(); ok {
		_spec.SetField(supportgrant.FieldInstitutionID, field.TypeUUID, value)
	}
	if value, ok := sgu.mutation.GrantedByID(); ok {
		_spec.SetField(supportgrant.FieldGrantedByID, field.TypeUUID, value)
	}
	if value, ok := sgu.mutation.UsedByID(); ok {
		_spec.SetField(supportgrant.FieldUsedByID, field.TypeUUID, value)
	}
	if sgu.mutation.UsedByIDCleared() {
		_spec.ClearField(supportgrant.FieldUsedByID, field.TypeUUID)
	}
	if value, ok := sgu.mutation.TokenHash(); ok {
		_spec.SetField(supportgrant.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := sgu.mutation.ExpiresAt(); ok {
		_spec.SetField(supportgrant.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := sgu.mutation.IsUsed(); ok {
		_spec.SetField(supportgrant.FieldIsUsed, field.TypeBool, value)
	}
	if value, ok := sgu.mutation.UsedAt(); ok {
		_spec.SetField(supportgrant.FieldUsedAt, field.TypeTime, value)
	}
	if sgu.mutation.UsedAtCleared() {
		_spec.ClearField(supportgrant.FieldUsedAt, field.TypeTime)
	}
	if value, ok := sgu.mutation.Scope(); ok {
		_spec.SetField(supportgrant.FieldScope, field.TypeString, value)
	}
	if value, ok := sgu.mutation.WhitelistedIps(); ok {
		_spec.SetField(supportgrant.FieldWhitelistedIps, field.TypeJSON, value)
	}
	if value, ok := sgu.mutation.AppendedWhitelistedIps(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, supportgrant.FieldWhitelistedIps, value)
		})
	}
	if sgu.mutation.WhitelistedIpsCleared() {
		_spec.ClearField(supportgrant.FieldWhitelistedIps, field.TypeJSON)
	}
	if value, ok := sgu.mutation.CreatedAt(); ok {
		_spec.SetField(supportgrant.FieldCreatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, sgu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportgrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	sgu.mutation.done = true
	return n, nil
}

// SupportGrantUpdateOne is the builder for updating a single SupportGrant entity.
type SupportGrantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupportGrantMutation
}

// SetInstitutionID sets the "institution_id" field.
func (sguo *SupportGrantUpdateOne) SetInstitutionID(u uuid.UUID) *SupportGrantUpdateOne {
	sguo.mutation.SetInstitutionID(u)
	return sguo
}

// SetNillableInstitutionID sets the "institution_id" field if the given value is not nil.
func (sguo *SupportGrantUpdateOne) SetNillableInstitutionID(u *uuid.UUID) *SupportGrantUpdateOne {
	if u != nil {
		sguo.SetInstitutionID(*u)
	}
	return sguo
}

// SetGrantedByID sets the "granted_by_id" field.
func (sguo *SupportGrantUpdateOne) SetGrantedByID(u uuid.UUID) *SupportGrantUpdateOne {
	sguo.mutation.SetGrantedByID(u)
	return sguo
}

// SetNillableGrantedByID sets the "granted_by_id" field if the given value is not nil.
func (sguo *SupportGrantUpdateOne) SetNillableGrantedByID(u *uuid.UUID) *SupportGrantUpdateOne {
	if u != nil {
		sguo.SetGrantedByID(*u)
	}
	return sguo
}

// SetUsedByID sets the "used_by_id" field.
func (sguo *SupportGrantUpdateOne) SetUsedByID(u uuid.UUID) *SupportGrantUpdateOne {
	sguo.mutation.SetUsedByID(u)
	return sguo
}

// SetNillableUsedByID sets the "used_by_id" field if the given value is not nil.
func (sguo *SupportGrantUpdateOne) SetNillableUsedByID(u *uuid.UUID) *SupportGrantUpdateOne {
	if u != nil {
		sguo.SetUsedByID(*u)
	}
	return sguo
}

// ClearUsedByID clears the value of the "used_by_id" field.
func (sguo *SupportGrantUpdateOne) ClearUsedByID() *SupportGrantUpdateOne {
	sguo.mutation.ClearUsedByID()
	return sguo
}

// SetTokenHash sets the "token_hash" field.
func (sguo *SupportGrantUpdateOne) SetTokenHash(s string) *SupportGrantUpdateOne {
	sguo.mutation.SetTokenHash(s)
	return sguo
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (sguo *SupportGrantUpdateOne) SetNillableTokenHash(s *string) *SupportGrantUpdateOne {
	if s != nil {
		sguo.SetTokenHash(*s)
	}
	return sguo
}

// SetExpiresAt sets the "expires_at" field.
func (sguo *SupportGrantUpdateOne) SetExpiresAt(t time.Time) *SupportGrantUpdateOne {
	sguo.mutation.SetExpiresAt(t)
	return sguo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (sguo *SupportGrantUpdateOne) SetNillableExpiresAt(t *time.Time) *SupportGrantUpdateOne {
	if t != nil {
		sguo.SetExpiresAt(*t)
	}
	return sguo
}

// SetIsUsed sets the "is_used" field.
func (sguo *SupportGrantUpdateOne) SetIsUsed(b bool) *SupportGrantUpdateOne {
	sguo.mutation.SetIsUsed(b)
	return sguo
}

// SetNillableIsUsed sets the "is_used" field if the given value is not nil.
func (sguo *SupportGrantUpdateOne) SetNillableIsUsed(b *bool) *SupportGrantUpdateOne {
	if b != nil {
		sguo.SetIsUsed(*b)
	}
	return sguo
}

// SetUsedAt sets the "used_at" field.
func (sguo *SupportGrantUpdateOne) SetUsedAt(t time.Time) *SupportGrantUpdateOne {
	sguo.mutation.SetUsedAt(t)
	return sguo
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (sguo *SupportGrantUpdateOne) SetNillableUsedAt(t *time.Time) *SupportGrantUpdateOne {
	if t != nil {
		sguo.SetUsedAt(*t)
	}
	return sguo
}

// ClearUsedAt clears the value of the "used_at" field.
func (sguo *SupportGrantUpdateOne) ClearUsedAt() *SupportGrantUpdateOne {
	sguo.mutation.ClearUsedAt()
	return sguo
}

// SetScope sets the "scope" field.
func (sguo *SupportGrantUpdateOne) SetScope(s string) *SupportGrantUpdateOne {
	sguo.mutation.SetScope(s)
	return sguo
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (sguo *SupportGrantUpdateOne) SetNillableScope(s *string) *SupportGrantUpdateOne {
	if s != nil {
		sguo.SetScope(*s)
	}
	return sguo
}

// SetWhitelistedIps sets the "whitelisted_ips" field.
func (sguo *SupportGrantUpdateOne) SetWhitelistedIps(s []string) *SupportGrantUpdateOne {
	sguo.mutation.SetWhitelistedIps(s)
	return sguo
}

// AppendWhitelistedIps appends s to the "whitelisted_ips" field.
func (sguo *SupportGrantUpdateOne) AppendWhitelistedIps(s []string) *SupportGrantUpdateOne {
	sguo.mutation.AppendWhitelistedIps(s)
	return sguo
}

// ClearWhitelistedIps clears the value of the "whitelisted_ips" field.
func (sguo *SupportGrantUpdateOne) ClearWhitelistedIps() *SupportGrantUpdateOne {
	sguo.mutation.ClearWhitelistedIps()
	return sguo
}

// SetCreatedAt sets the "created_at" field.
func (sguo *SupportGrantUpdateOne) SetCreatedAt(t time.Time) *SupportGrantUpdateOne {
	sguo.mutation.SetCreatedAt(t)
	return sguo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sguo *SupportGrantUpdateOne) SetNillableCreatedAt(t *time.Time) *SupportGrantUpdateOne {
	if t != nil {
		sguo.SetCreatedAt(*t)
	}
	return sguo
}

// Mutation returns the SupportGrantMutation object of the builder.
func (sguo *SupportGrantUpdateOne) Mutation() *SupportGrantMutation {
	return sguo.mutation
}

// Where appends a list predicates to the SupportGrantUpdate builder.
func (sguo *SupportGrantUpdateOne) Where(ps ...predicate.SupportGrant) *SupportGrantUpdateOne {
	sguo.mutation.Where(ps...)
	return sguo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (sguo *SupportGrantUpdateOne) Select(field string, fields ...string) *SupportGrantUpdateOne {
	sguo.fields = append([]string{field}, fields...)
	return sguo
}

// Save executes the query and returns the updated SupportGrant entity.
func (sguo *SupportGrantUpdateOne) Save(ctx context.Context) (*SupportGrant, error) {
	return withHooks(ctx, sguo.sqlSave, sguo.mutation, sguo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (sguo *SupportGrantUpdateOne) SaveX(ctx context.Context) *SupportGrant {
	node, err := sguo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (sguo *SupportGrantUpdateOne) Exec(ctx context.Context) error {
	_, err := sguo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sguo *SupportGrantUpdateOne) ExecX(ctx context.Context) {
	if err := sguo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (sguo *SupportGrantUpdateOne) sqlSave(ctx context.Context) (_node *SupportGrant, err error) {
	_spec := sqlgraph.NewUpdateSpec(supportgrant.Table, supportgrant.Columns, sqlgraph.NewFieldSpec(supportgrant.FieldID, field.TypeUUID))
	id, ok := sguo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupportGrant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := sguo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supportgrant.FieldID)
		for _, f := range fields {
			if !supportgrant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supportgrant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := sguo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sguo.mutation.InstitutionID(); ok {
		_spec.SetField(supportgrant.FieldInstitutionID, field.TypeUUID, value)
	}
	if value, ok := sguo.mutation.GrantedByID(); ok {
		_spec.SetField(supportgrant.FieldGrantedByID, field.TypeUUID, value)
	}
	if value, ok := sguo.mutation.UsedByID(); ok {
		_spec.SetField(supportgrant.FieldUsedByID, field.TypeUUID, value)
	}
	if sguo.mutation.UsedByIDCleared() {
		_spec.ClearField(supportgrant.FieldUsedByID, field.TypeUUID)
	}
	if value, ok := sguo.mutation.TokenHash(); ok {
		_spec.SetField(supportgrant.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := sguo.mutation.ExpiresAt(); ok {
		_spec.SetField(supportgrant.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := sguo.mutation.IsUsed(); ok {
		_spec.SetField(supportgrant.FieldIsUsed, field.TypeBool, value)
	}
	if value, ok := sguo.mutation.UsedAt(); ok {
		_spec.SetField(supportgrant.FieldUsedAt, field.TypeTime, value)
	}
	if sguo.mutation.UsedAtCleared() {
		_spec.ClearField(supportgrant.FieldUsedAt, field.TypeTime)
	}
	if value, ok := sguo.mutation.Scope(); ok {
		_spec.SetField(supportgrant.FieldScope, field.TypeString, value)
	}
	if value, ok := sguo.mutation.WhitelistedIps(); ok {
		_spec.SetField(supportgrant.FieldWhitelistedIps, field.TypeJSON, value)
	}
	if value, ok := sguo.mutation.AppendedWhitelistedIps(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, supportgrant.FieldWhitelistedIps, value)
		})
	}
	if sguo.mutation.WhitelistedIpsCleared() {
		_spec.ClearField(supportgrant.FieldWhitelistedIps, field.TypeJSON)
	}
	if value, ok := sguo.mutation.CreatedAt(); ok {
		_spec.SetField(supportgrant.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &SupportGrant{config: sguo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, sguo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportgrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	sguo.mutation.done = true
	return _node, nil
}
