// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"grantsupport/ent/supportgrant"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// SupportGrant is the model entity for the SupportGrant schema.
type SupportGrant struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// InstitutionID holds the value of the "institution_id" field.
	InstitutionID uuid.UUID `json:"institution_id,omitempty"`
	// GrantedByID holds the value of the "granted_by_id" field.
	GrantedByID uuid.UUID `json:"granted_by_id,omitempty"`
	// TokenHash holds the value of the "token_hash" field.
	TokenHash string `json:"token_hash,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// IsUsed holds the value of the "is_used" field.
	IsUsed bool `json:"is_used,omitempty"`
	// UsedAt holds the value of the "used_at" field.
	UsedAt *time.Time `json:"used_at,omitempty"`
	// Scope holds the value of the "scope" field.
	Scope string `json:"scope,omitempty"`
	// WhitelistedIps holds the value of the "whitelisted_ips" field.
	WhitelistedIps []string `json:"whitelisted_ips,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SupportGrant) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case supportgrant.FieldWhitelistedIps:
			values[i] = new([]byte)
		case supportgrant.FieldIsUsed:
			values[i] = new(sql.NullBool)
		case supportgrant.FieldTokenHash, supportgrant.FieldScope:
			values[i] = new(sql.NullString)
		case supportgrant.FieldExpiresAt, supportgrant.FieldUsedAt, supportgrant.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case supportgrant.FieldID, supportgrant.FieldInstitutionID, supportgrant.FieldGrantedByID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SupportGrant fields.
func (sg *SupportGrant) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case supportgrant.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				sg.ID = *value
			}
		case supportgrant.FieldInstitutionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field institution_id", values[i])
			} else if value != nil {
				sg.InstitutionID = *value
			}
		case supportgrant.FieldGrantedByID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field granted_by_id", values[i])
			} else if value != nil {
				sg.GrantedByID = *value
			}
		case supportgrant.FieldTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_hash", values[i])
			} else if value.Valid {
				sg.TokenHash = value.String
			}
		case supportgrant.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				sg.ExpiresAt = value.Time
			}
		case supportgrant.FieldIsUsed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_used", values[i])
			} else if value.Valid {
				sg.IsUsed = value.Bool
			}
		case supportgrant.FieldUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field used_at", values[i])
			} else if value.Valid {
				sg.UsedAt = new(time.Time)
				*sg.UsedAt = value.Time
			}
		case supportgrant.FieldScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope", values[i])
			} else if value.Valid {
				sg.Scope = value.String
			}
		case supportgrant.FieldWhitelistedIps:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field whitelisted_ips", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &sg.WhitelistedIps); err != nil {
					return fmt.Errorf("unmarshal field whitelisted_ips: %w", err)
				}
			}
		case supportgrant.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				sg.CreatedAt = value.Time
			}
		default:
			sg.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SupportGrant.
// This includes values selected through modifiers, order, etc.
func (sg *SupportGrant) Value(name string) (ent.Value, error) {
	return sg.selectValues.Get(name)
}

// Update returns a builder for updating this SupportGrant.
// Note that you need to call SupportGrant.Unwrap() before calling this method if this SupportGrant
// was returned from a transaction, and the transaction was committed or rolled back.
func (sg *SupportGrant) Update() *SupportGrantUpdateOne {
	return NewSupportGrantClient(sg.config).UpdateOne(sg)
}

// Unwrap unwraps the SupportGrant entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sg *SupportGrant) Unwrap() *SupportGrant {
	_tx, ok := sg.config.driver.(*txDriver)
	if !ok {
		panic("ent: SupportGrant is not a transactional entity")
	}
	sg.config.driver = _tx.drv
	return sg
}

// String implements the fmt.Stringer.
func (sg *SupportGrant) String() string {
	var builder strings.Builder
	builder.WriteString("SupportGrant(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sg.ID))
	builder.WriteString("institution_id=")
	builder.WriteString(fmt.Sprintf("%v", sg.InstitutionID))
	builder.WriteString(", ")
	builder.WriteString("granted_by_id=")
	builder.WriteString(fmt.Sprintf("%v", sg.GrantedByID))
	builder.WriteString(", ")
	builder.WriteString("token_hash=")
	builder.WriteString(sg.TokenHash)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(sg.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("is_used=")
	builder.WriteString(fmt.Sprintf("%v", sg.IsUsed))
	builder.WriteString(", ")
	if v := sg.UsedAt; v != nil {
		builder.WriteString("used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("scope=")
	builder.WriteString(sg.Scope)
	builder.WriteString(", ")
	builder.WriteString("whitelisted_ips=")
	builder.WriteString(fmt.Sprintf("%v", sg.WhitelistedIps))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(sg.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SupportGrants is a parsable slice of SupportGrant.
type SupportGrants []*SupportGrant
