// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"grantsupport/ent/supportgrant"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SupportGrantCreate is the builder for creating a SupportGrant entity.
type SupportGrantCreate struct {
	config
	mutation *SupportGrantMutation
	hooks    []Hook
}

// SetInstitutionID sets the "institution_id" field.
func (sgc *SupportGrantCreate) SetInstitutionID(u uuid.UUID) *SupportGrantCreate {
	sgc.mutation.SetInstitutionID(u)
	return sgc
}

// SetGrantedByID sets the "granted_by_id" field.
func (sgc *SupportGrantCreate) SetGrantedByID(u uuid.UUID) *SupportGrantCreate {
	sgc.mutation.SetGrantedByID(u)
	return sgc
}

// SetUsedByID sets the "used_by_id" field.
func (sgc *SupportGrantCreate) SetUsedByID(u uuid.UUID) *SupportGrantCreate {
	sgc.mutation.SetUsedByID(u)
	return sgc
}

// SetNillableUsedByID sets the "used_by_id" field if the given value is not nil.
func (sgc *SupportGrantCreate) SetNillableUsedByID(u *uuid.UUID) *SupportGrantCreate {
	if u != nil {
		sgc.SetUsedByID(*u)
	}
	return sgc
}

// SetTokenHash sets the "token_hash" field.
func (sgc *SupportGrantCreate) SetTokenHash(s string) *SupportGrantCreate {
	sgc.mutation.SetTokenHash(s)
	return sgc
}

// SetExpiresAt sets the "expires_at" field.
func (sgc *SupportGrantCreate) SetExpiresAt(t time.Time) *SupportGrantCreate {
	sgc.mutation.SetExpiresAt(t)
	return sgc
}

// SetIsUsed sets the "is_used" field.
func (sgc *SupportGrantCreate) SetIsUsed(b bool) *SupportGrantCreate {
	sgc.mutation.SetIsUsed(b)
	return sgc
}

// SetNillableIsUsed sets the "is_used" field if the given value is not nil.
func (sgc *SupportGrantCreate) SetNillableIsUsed(b *bool) *SupportGrantCreate {
	if b != nil {
		sgc.SetIsUsed(*b)
	}
	return sgc
}

// SetUsedAt sets the "used_at" field.
func (sgc *SupportGrantCreate) SetUsedAt(t time.Time) *SupportGrantCreate {
	sgc.mutation.SetUsedAt(t)
	return sgc
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (sgc *SupportGrantCreate) SetNillableUsedAt(t *time.Time) *SupportGrantCreate {
	if t != nil {
		sgc.SetUsedAt(*t)
	}
	return sgc
}

// SetScope sets the "scope" field.
func (sgc *SupportGrantCreate) SetScope(s string) *SupportGrantCreate {
	sgc.mutation.SetScope(s)
	return sgc
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (sgc *SupportGrantCreate) SetNillableScope(s *string) *SupportGrantCreate {
	if s != nil {
		sgc.SetScope(*s)
	}
	return sgc
}

// SetWhitelistedIps sets the "whitelisted_ips" field.
func (sgc *SupportGrantCreate) SetWhitelistedIps(s []string) *SupportGrantCreate {
	sgc.mutation.SetWhitelistedIps(s)
	return sgc
}

// SetCreatedAt sets the "created_at" field.
func (sgc *SupportGrantCreate) SetCreatedAt(t time.Time) *SupportGrantCreate {
	sgc.mutation.SetCreatedAt(t)
	return sgc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sgc *SupportGrantCreate) SetNillableCreatedAt(t *time.Time) *SupportGrantCreate {
	if t != nil {
		sgc.SetCreatedAt(*t)
	}
	return sgc
}

// SetID sets the "id" field.
func (sgc *SupportGrantCreate) SetID(u uuid.UUID) *SupportGrantCreate {
	sgc.mutation.SetID(u)
	return sgc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (sgc *SupportGrantCreate) SetNillableID(u *uuid.UUID) *SupportGrantCreate {
	if u != nil {
		sgc.SetID(*u)
	}
	return sgc
}

// Mutation returns the SupportGrantMutation object of the builder.
func (sgc *SupportGrantCreate) Mutation() *SupportGrantMutation {
	return sgc.mutation
}

// Save creates the SupportGrant in the database.
func (sgc *SupportGrantCreate) Save(ctx context.Context) (*SupportGrant, error) {
	sgc.defaults()
	return withHooks(ctx, sgc.sqlSave, sgc.mutation, sgc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sgc *SupportGrantCreate) SaveX(ctx context.Context) *SupportGrant {
	v, err := sgc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sgc *SupportGrantCreate) Exec(ctx context.Context) error {
	_, err := sgc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sgc *SupportGrantCreate) ExecX(ctx context.Context) {
	if err := sgc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sgc *SupportGrantCreate) defaults() {
	if _, ok := sgc.mutation.IsUsed(); !ok {
		v := supportgrant.DefaultIsUsed
		sgc.mutation.SetIsUsed(v)
	}
	if _, ok := sgc.mutation.Scope(); !ok {
		v := supportgrant.DefaultScope
		sgc.mutation.SetScope(v)
	}
	if _, ok := sgc.mutation.WhitelistedIps(); !ok {
		v := supportgrant.DefaultWhitelistedIps
		sgc.mutation.SetWhitelistedIps(v)
	}
	if _, ok := sgc.mutation.CreatedAt(); !ok {
		v := supportgrant.DefaultCreatedAt()
		sgc.mutation.SetCreatedAt(v)
	}
	if _, ok := sgc.mutation.ID(); !ok {
		v := supportgrant.DefaultID()
		sgc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sgc *SupportGrantCreate) check() error {
	if _, ok := sgc.mutation.InstitutionID(); !ok {
		return &ValidationError{Name: "institution_id", err: errors.New(`ent: missing required field "SupportGrant.institution_id"`)}
	}
	if _, ok := sgc.mutation.GrantedByID(); !ok {
		return &ValidationError{Name: "granted_by_id", err: errors.New(`ent: missing required field "SupportGrant.granted_by_id"`)}
	}
	if _, ok := sgc.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "SupportGrant.token_hash"`)}
	}
	if _, ok := sgc.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "SupportGrant.expires_at"`)}
	}
	if _, ok := sgc.mutation.IsUsed(); !ok {
		return &ValidationError{Name: "is_used", err: errors.New(`ent: missing required field "SupportGrant.is_used"`)}
	}
	if _, ok := sgc.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "SupportGrant.scope"`)}
	}
	if _, ok := sgc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SupportGrant.created_at"`)}
	}
	return nil
}

func (sgc *SupportGrantCreate) sqlSave(ctx context.Context) (*SupportGrant, error) {
	if err := sgc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sgc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sgc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	sgc.mutation.id = &_node.ID
	sgc.mutation.done = true
	return _node, nil
}

func (sgc *SupportGrantCreate) createSpec() (*SupportGrant, *sqlgraph.CreateSpec) {
	var (
		_node = &SupportGrant{config: sgc.config}
		_spec = sqlgraph.NewCreateSpec(supportgrant.Table, sqlgraph.NewFieldSpec(supportgrant.FieldID, field.TypeUUID))
	)
	if id, ok := sgc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := sgc.mutation.InstitutionID(); ok {
		_spec.SetField(supportgrant.FieldInstitutionID, field.TypeUUID, value)
		_node.InstitutionID = value
	}
	if value, ok := sgc.mutation.GrantedByID(); ok {
		_spec.SetField(supportgrant.FieldGrantedByID, field.TypeUUID, value)
		_node.GrantedByID = value
	}
	if value, ok := sgc.mutation.UsedByID(); ok {
		_spec.SetField(supportgrant.FieldUsedByID, field.TypeUUID, value)
		_node.UsedByID = &value
	}
	if value, ok := sgc.mutation.TokenHash(); ok {
		_spec.SetField(supportgrant.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = value
	}
	if value, ok := sgc.mutation.ExpiresAt(); ok {
		_spec.SetField(supportgrant.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := sgc.mutation.IsUsed(); ok {
		_spec.SetField(supportgrant.FieldIsUsed, field.TypeBool, value)
		_node.IsUsed = value
	}
	if value, ok := sgc.mutation.UsedAt(); ok {
		_spec.SetField(supportgrant.FieldUsedAt, field.TypeTime, value)
		_node.UsedAt = &value
	}
	if value, ok := sgc.mutation.Scope(); ok {
		_spec.SetField(supportgrant.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := sgc.mutation.WhitelistedIps(); ok {
		_spec.SetField(supportgrant.FieldWhitelistedIps, field.TypeJSON, value)
		_node.WhitelistedIps = value
	}
	if value, ok := sgc.mutation.CreatedAt(); ok {
		_spec.SetField(supportgrant.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// SupportGrantCreateBulk is the builder for creating many SupportGrant entities in bulk.
type SupportGrantCreateBulk struct {
	config
	err      error
	builders []*SupportGrantCreate
}

// Save creates the SupportGrant entities in the database.
func (sgcb *SupportGrantCreateBulk) Save(ctx context.Context) ([]*SupportGrant, error) {
	if sgcb.err != nil {
		return nil, sgcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(sgcb.builders))
	nodes := make([]*SupportGrant, len(sgcb.builders))
	mutators := make([]Mutator, len(sgcb.builders))
	for i := range sgcb.builders {
		func(i int, root context.Context) {
			builder := sgcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SupportGrantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sgcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sgcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sgcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (sgcb *SupportGrantCreateBulk) SaveX(ctx context.Context) []*SupportGrant {
	v, err := sgcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sgcb *SupportGrantCreateBulk) Exec(ctx context.Context) error {
	_, err := sgcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sgcb *SupportGrantCreateBulk) ExecX(ctx context.Context) {
	if err := sgcb.Exec(ctx); err != nil {
		panic(err)
	}
}
