// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AccessRequest is the predicate function for accessrequest builders.
type AccessRequest func(*sql.Selector)

// AuditEvent is the predicate function for auditevent builders.
type AuditEvent func(*sql.Selector)

// SupportGrant is the predicate function for supportgrant builders.
type SupportGrant func(*sql.Selector)
